CppRandLib - c++11: Pcg128_64 Class Reference
Pcg128_64 Class Reference
Permutated Congruential Generator dedicated to 128-bits calculations and 64-bits output with medium period (about 3.40e+38).
#include <pcg128_64.h>
Public Types
using MyBaseClass = BasePCG<utils::UInt128, std::uint64_t>
using value_type = utils::UInt128
Public Member Functions
virtual void _setstate (const std::uint64_t seed_) noexcept override
Sets the internal state with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed_) noexcept override
Sets the internal state with a 128-bits integer seed.
virtual const output_type next () noexcept override
The internal PRNG algorithm.
Pcg128_64 () noexcept
Default empty constructor.
Pcg128_64 (const double seed)
Valued constructor (double).
Pcg128_64 (const int seed) noexcept
Valued constructor (int).
Pcg128_64 (const long long seed) noexcept
Valued constructor (long long).
Pcg128_64 (const long seed) noexcept
Valued constructor (long)
Pcg128_64 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Pcg128_64 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Pcg128_64 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Pcg128_64 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual void seed () noexcept override
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
Permutated Congruential Generator dedicated to 128-bits calculations and 64-bits output with medium period (about 3.40e+38).
The Pcg128_64 class implements the "PCG XSL RR 128/64 (LCG)" version of the PCG algorithm, as specified in the related paper (see reference [7] in document README.md). Output values are returned on 64 bits.
PCGs are very fast generators, with low memory usage except for a very few of them and medium to very large periods. They offer jump ahead and multi streams features for most of them. They are difficult to very difficult to invert and to predict.
See Pcg128_64 for a 2^64 (i.e. about 1.84e+19) period PC-Generator with low computation time and a shorter period than for Pcg128_64, with 4 32-bits word integers memory consumption. Output values are eturned on 32 bits.
See Pcg1024_32 for a 2^32,830 (i.e. about 6.53e+9,882) period PC-Generator with low computation time also and a very large period, but 1,026 32-bits word integers memory consumption. Output values are returned on 32 bits.
Furthermore this class is callable:
Squares32 rand{};                     // CAUTION: Replace 'BaseSquares' with any inheriting class constructor!
std::cout << rand() << std::endl;     // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;    // prints a uniform pseudo-random value within [0.0, b)
Please notice that for simulating the roll of a dice you may use any of:
Squares32 diceRoll{};  // CAUTION: Replace 'BaseSquares' with any inheriting class constructor!
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the PCG algorithms that have been implemented in CppRandLib, as provided in paper "TestU01, ..." and when available.
+------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class initial PCG algo name ([7]) Memory Usage Period time-64 bits SmallCrush fails Crush fails BigCrush fails
Pcg64_32 PCG XSH RS 64/32 (LCG) 2 x 4-bytes 2^64 0.79 0 0 0
Pcg128_64 PCG XSL RR 128/64 (LCG) 4 x 4-bytes 2^128 1.70 0 0 0
Pcg1024_32 PCG XSH RS 64/32 (EXT 1024) 1026 x 4-bytes 2^32,830 0.78 0 0 0
+------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Pcg128_64() [1/9]
Pcg128_64::Pcg128_64 () noexcept
Default empty constructor.
Empty constructor.
References seed().
Pcg128_64() [2/9]
Pcg128_64::Pcg128_64 (const int seed_) noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
Pcg128_64() [3/9]
Pcg128_64::Pcg128_64 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
Pcg128_64() [4/9]
Pcg128_64::Pcg128_64 (const long seed_) noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
Pcg128_64() [5/9]
Pcg128_64::Pcg128_64 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
Pcg128_64() [6/9]
Pcg128_64::Pcg128_64 (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
Pcg128_64() [7/9]
Pcg128_64::Pcg128_64 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
Pcg128_64() [8/9]
Pcg128_64::Pcg128_64 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References seed().
Pcg128_64() [9/9]
Pcg128_64::Pcg128_64 (const double seed_)
Valued constructor (double).
Valued constructor (double).
References seed().
Member Function Documentation
_setstate() [1/2]
void Pcg128_64::_setstate (const std::uint64_t seed) override virtual noexcept
Sets the internal state with a 64-bits integer seed.
Sets the internal state with an integer seed.
References seed().
_setstate() [2/2]
void Pcg128_64::_setstate (const utils::UInt128 & seed) override virtual noexcept
Sets the internal state with a 128-bits integer seed.
Sets the internal state with an UInt128 seed.
References seed().
next()
const Pcg128_64::output_type Pcg128_64::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
seed() [1/9]
void Pcg128_64::seed () inline override virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Referenced by _setstate(), _setstate(), Pcg128_64(), Pcg128_64(), Pcg128_64(), Pcg128_64(), Pcg128_64(), Pcg128_64(), Pcg128_64(), Pcg128_64(), Pcg128_64(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
void Pcg128_64::seed (const double seed_)
Initializes internal state (double).
Initializes internal state (double).
seed() [3/9]
void Pcg128_64::seed (const int seed_) noexcept
Initializes internal state (int).
Initializes internal state (int).
References seed().
seed() [4/9]
void Pcg128_64::seed (const long long seed_) noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References seed().
seed() [5/9]
void Pcg128_64::seed (const long seed_) noexcept
Initializes internal state (long)
Initializes internal state (long).
References seed().
seed() [6/9]
void Pcg128_64::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References seed().
seed() [7/9]
void Pcg128_64::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
seed() [8/9]
void Pcg128_64::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References seed().
seed() [9/9]
void Pcg128_64::seed (const utils::UInt128 & seed_) noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
The documentation for this class was generated from the following files:
pcg128_64.h
pcg128_64.cpp