CppRandLib - c++11: BaseRandom< StateT, OutputT, OUTPUT_BITS > Class Template Reference
BaseRandom< StateT, OutputT, OUTPUT_BITS > Class Template Reference
This is the base class for all pseudo-random numbers generators.
#include <baserandom.h>
Classes
struct _InternalState
Public Types
using output_type = OutputT
using state_type = StateT
Public Member Functions
BaseRandom () noexcept=default
default empty constructor.
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
template<typename CountT, typename ProbaT>
const CountT binomialvariate (CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
template<typename T, const std::size_t n>
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
template<typename T>
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
template<typename T>
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
template<typename T, typename C>
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
template<typename T, typename C>
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
OutputT getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be passed to setstate() later.
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
template<typename T, const std::size_t n>
std::array< T, n > n_evaluate ()
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
template<typename T, const std::size_t m, typename U = T, const std::size_t n = m>
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
template<typename T, const std::size_t m, typename U = T, const std::size_t n = m, typename V = U, const std::size_t p = n>
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
template<typename T>
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
template<typename T, typename U = T>
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
template<typename T, typename U = T>
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of n values in range [0; max[i]).
template<typename T, typename U = T, typename V = U>
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
template<typename T, const std::size_t n, typename U = T>
std::array< T, n > n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
template<typename T, const std::size_t n, typename U = T, typename V = U>
std::array< T, n > n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
virtual const output_type next () noexcept
The internal PRNG algorithm.
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
template<typename T = long double>
const T operator() () noexcept
Empty Call operator.
template<typename T, const std::size_t n>
std::array< T, n > operator() (const std::array< T, n > &max)
Valued call operator (1 std::array of scalars).
template<typename T, const std::size_t n>
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max)
Valued call operator (2 std::array of scalars).
template<typename T>
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
template<typename T>
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max)
Valued call operator (2 std::vector of scalars).
template<typename T = OutputT>
const T operator() (const T max)
Valued call operator (1 scalar).
template<typename T = OutputT>
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
template<typename T = OutputT>
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const StateT &new_internal_state) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
template<typename T>
const T randint (const T a, const T b)
Returns random integer in range [a, b], including both end points.
template<typename T = double>
const T random ()
The uniform distribution on [0.0, 1.0).
template<>
const long double random ()
template<typename T, typename S = T>
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
template<typename T, const std::size_t k, const std::size_t n>
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
template<typename T, typename C, const std::size_t k, const std::size_t n>
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
template<typename T>
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
template<typename T, typename C>
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
virtual void seed () noexcept
Initializes internal state (empty signature).
virtual void seed (const double seed_)
Initalizes internal state from a double seed.
virtual void seed (const int seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
virtual void seed (const long long seed_) noexcept
Initializes internal state from a 64-bits signed integer seed.
virtual void seed (const long seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
virtual void seed (const unsigned int seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
virtual void seed (const unsigned long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
virtual void seed (const unsigned long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
virtual void seed (const utils::UInt128 &seed_) noexcept
Initializes the internal state of this PRNG with a 128-bits integer seed.
void setstate (const StateT &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const StateT &new_internal_state, const double gauss_next) noexcept
Sets the internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
template<typename ContainerType>
void shuffle (ContainerType &seq)
Shuffles specified sequence in place.
const state_type state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
template<typename T = double>
const T uniform ()
Uniform distribution in [0.0, 1.0).
template<>
const double uniform (const double max)
template<>
const float uniform (const float max)
template<>
const long double uniform (const long double max)
template<typename T = double, typename U = T>
const T uniform (const U max)
Uniform distribution in [0.0, max).
template<typename T, typename U = T, typename V = U>
const T uniform (const U min, const V max)
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Public Attributes
struct BaseRandom::_InternalState _internal_state
Protected Member Functions
virtual void _setstate (const std::uint64_t seed) noexcept
Sets the internal state with an integer seed.
virtual void _setstate (const utils::UInt128 &seed_) noexcept
Sets the internal state with a 128-bits integer seed.
Static Protected Attributes
static constexpr std::uint64_t _MODULO { (((1ull << ((OUTPUT_BITS > 64 ? 64 : OUTPUT_BITS) - 1)) - 1) << 1) | 0x1 }
static constexpr double _NORMALIZE { double(_NORMALIZE_LD)}
static constexpr long double _NORMALIZE_LD
static const double BPF
static const double E
static const double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static const double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static const double TWO_PI
Detailed Description
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)>
class BaseRandom< StateT, OutputT, OUTPUT_BITS >
This is the base class for all pseudo-random numbers generators.
See Cwg64 for a minimum 2^70 (i.e. about 1.18e+21) period Collatz-Weyl Generator with low computation time, medium period, 64- bits output values and very good randomness characteristics. See Cwg128_64 for a minimum 2^71 (i.e. about 2.36e+21) period C-W Generator with with very low computation time, medium period, 64-bits output values and very good randomness characteristics. See Cwg128 for a minimum 2^135 (i.e. about 4.36e+40) period C-W generator with very low computation time, medium period, 64- bits output values and very good randomness characteristics.
See FastRand32 for a 2^32 (i.e. 4.29e+9) period Linear Congruential Generator and FastRand63 for a 2^63 (i.e. about 9.2e+18) period LC-Generator with very low computation time and very low memory consumption (resp. 1 and 2 32-bits integers).
See LFibRand78, LFibRand116, LFibRand668 and LFibRand1340 for large period Lagged Fibonacci Generators (resp. 2^78, 2^116, 2^668 and 2^1340 periods, i.e. resp. 3.0e+23, 8.3e+34, 1.2e+201 and 2.4e+403 periods) while same computation time and far higher precision (64-bits calculations) but memory consumption (resp. 17, 55, 607 and 1279 32-bits integers).
See Melg607 for a large period Maximally Equidistributed F2-Linear Generator (2^607, i.e. 5.31e+182) with medium computation time and the equivalent of 21 32- bits integers memory little consumption. See Melg19937 for alarger period MELG-Generator (2^19,937, i.e. 4.32e+6001), same computation time and equivalent of 625 integers memory consumption. See Melg44497 for a very large period (2^44,497, i.e. 8.55e+13,395) with similar computation time but use of even more memory space (equivalent of 1,393 32-bits integers). This is the longest period version proposed in paper [11].
See Mrg287 for a short period Multiple Recursive Generator (2^287, i.e. 2.49e+86) with low computation time but 256 32-bits integers memory consumption. See Mrg1457 for a longer period MR-Generator (2^1457, i.e. 4.0e+438) and longer computation time (2^31-1 modulus calculations) but less memory space consumption (32-bits 47 integers). See Mrg49507 for a far larger period MR-Generator (2^49507, i.e. 1.2e+14903) with low computation time too (31-bits modulus) but use of more memory space (1597 32-bits integers).
See Pcg64_32, Pcg128_64 and Pcg1024_32 for Permuted Congruential Generators with medium to very large periods, very low computation time, and for very low memory consumption for the two first (resp. 4, 8 and 1,026 times 32-bits). Associated periods are resp. 2^64, 2^128 and 2^32830, i.e. 1.84e+19, 3.40e+38 and 6.53e+9882. These PRNGs provide multi-streams and jump ahead features. Since they all are exposing only a part of their internal state, they are difficult to reverse and to predict.
See Squares32 for a counter-based middle-square random number generator with 2^64 (i.e. about 1.84e+19) period, low computation time, 32-bits output values and very good randomness characteristics. See Squares64 for a 2^64 (i.e. about 1.84e+19) period PRNG with low computation time, medium period, 64-bits output values and very good randomness characteristics. Caution: this 64-bits version should not pass the birthday test, which is a randomness issue, while this is not mentionned in the original paper.
See Well512a, Well1024a, Well19937c and Well44479b for large to very large period generators (resp. 2^512, 2^1024, 2^19937 and 2^44479 periods, i.e. resp. 1.34e+154, 2.68e+308, 4.32e+6001 and 1.51e+13466 periods), a little bit longer computation times but very quick escaping from zeroland. Memory consumption is resp. 32, 64, 624 and 1391 32-bits integers.
See Xoroshiro256, Xoroshiro512, Xoroshiro1024 for long period generators (resp. 2^256, 2^512 and 2^1024 periods, i.e. resp. 1.16e+77, 1.34e+154 and 1.80e+308 periods), 64-bits precision calculations and short memory consumption (resp. 4, 8 and 16 integers each coded on 64 bits.
Furthermore this class and all its inheriting sub-classes are callable. Example:
BaseRandom rand{}; // CAUTION: Replace 'BaseRandom' with any inheriting class constructor!
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Please notice that for simulating the roll of a dice you may use any of:
FastRand32 diceRoll{};                            // notice: use of FastRand32 is for sole example purpose
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Conforming to the former Python version of this library (i.e. PyRandLib), next methods are available - built-in function in Python module 'random': | | betavariate(alpha, beta) | Beta distribution. | https://en.wikipedia.org/wiki/Beta_distribution | | Conditions on the parameters are alpha > 0 and beta > 0. | Returned values range between 0 and 1. | | | binomialvariate(n=1, p=0.5) | Binomial distribution. Return the number of successes for n | independent trials with the probability of success in each | trial being p. | n >= 0, 0.0 <= p <= 1.0, | the result is an integer in the range 0 <= X <= n. | | | choice(seq) | Choose a random element from a non-empty sequence. | | | choices(population, weights=None, , cum_weights=None, k=1) | Important notice: CppRandLib implements this function via | different signatures. | | Python documentation: | Return a k sized list of elements chosen from the population | with replacement. If the population is empty, raises an | error. | | If a weights sequence is specified, selections are made | according to the relative weights. Alternatively, if a | cum_weights sequence is given, the selections are made | according to the cumulative weights (perhaps computed using | itertools.accumulate()). For example, the relative weights | [10, 5, 30, 5] are equivalent to the cumulative weights | [10, 15, 45, 50]. Internally, the relative weights are | converted to cumulative weights before making selections, | so supplying the cumulative weights saves work. | | If neither weights nor cum_weights are specified, selections | are made with equal probability. If a weights sequence is | supplied, it must be the same length as the population | sequence. It is a TypeError to specify both weights and | cum_weights. | | The weights or cum_weights can use any numeric type that | interoperates with the float values returned by random() | (that includes integers, floats, and fractions but excludes | decimals). Weights are assumed to be non-negative and finite. | A ValueError is raised if all weights are zero. | | For a given seed, the choices() function with equal | weighting typically produces a different sequence than | repeated calls to choice(). The algorithm used by choices() | uses floating-point arithmetic for internal consistency and | speed. The algorithm used by choice() defaults to integer | arithmetic with repeated selections to avoid small biases | from round-off error. | | | expovariate(lambda = 1.0) | Exponential distribution. | https://en.wikipedia.org/wiki/Exponential_distribution | | lambda is 1.0 divided by the desired mean. It should be | nonzero. | Returned values range from 0 to positive infinity if lambda | is positive, and from negative infinity to 0 if lambda is | negative. | | | gammavariate(alpha, beta) | Gamma distribution. Not the gamma function! | https://en.wikipedia.org/wiki/Gamma_distribution | | Conditions on the parameters are alpha > 0 and beta > 0. | | | gauss(mu, sigma) | Gaussian distribution. | https://en.wikipedia.org/wiki/Normal_distribution | | mu is the mean, and sigma is the standard deviation. This is | slightly faster than the normalvariate() function. | | Not thread-safe without a lock around calls. | | | getstate() | Return internal state; can be passed to setstate() later. | | | getrandbits(k) | Returns a non-negative integer with k random bits. | | | lognormvariate(mu, sigma) | Log normal distribution. | https://en.wikipedia.org/wiki/Log-normal_distribution | | If you take the natural logarithm of this distribution, you'll get a | normal distribution with mean mu and standard deviation sigma. | mu can have any value, and sigma must be greater than zero. | | | n_evaluate() | This method is not available in PyRandLib and is not part of | Python API. It is specific to the c++ version CppRandLib in | which many different signature are available. | | See code documentation below and document README.md, section | "Distribution Functions and Generic Functions", for full details | of the different available signatures of this method. | | | normalvariate(mu, sigma) | Normal distribution. | https://en.wikipedia.org/wiki/Normal_distribution | | mu is the mean, and sigma is the standard deviation. | | | paretovariate(alpha) | Pareto distribution. alpha is the shape parameter. | https://en.wikipedia.org/wiki/Pareto_distribution | | | randbytes(n) | Generate n random bytes. | This method should not be used for generating security tokens. | | | randint(a, b) | Return random integer in range [a, b], including both end points. | | | randrange(start, stop, step=1) | Choose a random item from range(start, stop[, step]). | | This fixes the problem with randint() which includes the | endpoint. | | | sample(population, k) | Chooses k unique random elements from a population sequence or set. | | Returns a new list containing elements from the population while | leaving the original population unchanged. The resulting list is | in selection order so that all sub-slices will also be valid random | samples. This allows raffle winners (the sample) to be partitioned | into grand prize and second place winners (the subslices). | | Members of the population need not be hashable or unique. If the | population contains repeats, then each occurrence is a possible | selection in the sample. | | To choose a sample in a range of integers, use range as an argument. | This is especially fast and space efficient for sampling from a | large population: sample(range(10000000), 60) | | | seed() | seed(a) | Initialize internal state. | No argument seeds from current time. | If *a is an int, all bits are used. | | | setstate(state) | Restore internal state from object returned by getstate(). | | | shuffle(x) | x-> shuffle vector x in place. | | | triangular() | triangular(low, high) | triangular(low, high, mode) | Triangular distribution. | http://en.wikipedia.org/wiki/Triangular_distribution | | Continuous distribution bounded by given lower and upper limits, | and having a given mode value in-between. | When missing, low = 0.0, high = 1.0, mode = (low + high) / 2 | | | uniform() | uniform(b) | uniform(a, b) | Get a random number in the range [a, b) or [a, b] depending on rounding. | When missing, a = 0.0 and b = 1.0 | | | vonmisesvariate(mu, kappa) | Circular data distribution. | https://en.wikipedia.org/wiki/Von_Mises_distribution | | mu is the mean angle, expressed in radians between 0 and 2*pi, and | kappa is the concentration parameter, which must be greater than or | equal to zero. If kappa is equal to zero, this distribution reduces | to a uniform random angle over the range 0 to 2*pi. | | | weibullvariate(alpha, beta) | Weibull distribution. | https://en.wikipedia.org/wiki/Weibull_distribution | | alpha is the scale parameter and beta is the shape parameter.
Constructor & Destructor Documentation
BaseRandom() [1/3]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> BaseRandom< StateT, OutputT, OUTPUT_BITS >::BaseRandom () default noexcept
default empty constructor.
BaseRandom() [2/3]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> BaseRandom< StateT, OutputT, OUTPUT_BITS >::BaseRandom (const BaseRandom< StateT, OutputT, OUTPUT_BITS > &) default noexcept
default copy constructor.
BaseRandom() [3/3]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> BaseRandom< StateT, OutputT, OUTPUT_BITS >::BaseRandom (BaseRandom< StateT, OutputT, OUTPUT_BITS > &&) default noexcept
default move constructor.
~BaseRandom()
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> virtual BaseRandom< StateT, OutputT, OUTPUT_BITS >::~BaseRandom () virtual default noexcept
default destructor.
Member Function Documentation
_setstate() [1/2]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::_setstate (const std::uint64_t seed) inline protected virtual noexcept
Sets the internal state with an integer seed.
MUST BE overridden in inheriting classes.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, FastRand32, FastRand63, Pcg1024_32, Pcg128_64, and Pcg64_32.
Referenced by seed(), seed(), and seed().
_setstate() [2/2]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::_setstate (const utils::UInt128 & seed_) inline protected virtual noexcept
Sets the internal state with a 128-bits integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, FastRand32, FastRand63, Pcg1024_32, Pcg128_64, and Pcg64_32.
betavariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::betavariate (const double alpha, const double beta)
Beta distribution.
Parameters
alpha double, must be greater than 0
beta double, must be greater than 0
Returns
a value in interval [0.0, 1.0].
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++. The original code is due to Janne Sinkkonen and matches all the std texts (e.g., Knuth Vol 2 Ed 3 pg 134 "the beta distribution").
Beta distribution.
References gammavariate().
binomialvariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename CountT, typename ProbaT> const CountT BaseRandom< StateT, OutputT, OUTPUT_BITS >::binomialvariate (CountT n = 1, const ProbaT p = ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
Returns the number of successes for n>=0 independent trials.
References uniform().
choice() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n> const T & BaseRandom< StateT, OutputT, OUTPUT_BITS >::choice (const std::array< T, n > & seq)
Chooses a random element from a non-empty sequence (std::array).
Chooses a random element from a non-empty sequence (std::array).
References uniform().
choice() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> const T & BaseRandom< StateT, OutputT, OUTPUT_BITS >::choice (const std::vector< T > & seq)
Chooses a random element from a non-empty sequence (std::vector).
Chooses a random element from a non-empty sequence (std::vector).
References uniform().
choices() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices (const std::vector< T > & population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
Returns a k sized vector of elements chosen from the population with replacement (same weights).
References choices_cum().
choices() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename C> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices (const std::vector< T > & population, std::vector< C > & weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
References choices_cum().
choices_cum()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename C> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices_cum (const std::vector< T > & population, const std::vector< C > & cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
Referenced by choices(), and choices().
expovariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::expovariate (const double lambda = 1.0)
Exponential distribution.
Parameters
lambda double, this should get the value (1.0 / desired_mean). It cannot be 0.0.
Returns
a value in range [0.0, Infinity) if lambda is positive, or a value in range (-Infinity, 0.0] if lambda is negative.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Exponential distribution.
References uniform().
gammavariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
The probability distribution function is : x^(alpha - 1) * std::exp(-x / beta) pdf(x) = --------------------------------— std::tgamma(alpha) * beta^alpha where: pdf is the probability density function a^b is std::pow(a, b) std::tgamma() is the Gamma funtion as implemented in the c++ math library.
The Gamma function is the below integral summation from 0 to Infinity: (x) = 0 t^(x1) * std::exp(t) dt
Parameters
alpha : double, the shape parameter - must be greater than 0.0.
beta : double, the scale parameter - must be greater than 0.0. With these two arguments: mean is alpha * beta and variance is alpha * beta * beta
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++. As such, some comments present in the Python original code have been copied as is in this c++ implementation, naming then the authors of the related parts of code.
Gamma distribution. This is NOT the gamma function!
References uniform().
Referenced by betavariate().
gauss() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gauss () inline noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
This is slightly faster than the normalvariate() function. Notice: not thread-safe without a lock around calls.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Default Gaussian distribution (mean=0.0, stdev=1.0).
References gauss().
Referenced by gauss().
gauss() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
mu is the mean, and sigma is the standard deviation. mu can be any value, sigma must be greater than 0.0. This is slightly faster than the normalvariate() function.
Notice: not thread-safe without a mutex around calls.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Gaussian distribution (mean=mu, stdev=sigma).
References uniform().
getrandbits()
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> OutputT BaseRandom< StateT, OutputT, OUTPUT_BITS >::getrandbits (const unsigned int k) inline
Returns a non-negative integer with k random bits.
getstate()
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> struct _InternalState BaseRandom< StateT, OutputT, OUTPUT_BITS >::getstate () const inline noexcept
Returns the internal state of this PRNG; can be passed to setstate() later.
lognormvariate() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::lognormvariate () inline
Default Log normal distribution (mean=0.0, stdev=1.0).
If you take the natural logarithm of this distribution, you'll get a normal distribution with mean 0.0 and standard deviation 1.0.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Default Log normal distribution (mean=0.0, stdev=1.0).
References lognormvariate().
Referenced by lognormvariate().
lognormvariate() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::lognormvariate (const double mu, const double sigma) inline
Log normal distribution (mean=mu, stdev=sigma).
If you take the natural logarithm of this distribution, you'll get a normal distribution with mean mu and standard deviation sigma. mu can have any value, and sigma must be greater than zero.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Log normal distribution (mean=mu, stdev=sigma).
References normalvariate().
n_evaluate() [1/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate () inline
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
References uniform().
n_evaluate() [2/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t m, typename U, const std::size_t n> std::array< T, m > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::array< U, n > & max)
Returns an array of min(m, n) values in range [0; max[i]).
Returns an array of min(m, n) values in range [0; max[i]).
References uniform().
n_evaluate() [3/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t m, typename U, const std::size_t n, typename V, const std::size_t p> std::array< T, m > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::array< U, n > & min, const std::array< V, p > & max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
Returns an array min(m, n, p) values in range [min[i]; max[i]).
References uniform().
n_evaluate() [4/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::size_t n) inline
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
n_evaluate() [5/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
Returns a vector of n values that are uniformly contained within range [0, max).
References uniform().
n_evaluate() [6/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::vector< U > & max)
Returns a vector of n values in range [0; max[i]).
Returns a vector of n values in range [0; max[i]).
References uniform().
n_evaluate() [7/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U, typename V> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::vector< U > & min, const std::vector< V > & max)
Returns a vector of n values in range [min[i]; max[i]).
Returns a vector of n values in range [min[i]; max[i]).
References uniform().
n_evaluate() [8/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n, typename U> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
Returns an array of n values that are uniformly contained within range [0, max).
References uniform().
n_evaluate() [9/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n, typename U, typename V> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
Returns an array of n values that are uniformly contained within range [min, max).
References uniform().
next()
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> virtual const output_type BaseRandom< StateT, OutputT, OUTPUT_BITS >::next () inline virtual noexcept
The internal PRNG algorithm.
This method MUST be implemented in inheriting classes.
Returns
an integer value coded on OUTPUT_BITS bits, related to the uniform distribution.
Reimplemented in BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Mrg1457, Mrg287, Mrg49507, Pcg1024_32, Pcg128_64, Pcg64_32, Squares32, Squares64, Well1024a, Well19937c, Well44497b, Well512a, Xoroshiro1024, Xoroshiro256, and Xoroshiro512.
normalvariate() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::normalvariate () inline
Normal distribution (mean=0.0, stdev=1.0).
The Python version of this method uses Kindermanand Monahan method. Reference: Kinderman, A.J.and Monahan, J.F., "Computer generation of random variables using the ratio of uniform deviates", ACM Trans Math Software, 3, (1977), pp257 - 260. This method is slightlly slower than the gauss method. Furthermore, we've s lightly modified the original algorithm here to fulfill very special cases that might happen in very specific conditions. This slows down also the running of normalvariate() in these very specific conditions. You should prefer then to use method gauss() instead of this one.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Normal distribution (mean=0.0, stdev=1.0).
References normalvariate().
Referenced by lognormvariate(), and normalvariate().
normalvariate() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::normalvariate (const double mu, const double sigma) inline
Normal distribution (mean=mu, stdev=sigma).
mu is the mean, and sigma is the standard deviation. mu can be any value, sigma must be greater than 0.0.
The Python version of this method uses Kindermanand Monahan method. Reference: Kinderman, A.J.and Monahan, J.F., "Computer generation of random variables using the ratio of uniform deviates", ACM Trans Math Software, 3, (1977), pp257 - 260. This method is slightlly slower than the gauss method. Furthermore, we've s lightly modified the original algorithm here to fulfill very special cases that might happen in very specific conditions. This slows down also the running of normalvariate() in these very specific conditions. You should prefer then to use method gauss() instead of this one.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Normal distribution (mean=mu, stdev=sigma).
References uniform().
operator()() [1/8]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> template<typename T = long double> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() () inline noexcept
Empty Call operator.
Returns
a value that is uniformly contained within range [0.0, 1.0).
operator()() [2/8]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::array< T, n > & max)
Valued call operator (1 std::array of scalars).
Returns
an array of values that are uniformly contained within the interval [0; max[i]) – i being the index of the value in the returned array.
Valued call operator (1 std::array of scalars).
References uniform().
operator()() [3/8]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::array< T, n > & min, const std::array< T, n > & max)
Valued call operator (2 std::array of scalars).
Returns
an array of values that are uniformly contained within the interval [min[i]; max[i]) - i being the index of the value in the returned array.
Valued call operator (2 std::array of scalars).
References uniform().
operator()() [4/8]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::vector< T > & max)
Valued call operator (1 std::vector of scalars).
Returns
a vector of values that are uniformly contained within the interval [0; max[i]) – i being the index of the value in the returned vector.
Valued call operator (1 std::vector of scalars).
References uniform().
operator()() [5/8]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::vector< T > & min, const std::vector< T > & max)
Valued call operator (2 std::vector of scalars).
Returns
a vector of values that are uniformly contained within the interval [min[i]; max[i]) - i being the index of the value in the returned vector.
Valued call operator (2 std::vector of scalars).
References uniform().
operator()() [6/8]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T max)
Valued call operator (1 scalar).
Returns
a value that is uniformly contained within range [0; max).
Valued call operator (1 scalar).
References uniform().
operator()() [7/8]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
Returns
a vector of n values that are uniformly contained within range [0; max).
Valued call operator (max and n scalars).
References uniform().
operator()() [8/8]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
Returns
a vector of n values that are uniformly contained within range [min; max).
Valued call operator (min, max and n scalars).
References uniform().
operator=() [1/3]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> BaseRandom & BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator= (BaseRandom< StateT, OutputT, OUTPUT_BITS > &&) default noexcept
default move assignment.
operator=() [2/3]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> BaseRandom & BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator= (const BaseRandom< StateT, OutputT, OUTPUT_BITS > &) default noexcept
default copy assignment.
operator=() [3/3]
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> BaseRandom & BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator= (const StateT & new_internal_state) inline noexcept
< valued assignment.
paretovariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::paretovariate (const double alpha)
Pareto distribution.
Parameters
alpha double, the shape parameter. Cannot be 0.0.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Pareto distribution.
References uniform().
randbytes()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> std::vector< std::uint8_t > BaseRandom< StateT, OutputT, OUTPUT_BITS >::randbytes (const std::size_t n) inline
Generates n random bytes.
This method should not be used for generating security tokens.
Generates n random bytes.
References uniform().
randint()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::randint (const T a, const T b) inline
Returns random integer in range [a, b], including both end points.
Template argument T must be an integral type.
Returns a random integer in range [a, b], including both end points.
References uniform().
random()
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> template<typename T = double> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::random () inline
The uniform distribution on [0.0, 1.0).
Returns
a double value uniformly contained within range [0.0, 1.0).
Referenced by uniform(), uniform(), and uniform().
randrange()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename S> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::randrange (const T start, const T stop, const S step = S(1))
Returns a random value in range [start, stop) with specified step.
Template arguments T and S must be arithmetic types.
Returns a random value in range [start, stop) with specified step.
References uniform().
sample() [1/4]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t k, const std::size_t n> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::array< T, k > & out, const std::array< T, n > & population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
Evaluates a vector containing elements from the population while leaving the original population unchanged. The resulting list is in selection order so that all sub-slices will also be valid random samples. This allows raffle winners (the sample) to be partitioned into grand prize and second place winners (the subslices).
Members of the population need not be unique. If the population contains repeats, then each occurrence is a possible selection in the sample. Notice: k must be greater than n.
Chooses k unique random elements from a population sequence (out std::array<>, in std::array<>, default count per element = 1).
References uniform().
sample() [2/4]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename C, const std::size_t k, const std::size_t n> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::array< T, k > & out, const std::array< T, n > & population, const std::array< C, n > & counts) inline
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
Evaluates an array containing k elements from the population while leaving the original population unchanged. The resulting list is in selection order so that all sub-slices will also be valid random samples. This allows raffle winners (the sample) to be partitioned into grand prize and second place winners (the subslices).
Members of the population need not be unique. If the population contains repeats, then each occurrence is a possible selection in the sample.
Repeated elements are specified by the counts parameter. For example: std::array<char*, 5> out; sample(out, std::array<char*, 2>{"red", "blue"}, std::array<int,2>{4, 2}); is equivalent to: sample(out, std::array<char*, 6>{"red", "red", "red", "red", "blue", "blue"});
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
References uniform().
sample() [3/4]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::vector< T > & out, const std::vector< T > & population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
Evaluates a vector containing elements from the population while leaving the original population unchanged. The resulting list is in selection order so that all sub-slices will also be valid random samples. This allows raffle winners (the sample) to be partitioned into grand prize and second place winners (the subslices).
Members of the population need not be unique. If the population contains repeats, then each occurrence is a possible selection in the sample.
Chooses k unique random elements from a population sequence (out std::vector, in container, default count per element = 1).
References uniform().
sample() [4/4]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename C> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::vector< T > & out, const std::vector< T > & population, const std::vector< C > & counts, const std::size_t k) inline
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
Evaluates a vector containing elements from the population while leaving the original population unchanged. The resulting list is in selection order so that all sub-slices will also be valid random samples. This allows raffle winners (the sample) to be partitioned into grand prize and second place winners (the subslices).
Members of the population need not be unique. If the population contains repeats, then each occurrence is a possible selection in the selection in the sample.
Repeated elements are specified by the counts parameter. For example: sample({"red", "blue"}, {4, 2}, 5); is equivalent to: sample({"red", "red", "red", "red", "blue", "blue"}, 5);
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
References uniform().
seed() [1/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Uses an integer value evaluated from shuffled and xored current time as seed.
Initializes internal state (empty signature).
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed(), and utils::set_random_seed64().
Referenced by seed(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const double seed_) inline virtual
Initalizes internal state from a double seed.
Initalizes internal state from a double seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [3/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const int seed_) inline virtual noexcept
Initializes internal state from a 32-bits signed integer seed.
Initializes internal state from a 32-bits signed integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [4/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const long long seed_) inline virtual noexcept
Initializes internal state from a 64-bits signed integer seed.
Initializes internal state from a 64-bits signed integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [5/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const long seed_) inline virtual noexcept
Initializes internal state from a 32-bits signed integer seed.
Initializes internal state from a 32-bits signed integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [6/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state from a 32-bits unsigned integer seed.
Initializes internal state from a 32-bits unsigned integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [7/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state from a 64-bits unsigned integer seed.
Initializes internal state from a 64-bits unsigned integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References _setstate().
seed() [8/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state from a 32-bits unsigned integer seed.
Initializes internal state from a 32-bits unsigned integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References _setstate().
seed() [9/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes the internal state of this PRNG with a 128-bits integer seed.
Initializes the internal state of this PRNG with a 128-bits integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References _setstate().
setstate() [1/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const StateT & new_internal_state) inline noexcept
Sets the internal state from a new internal state content.
Sets the internal state from a new internal state content.
setstate() [2/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const StateT & new_internal_state, const double gauss_next) inline noexcept
Sets the internal state from a new internal state content and with gauss_next.
Sets the internal state from a new internal state content and with gauss_next.
setstate() [3/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const struct _InternalState & new_internal_state) inline noexcept
Restores internal state from object returned by getstate().
Restores internal state from object returned by getstate().
Referenced by Squares32::Squares32(), and Squares64::Squares64().
shuffle()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename ContainerType> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::shuffle (ContainerType & seq)
Shuffles specified sequence in place.
The Container type must be either std::vector or std::array.
Shuffles specified sequence in place.
References uniform().
state()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const StateT BaseRandom< StateT, OutputT, OUTPUT_BITS >::state () const inline noexcept
Returns the current internal state value.
Returns the current internal state value.
triangular() [1/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular () inline noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
Triangular distribution (low=0.0, high=1.0, mode=0.5).
References triangular().
Referenced by triangular(), and triangular().
triangular() [2/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
Triangular distribution (low, high, default mode).
References triangular().
triangular() [3/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Triangular distribution (low, high, mode).
References uniform().
uniform() [1/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform () inline
Uniform distribution in [0.0, 1.0).
Uniform distribution in [0.0, 1.0).
References random().
Referenced by binomialvariate(), choice(), choice(), expovariate(), gammavariate(), gauss(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), normalvariate(), operator()(), operator()(), operator()(), operator()(), operator()(), operator()(), operator()(), paretovariate(), randbytes(), randint(), randrange(), sample(), sample(), sample(), sample(), shuffle(), triangular(), vonmisesvariate(), and weibullvariate().
uniform() [2/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform (const U max) inline
Uniform distribution in [0.0, max).
Uniform distribution in [0.0, max).
References random().
uniform() [3/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U, typename V> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform (const U min, const V max) inline
Uniform distribution in [min, max).
Uniform distribution in [min, max).
References random().
vonmisesvariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
Parameters
mu is the mean angle, expressed in radians between 0 and 2*pi
kappa is the concentration parameter, which must be greater than or equal to zero. If kappa is equal to zero, this distribution reduces to a uniform random angle over the range 0 to 2*pi.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++. As such, some comments present in the Python original code have been copied as is in this c++ implementation, naming then the authors of the related parts of code.
Circular data distribution.
References uniform().
weibullvariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::weibullvariate (const double alpha, const double beta)
Weibull distribution.
Parameters
alpha double, the scale parameter.
beta double, the shape parameter. Must be non null.
Weibull distribution.
References uniform().
Member Data Documentation
_NORMALIZE_LD
template<typename StateT, typename OutputT = std::uint32_t, const std::uint8_t OUTPUT_BITS = 8 * sizeof(OutputT)> long double BaseRandom< StateT, OutputT, OUTPUT_BITS >::_NORMALIZE_LD static constexpr protected
Initial value:
{ (OUTPUT_BITS <= 64)
        ? 1.0l / ((long double)_MODULO + 1.0l)
        : 2.938'735'877'055'718'769'921'841'343'055'6e-39l
    }
The documentation for this class was generated from the following file:
baserandom.h