CppRandLib - c++11: Pcg64_32 Class Reference
Pcg64_32 Class Reference
Permutated Congruential Generator dedicated to 64-bits calculations and 32-bits output with medium period (about 1.84e+19).
#include <pcg64_32.h>
Public Types
using MyBaseClass = BasePCG<std::uint64_t, std::uint32_t>
using value_type = std::uint64_t
Public Member Functions
virtual void _setstate (const std::uint64_t seed_) noexcept override
Sets the internal state with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed_) noexcept override
Sets the internal state with a 128-bits integer seed.
virtual const output_type next () noexcept override
The internal PRNG algorithm.
Pcg64_32 () noexcept
Default empty constructor.
Pcg64_32 (const double seed)
Valued constructor (double).
Pcg64_32 (const int seed) noexcept
Valued constructor (int).
Pcg64_32 (const long long seed) noexcept
Valued constructor (long long).
Pcg64_32 (const long seed) noexcept
Valued constructor (long)
Pcg64_32 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Pcg64_32 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Pcg64_32 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Pcg64_32 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual void seed () noexcept override
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
Permutated Congruential Generator dedicated to 64-bits calculations and 32-bits output with medium period (about 1.84e+19).
This Pcg64_32 class implements the "PCG XSH RS 64/32 (LCG)" version of the PCG algorithm, as specified in the related paper (see reference [7] in document README.md). Output values are returned on 32 bits.
PCGs are very fast generators, with low memory usage except for a very few of them and medium to very large periods. They offer jump ahead and multi streams features for most of them. They are difficult to very difficult to invert and to predict.
See Pcg128_64 for a 2^128 (i.e. about 3.40e+38) period PC-Generator with low computation time also and a longer period than for Pcg64_32, with 4 32-bits word integers memory consumption. Output values are returned on 64 bits.
See Pcg1024_32 for a 2^32,830 (i.e. about 6.53e+9,882) period PC-Generator with low computation time also and a very large period, but 1,026 32-bits word integers memory consumption. Output values are returned on 32 bits.
Furthermore this class is callable:
Pcg64_32 rand{};
std::cout << rand() << std::endl;     // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;    // prints a uniform pseudo-random value within [0.0, b)
Please notice that for simulating the roll of a dice you may use any of:
Pcg64_32 diceRoll{};
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the PCG algorithms that have been implemented in CppRandLib, as provided in paper "TestU01, ..." and when available.
+------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class initial PCG algo name ([7]) Memory Usage Period time-64 bits SmallCrush fails Crush fails BigCrush fails
Pcg64_32 PCG XSH RS 64/32 (LCG) 2 x 4-bytes 2^64 0.79 0 0 0
Pcg128_64 PCG XSL RR 128/64 (LCG) 4 x 4-bytes 2^128 1.70 0 0 0
Pcg1024_32 PCG XSH RS 64/32 (EXT 1024) 1026 x 4-bytes 2^32,830 0.78 0 0 0
+------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Pcg64_32() [1/9]
Pcg64_32::Pcg64_32 () noexcept
Default empty constructor.
Empty constructor.
References seed().
Pcg64_32() [2/9]
Pcg64_32::Pcg64_32 (const int seed_) noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
Pcg64_32() [3/9]
Pcg64_32::Pcg64_32 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
Pcg64_32() [4/9]
Pcg64_32::Pcg64_32 (const long seed_) noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
Pcg64_32() [5/9]
Pcg64_32::Pcg64_32 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
Pcg64_32() [6/9]
Pcg64_32::Pcg64_32 (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
Pcg64_32() [7/9]
Pcg64_32::Pcg64_32 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
Pcg64_32() [8/9]
Pcg64_32::Pcg64_32 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References seed().
Pcg64_32() [9/9]
Pcg64_32::Pcg64_32 (const double seed_)
Valued constructor (double).
Valued constructor (double).
References seed().
Member Function Documentation
_setstate() [1/2]
void Pcg64_32::_setstate (const std::uint64_t seed_) override virtual noexcept
Sets the internal state with a 64-bits integer seed.
Sets the internal state with a 64-bits integer seed.
Referenced by _setstate().
_setstate() [2/2]
void Pcg64_32::_setstate (const utils::UInt128 & seed_) override virtual noexcept
Sets the internal state with a 128-bits integer seed.
Sets the internal state with a 128-bits integer seed.
References _setstate().
next()
const Pcg64_32::output_type Pcg64_32::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
seed() [1/9]
void Pcg64_32::seed () inline override virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Referenced by Pcg64_32(), Pcg64_32(), Pcg64_32(), Pcg64_32(), Pcg64_32(), Pcg64_32(), Pcg64_32(), Pcg64_32(), Pcg64_32(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
void Pcg64_32::seed (const double seed_)
Initializes internal state (double).
Initializes internal state (double).
seed() [3/9]
void Pcg64_32::seed (const int seed_) noexcept
Initializes internal state (int).
Initializes internal state (int).
References seed().
seed() [4/9]
void Pcg64_32::seed (const long long seed_) noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References seed().
seed() [5/9]
void Pcg64_32::seed (const long seed_) noexcept
Initializes internal state (long)
Initializes internal state (long).
References seed().
seed() [6/9]
void Pcg64_32::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References seed().
seed() [7/9]
void Pcg64_32::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
seed() [8/9]
void Pcg64_32::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References seed().
seed() [9/9]
void Pcg64_32::seed (const utils::UInt128 & seed_) noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
The documentation for this class was generated from the following files:
pcg64_32.h
pcg64_32.cpp