CppRandLib - c++11: BaseSquares< OutputT > Class Template Reference
BaseSquares< OutputT > Class Template Reference
The base class for all Squares counter-based pseudorandom Generators.
#include <basesquares.h>
Public Types
using MyBaseClass = BaseRandom<CounterKeyState, OutputT, 8 * sizeof(OutputT)>
using output_type = OutputT
using state_type = MyBaseClass::state_type
using value_type = typename state_type::value_type
Public Types inherited from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>
using output_type
using state_type
Public Member Functions
virtual void _setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseSquares () noexcept
Default empty constructor.
BaseSquares (const double seed)
Valued constructor (double).
BaseSquares (const int seed) noexcept
Valued constructor (int).
BaseSquares (const long long seed) noexcept
Valued constructor (long long).
BaseSquares (const long seed) noexcept
Valued constructor (long)
BaseSquares (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseSquares (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseSquares (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseSquares (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseSquares (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~BaseSquares () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>
BaseRandom () noexcept=default
default empty constructor.
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
OutputT getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be passed to setstate() later.
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate ()
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of n values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
virtual const output_type next () noexcept
The internal PRNG algorithm.
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max)
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max)
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max)
Valued call operator (2 std::vector of scalars).
const T operator() (const T max)
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const CounterKeyState &new_internal_state) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b)
Returns random integer in range [a, b], including both end points.
const T random ()
The uniform distribution on [0.0, 1.0).
const long double random ()
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void setstate (const CounterKeyState &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const CounterKeyState &new_internal_state, const double gauss_next) noexcept
Sets the internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
Shuffles specified sequence in place.
const state_type state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform ()
Uniform distribution in [0.0, 1.0).
const double uniform (const double max)
const float uniform (const float max)
const long double uniform (const long double max)
const T uniform (const U max)
Uniform distribution in [0.0, max).
const T uniform (const U min, const V max)
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static const double BPF
static const double E
static const double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static const double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static const double TWO_PI
Detailed Description
template<typename OutputT>
class BaseSquares< OutputT >
The base class for all Squares counter-based pseudorandom Generators.
Squares models are based on an incremented counter and a key. The algorithm squares a combination of the counter and the key values, and exchanges the upper and lower bits of the combination, the whole repeated a number of times (4 to 5 rounds). Output values are provided on 32-bits or on 64-bits according to the model. See [9] in README.md.
See Squares32 for a 2^64 (i.e. about 1.84e+19) period PRNG with low computation time, medium period, 32-bits output values and very good randomness characteristics.
See Squares64 for a 2^64 (i.e. about 1.84e+19) period PRNG with low computation time, medium period, 64-bits output values and very good randomness characteristics. Caution: the 64-bits version should not pass the birthday test, which is a randomness issue, while this is not mentionned in the original paper - see reference [9] in file README.md.
Furthermore this class is callable:
BaseSquares rand{};                   // CAUTION: Replace 'BaseSquares' with any inheriting class constructor!
std::cout << rand() << std::endl;     // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;    // prints a uniform pseudo-random value within [0.0, b)
Please notice that for simulating the roll of a dice you may use any of:
BaseSquares diceRoll{};               // CAUTION: Replace 'BaseSquares' with any inheriting class constructor!
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the WELL algorithms that have been implemented in CppRandLib, as provided in paper "TestU01, ..." and when available.
+-----------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class [9] generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Squares32 squares32 4 x 4-bytes 2^64 n.a. n.a. 0 0 0
Squares64 squares64 4 x 4-bytes 2^64 n.a. n.a. 0 0 0
+-----------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
BaseSquares() [1/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares () inline noexcept
Default empty constructor.
Empty constructor.
References BaseSquares(), and BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
Referenced by BaseSquares().
BaseSquares() [2/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [3/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [4/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [5/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [6/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [7/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [8/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [9/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const double seed_) inline
Valued constructor (double).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [10/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::setstate().
~BaseSquares()
template<typename OutputT> virtual BaseSquares< OutputT >::~BaseSquares () inline virtual default noexcept
default destructor.
Member Function Documentation
_setstate() [1/2]
template<typename OutputT> void BaseSquares< OutputT >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
Referenced by seed().
_setstate() [2/2]
template<typename OutputT> void BaseSquares< OutputT >::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
seed() [1/9]
template<typename OutputT> void BaseSquares< OutputT >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References _setstate(), and utils::set_random_seed64().
seed() [2/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const double seed_) inline virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [3/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const int seed_) inline virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [4/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const long long seed_) inline virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [5/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const long seed_) inline virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [6/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [7/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [8/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [9/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
The documentation for this class was generated from the following file:
basesquares.h