CppRandLib - c++11: BaseMELG< SIZE > Class Template Reference
BaseMELG< SIZE > Class Template Reference
The base class for all Maximally Equidistributed Long-period Linear Generators (MELG).
#include <basemelg.h>
Public Types
using MyBaseClass = BaseRandom<ListSeedState<utils::SplitMix64, std::uint64_t, SIZE>, std::uint64_t>
using output_type = typename MyBaseClass::output_type
using state_type = typename MyBaseClass::state_type
using value_type = typename state_type::value_type
Public Types inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >
using output_type
using state_type
Public Member Functions
virtual void _setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseMELG () noexcept
Default empty constructor.
BaseMELG (const double seed)
Valued constructor (double).
BaseMELG (const int seed) noexcept
Valued constructor (int).
BaseMELG (const long long seed) noexcept
Valued constructor (long long).
BaseMELG (const long seed) noexcept
Valued constructor (long)
BaseMELG (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseMELG (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseMELG (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseMELG (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseMELG (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~BaseMELG () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >
BaseRandom () noexcept=default
default empty constructor.
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
std::uint64_t getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be passed to setstate() later.
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate ()
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of n values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
virtual const output_type next () noexcept
The internal PRNG algorithm.
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max)
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max)
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max)
Valued call operator (2 std::vector of scalars).
const T operator() (const T max)
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b)
Returns random integer in range [a, b], including both end points.
const T random ()
The uniform distribution on [0.0, 1.0).
const long double random ()
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void setstate (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state, const double gauss_next) noexcept
Sets the internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
Shuffles specified sequence in place.
const state_type state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform ()
Uniform distribution in [0.0, 1.0).
const double uniform (const double max)
const float uniform (const float max)
const long double uniform (const long double max)
const T uniform (const U max)
Uniform distribution in [0.0, max).
const T uniform (const U min, const V max)
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static const double BPF
static const double E
static const double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static const double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static const double TWO_PI
Detailed Description
template<const std::uint32_t SIZE>
class BaseMELG< SIZE >
The base class for all Maximally Equidistributed Long-period Linear Generators (MELG).
Maximally Equidistributed Long-period Linear Generators (MELG) use linear recurrence based on state transitions with double feedbacks and linear output transformations with several memory references. See reference [11] in README.md.
MELGs offer large to very large periods with best known results in the evaluation of their randomness. They ensure a maximally equidistributed generation of pseudo random numbers. They pass all TestU01 tests and newer ones but are the slowest to compute ones in the base of PRNGs that have been implemented in CppRandLib.
Notice: while the WELL algorithms use 32-bits integers as their internal state and output pseudo-random 32-bits integers also, the MELG algorithm is full 64-bits.
See Melg607 for a large period MELG-Generator (2^607, i.e. 5.31e+182) with medium computation time and the equivalent of 21 32-bits integers memory little consumption. This is the shortest period version proposed in paper [11].
See Melg19937 for an even larger period MELG-Generator (2^19,937, i.e. 4.32e+6001), same computation time and equivalent of 625 integers memory consumption.
See Melg44497 for a very large period (2^44,497, i.e. 8.55e+13,395) with similar computation time but use of even more memory space (equivalent of 1,393 32-bits integers). This is the longest period version proposed in paper [11].
Furthermore this class is callable:
BaseMELG rand();  // CAUTION: Replace 'BaseMELG' with any inheriting class constructor!
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
BaseMELG diceRoll();  // CAUTION: Replace 'BaseMELG' with any inheriting class constructor!
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the MELGs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Melg607 melg607-64 21 x 4-bytes 2^607 n.a. n.a. n.a. n.a. n.a.
Melg19937 melg19937-64 625 x 4-bytes 2^19937 n.a. 4.21 0 0 0
Melg44497 melg44497-64 1,393 x 4-bytes 2^44497 n.a. n.a. n.a. n.a. n.a.
+------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
BaseMELG() [1/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG () inline noexcept
Default empty constructor.
Empty constructor.
References BaseMELG(), and seed().
Referenced by BaseMELG().
BaseMELG() [2/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [3/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [4/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [5/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [6/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [7/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [8/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (utils::UInt128).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [9/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [10/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::setstate().
~BaseMELG()
template<const std::uint32_t SIZE> virtual BaseMELG< SIZE >::~BaseMELG () inline virtual default noexcept
default destructor.
Member Function Documentation
_setstate() [1/2]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-*bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
_setstate() [2/2]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::_setstate (const utils::UInt128 & seed) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::_setstate(), and seed().
seed() [1/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
Referenced by _setstate(), BaseMELG(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const double seed_) inline virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
seed() [3/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const int seed_) inline virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [4/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const long long seed_) inline virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [5/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const long seed_) inline virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [6/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [7/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
seed() [8/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [9/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
The documentation for this class was generated from the following file:
basemelg.h