CppRandLib - c++11: FastRand32 Class Reference
FastRand32 Class Reference
Fast Linear Congruential Generator - 32 bits.
#include <fastrand32.h>
Public Types
using MyBaseClass = BaseRandom<std::uint32_t, std::uint32_t, 32>
Public Types inherited from BaseRandom< std::uint32_t, std::uint32_t, 32 >
using output_type
using state_type
Public Member Functions
virtual void _setstate (const std::uint64_t seed_) noexcept override
Sets the internal state with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed_) noexcept override
Sets the internal state with a 128-bits integer seed.
FastRand32 () noexcept
Empty constructor.
FastRand32 (const double seed_)
Valued constructor (double).
FastRand32 (const int seed_) noexcept
Valued constructor (int).
FastRand32 (const long long seed_) noexcept
Valued constructor (long long).
FastRand32 (const long seed_) noexcept
Valued constructor (long)
FastRand32 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
FastRand32 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
FastRand32 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
FastRand32 (const utils::UInt128 &seed_) noexcept
Valued constructor (unsigned 128-bits).
virtual const output_type next () noexcept override
The internal PRNG algorithm.
virtual void seed () noexcept override
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~FastRand32 () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< std::uint32_t, std::uint32_t, 32 >
BaseRandom () noexcept=default
default empty constructor.
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
std::uint32_t getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be passed to setstate() later.
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate ()
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of n values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max)
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max)
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max)
Valued call operator (2 std::vector of scalars).
const T operator() (const T max)
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const std::uint32_t &new_internal_state) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b)
Returns random integer in range [a, b], including both end points.
const T random ()
The uniform distribution on [0.0, 1.0).
const long double random ()
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void setstate (const std::uint32_t &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const std::uint32_t &new_internal_state, const double gauss_next) noexcept
Sets the internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
Shuffles specified sequence in place.
const state_type state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform ()
Uniform distribution in [0.0, 1.0).
const double uniform (const double max)
const float uniform (const float max)
const long double uniform (const long double max)
const T uniform (const U max)
Uniform distribution in [0.0, max).
const T uniform (const U min, const V max)
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< std::uint32_t, std::uint32_t, 32 >
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< std::uint32_t, std::uint32_t, 32 >
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static const double BPF
static const double E
static const double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static const double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static const double TWO_PI
Detailed Description
Fast Linear Congruential Generator - 32 bits.
Pseudo-random numbers generator - Linear Congruential Generator dedicated to 32-bits calculations with very short period (about 4.3e+09) but very short time computation.
LCG models evaluate pseudo-random numbers suites x(i) as a simple mathem- atical function of
x(i) = (a * x(i-1) + c) mod m
Results are nevertheless considered to be poor as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in 'TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007'. It is not recommended to use such pseudo-random numbers generators for serious simulation applications.
The implementation of this LCG 32-bits model is based on (a=69069, c=1) since these two values have evaluated to be the 'best' ones for LCGs within TestU01 while m = 2^32.
See FastRand63 for a 2^63 (i.e. about 9.2e+18) period LC-Generator with low computation time also, longer period and quite better randomness characteristics than for FastRand32.
Furthermore this class is callable:
FastRand32 rand{};
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(a) << std::endl;   // prints a uniform pseudo-random value within [0.0, a)
Notice that for simulating the roll of a dice you should program:
FastRand32 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the LCGs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +---------------------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
FastRand32 LCG(2^32, 69069, 1) 1 x 4-bytes 2^32 3.20 0.67 11 106 too many
FastRand63 LCG(2^63, 9219741426499971445, 1) 2 x 4-bytes 2^63 4.20 0.75 0 5 7
+---------------------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
FastRand32() [1/9]
FastRand32::FastRand32 () inline noexcept
Empty constructor.
Empty constructor.
References FastRand32(), and seed().
Referenced by FastRand32().
FastRand32() [2/9]
FastRand32::FastRand32 (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
FastRand32() [3/9]
FastRand32::FastRand32 (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
FastRand32() [4/9]
FastRand32::FastRand32 (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
FastRand32() [5/9]
FastRand32::FastRand32 (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
FastRand32() [6/9]
FastRand32::FastRand32 (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
FastRand32() [7/9]
FastRand32::FastRand32 (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
FastRand32() [8/9]
FastRand32::FastRand32 (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References seed().
FastRand32() [9/9]
FastRand32::FastRand32 (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References seed().
~FastRand32()
virtual FastRand32::~FastRand32 () inline virtual default noexcept
default destructor.
References _setstate(), next(), and seed().
Member Function Documentation
_setstate() [1/2]
void FastRand32::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state with a 64-bits integer seed.
Sets the internal state with an integer seed.
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
Referenced by _setstate(), and ~FastRand32().
_setstate() [2/2]
void FastRand32::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state with a 128-bits integer seed.
Sets the internal state with a 128-bits integer seed.
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References _setstate().
next()
const FastRand32::output_type FastRand32::next () inline override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
Referenced by ~FastRand32().
seed() [1/9]
void FastRand32::seed () inline override virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References BaseRandom< std::uint32_t, std::uint32_t, 32 >::seed().
Referenced by FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), seed(), seed(), seed(), seed(), seed(), and ~FastRand32().
seed() [2/9]
void FastRand32::seed (const double seed_) inline virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References BaseRandom< std::uint32_t, std::uint32_t, 32 >::seed().
seed() [3/9]
void FastRand32::seed (const int seed_) inline virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References seed().
seed() [4/9]
void FastRand32::seed (const long long seed_) inline virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References seed().
seed() [5/9]
void FastRand32::seed (const long seed_) inline virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References seed().
seed() [6/9]
void FastRand32::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References seed().
seed() [7/9]
void FastRand32::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References BaseRandom< std::uint32_t, std::uint32_t, 32 >::seed().
seed() [8/9]
void FastRand32::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References seed().
seed() [9/9]
void FastRand32::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References BaseRandom< std::uint32_t, std::uint32_t, 32 >::seed().
The documentation for this class was generated from the following file:
fastrand32.h