CppRandLib - c++11: BaseLFib64< SIZE, K > Class Template Reference
BaseLFib64< SIZE, K > Class Template Reference
The base class for all LFib PRNG based on 64-bits numbers.
#include <baselfib64.h>
Public Types
using MyBaseClass = BaseRandom<ListSeedState<utils::SplitMix64, std::uint64_t, SIZE>, std::uint64_t, 64>
using output_type = MyBaseClass::output_type
using state_type = MyBaseClass::state_type
using value_type = typename state_type::value_type
Public Types inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >
using output_type
using state_type
Public Member Functions
void _initIndex (const size_t _index) noexcept
Inits the internal index pointing to the internal list.
virtual void _setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseLFib64 () noexcept
Default empty constructor.
BaseLFib64 (const double seed)
Valued constructor (double).
BaseLFib64 (const int seed) noexcept
Valued constructor (int).
BaseLFib64 (const long long seed) noexcept
Valued constructor (long long).
BaseLFib64 (const long seed) noexcept
Valued constructor (long)
BaseLFib64 (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseLFib64 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseLFib64 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseLFib64 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseLFib64 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual const output_type next () noexcept override
The internal PRNG algorithm.
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~BaseLFib64 () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >
BaseRandom () noexcept=default
default empty constructor.
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
std::uint64_t getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be passed to setstate() later.
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate ()
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of n values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max)
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max)
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max)
Valued call operator (2 std::vector of scalars).
const T operator() (const T max)
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b)
Returns random integer in range [a, b], including both end points.
const T random ()
The uniform distribution on [0.0, 1.0).
const long double random ()
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void setstate (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state, const double gauss_next) noexcept
Sets the internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
Shuffles specified sequence in place.
const state_type state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform ()
Uniform distribution in [0.0, 1.0).
const double uniform (const double max)
const float uniform (const float max)
const long double uniform (const long double max)
const T uniform (const U max)
Uniform distribution in [0.0, max).
const T uniform (const U min, const V max)
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Static Public Attributes
static const std::uint32_t SEED_SIZE { SIZE }
Additional Inherited Members
Public Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static const double BPF
static const double E
static const double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static const double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static const double TWO_PI
Detailed Description
template<const std::uint32_t SIZE, const std::uint32_t K>
class BaseLFib64< SIZE, K >
The base class for all LFib PRNG based on 64-bits numbers.
Definition of the base class for all LFib pseudo-random generators based on 64-bits generated numbers.
Lagged Fibonacci generators LFib(m, r, k, op) use the recurrence
x(i) = (x(i-r) op (x(i-k)) mod m
where op is an operation that can be:
(addition),
(substraction),
(multiplication), ^ (bitwise exclusive-or).
With the + or - operation, such generators are in fact MRGs. They offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007". It is recommended to use such pseudo-random numbers generators rather than LCG ones for serious simulation applications.
See LFib78, LFib116, LFib668 and LFib1340 for long period LFib generators (resp. 2^78, 2^116, 2^668 and 2^1340 periods, i.e. resp. 3.0e+23, 8.3e+34, 1.2e+201 and 2.4e+403 periods) while same computation time and far higher precision (64-bits calculations) than MRGs, but more memory consumption (resp. 17, 55, 607 and 1279 integers).
Furthermore this class is callable:
    BaseLFib64 rand{}; // CAUTION: rplace 'BaseLFib64' with any inheriting class constructor!
    std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
    std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
@endoced
  Notice that for simulating the roll of a dice you should program:
@code
    BaseLFib64 diceRoll(); // CAUTION: replace 'BaseLFib64' with any inheriting class constructor!
    std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
    std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the LCGs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +-----------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRabdLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
LFibRand78 LFib(2^64, 17, 5, +) 34 x 4-bytes 2^78 n.a. 1.1 0 0 0
LFibRand11 LFib(2^64, 55, 24, +) 110 x 4-bytes 2^116 n.a. 1.0 0 0 0
LFibRand668 LFib(2^64, 607, 273, +) 1,214 x 4-bytes 2^668 n.a. 0.9 0 0 0
LFibRand1340 LFib(2^64, 1279, 861, +) 2,558 x 4-bytes 2^1340 n.a. 0.9 0 0 0
+-----------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
BaseLFib64() [1/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 () inline noexcept
Default empty constructor.
Empty constructor.
References BaseLFib64(), and seed().
Referenced by BaseLFib64().
BaseLFib64() [2/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
BaseLFib64() [3/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
BaseLFib64() [4/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
BaseLFib64() [5/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
BaseLFib64() [6/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
BaseLFib64() [7/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
BaseLFib64() [8/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (utils::UInt128).
References seed().
BaseLFib64() [9/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References seed().
BaseLFib64() [10/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::setstate().
~BaseLFib64()
template<const std::uint32_t SIZE, const std::uint32_t K> virtual BaseLFib64< SIZE, K >::~BaseLFib64 () inline virtual default noexcept
default destructor.
Member Function Documentation
_initIndex()
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::_initIndex (const size_t _index) inline noexcept
Inits the internal index pointing to the internal list.
Inits the internal index pointing to the internal list.
_setstate() [1/2]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
_setstate() [2/2]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::_setstate (const utils::UInt128 & seed) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::_setstate(), and seed().
next()
template<const std::uint32_t SIZE, std::uint32_t K> const BaseLFib64< SIZE, K >::output_type BaseLFib64< SIZE, K >::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
seed() [1/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
Referenced by _setstate(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const double seed_) inline virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
seed() [3/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const int seed_) inline virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [4/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const long long seed_) inline virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [5/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const long seed_) inline virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [6/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [7/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
seed() [8/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [9/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
The documentation for this class was generated from the following file:
baselfib64.h