CppRandLib - c++11: utils Namespace Reference
utils Namespace Reference
Utilities
Classes
class is_indexable
class is_indexable< std::array< T, n > >
class is_indexable< std::vector< T > >
class SplitMix31
The splitting and mixing algorithm used to initialize 31-bits internal states of PRNGs.
class SplitMix32
The splitting and mixing algorithm used to initialize 32-bits internal states of PRNGs.
class SplitMix63
The splitting and mixing algorithm used to initialize 63-bits internal states of PRNGs.
class SplitMix64
The splitting and mixing algorithm used to initialize 64-bits internal states of PRNGs.
class UInt128
128 bits integer minimalist arithmetic.
Functions
template<typename IntT>
const IntT balanced_bits_generation (const std::uint64_t seed)
Generates balanced bits patterns in integers.
const std::uint64_t get_time_ms () noexcept
Returns the current time since epoch as a 64-bits milliseconds integer.
const std::uint64_t get_time_ns () noexcept
Returns the current time since epoch as a 64-bits nanoseconds integer.
const std::uint64_t get_time_us () noexcept
Returns the current time since epoch as a 64-bits microseconds integer.
template<typename IntT>
const IntT rot_left (const IntT value, const int rot_count, const int BITS_COUNT=8 *sizeof(IntT))
Bits left rotation on unsigned integers.
const std::uint32_t set_random_seed31 ()
Generates a 31-bits random seed for PRNGs, based on the current system time.
const std::uint32_t set_random_seed32 ()
Generates a 32-bits random seed for PRNGs, based on the current system time.
const std::uint64_t set_random_seed63 ()
Generates a 63-bits random seed for PRNGs, based on the current system time.
const std::uint64_t set_random_seed64 ()
Generates a 64-bits random seed for PRNGs, based on the current system time.
Function Documentation
balanced_bits_generation()
template<typename IntT> const IntT utils::balanced_bits_generation (const std::uint64_t seed) inline
Generates balanced bits patterns in integers.
balanced_bits_generation.h This is a free local implementation of the algorithm described in document referenced [9] in README.md and of the coding of all 64-bits keys generation that is available in file keys/keys.c in related software package https://squaresrng.wixsite.com/rand. (Bernard Widynski1, March 2022, extracted text from keys/keys.c: The keys are created so that the upper 8 digits are different and also * that the lower 8 digits are different. The lower 8 digits are created * systematically so that all possible combinations are produced. The * ninth digit is chosen to be different than the eighth digit. The rest * of the upper 7 digits are chosen randomly. For any two keys produced, * it is certain that at least one digit is different in the lower 9 * digits. Testing has shown that this prevents similarities that can * arise in streams produced by keys that vary only in the upper digits.) *
Notice: Should you need to call this function many times to initialize multiple streams of PRNGs, ensure that no two initial seeds values are finaly the same on their 9 lowest hexa digits.
Referenced by CounterKeyState::seed(), and CounterKeyState::seed().
get_time_ms()
const std::uint64_t utils::get_time_ms () inline noexcept
Returns the current time since epoch as a 64-bits milliseconds integer.
get_time_ns()
const std::uint64_t utils::get_time_ns () inline noexcept
Returns the current time since epoch as a 64-bits nanoseconds integer.
get_time_us()
const std::uint64_t utils::get_time_us () inline noexcept
Returns the current time since epoch as a 64-bits microseconds integer.
Referenced by set_random_seed64(), and utils::SplitMix64::SplitMix64().
rot_left()
template<typename IntT> const IntT utils::rot_left (const IntT value, const int rot_count, const int BITS_COUNT = 8 * sizeof(IntT)) inline
Bits left rotation on unsigned integers.
Referenced by Xoroshiro1024::next(), Xoroshiro256::next(), and Xoroshiro512::next().
set_random_seed31()
const std::uint32_t utils::set_random_seed31 () inline
Generates a 31-bits random seed for PRNGs, based on the current system time.
This method is used to generate an as much random seed as possible without using the STL method 'std::random_device' which is known to not always use hardwara features to generate random numbers and for which no ensured way exist to check if such features are available on all platforms and on all hardware.
References set_random_seed64().
Referenced by BaseMRG31< SIZE >::seed().
set_random_seed32()
const std::uint32_t utils::set_random_seed32 () inline
Generates a 32-bits random seed for PRNGs, based on the current system time.
This method is used to generate an as much random seed as possible without using the STL method 'std::random_device' which is known to not always use hardwara features to generate random numbers and for which no ensured way exist to check if such features are available on all platforms and on all hardware.
References set_random_seed64().
Referenced by BaseMRG32< SIZE >::seed().
set_random_seed63()
const std::uint64_t utils::set_random_seed63 () inline
Generates a 63-bits random seed for PRNGs, based on the current system time.
This method is used to generate an as much random seed as possible without using the STL method 'std::random_device' which is known to not always use hardwara features to generate random numbers and for which no ensured way exist to check if such features are available on all platforms and on all hardware.
References set_random_seed64().
set_random_seed64()
const std::uint64_t utils::set_random_seed64 () inline
Generates a 64-bits random seed for PRNGs, based on the current system time.
This method is used to generate an as much random seed as possible without using the STL method 'std::random_device' which is known to not always use hardwara features to generate random numbers and for which no ensured way exist to check if such features are available on all platforms and on all hardware.
References get_time_us().
Referenced by BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed(), BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed(), BaseSquares< OutputT >::seed(), CounterKeyState::seed(), set_random_seed31(), set_random_seed32(), and set_random_seed63().