CppRandLib - c++11: ListSeedState< RandomT, ItemT, SIZE > Struct Template Reference
ListSeedState< RandomT, ItemT, SIZE > Struct Template Reference
The internal state of many Pseudo Random Numbers Generators.
#include <listseedstate.h>
Public Types
using value_type = ItemT
Public Member Functions
void inc_index () noexcept
Increments the internal index pointing to the internal list.
void init_index (const std::uint32_t new_index) noexcept
Initializes the internal index pointing to the internal list.
ListSeedState () noexcept
< Empty constructor.
const bool operator!= (const ListSeedState &other) const noexcept
Returns true if states differ.
const bool operator== (const ListSeedState &other) const noexcept
Returns true if both states are the same.
void seed (const std::uint64_t seed_) noexcept
Initializes the internal state container items.
Public Attributes
std::uint32_t index { 0UL }
std::vector< ItemT > list {}
Detailed Description
template<typename RandomT, typename ItemT, const std::uint32_t SIZE>
struct ListSeedState< RandomT, ItemT, SIZE >
The internal state of many Pseudo Random Numbers Generators.
Constructor & Destructor Documentation
ListSeedState()
template<typename RandomT, typename ItemT, const std::uint32_t SIZE> ListSeedState< RandomT, ItemT, SIZE >::ListSeedState () inline noexcept
< Empty constructor.
Referenced by operator!=(), and operator==().
Member Function Documentation
inc_index()
template<typename RandomT, typename ItemT, const std::uint32_t SIZE> void ListSeedState< RandomT, ItemT, SIZE >::inc_index () inline noexcept
Increments the internal index pointing to the internal list.
init_index()
template<typename RandomT, typename ItemT, const std::uint32_t SIZE> void ListSeedState< RandomT, ItemT, SIZE >::init_index (const std::uint32_t new_index) inline noexcept
Initializes the internal index pointing to the internal list.
operator!=()
template<typename RandomT, typename ItemT, const std::uint32_t SIZE> const bool ListSeedState< RandomT, ItemT, SIZE >::operator!= (const ListSeedState< RandomT, ItemT, SIZE > & other) const inline noexcept
Returns true if states differ.
References ListSeedState().
operator==()
template<typename RandomT, typename ItemT, const std::uint32_t SIZE> const bool ListSeedState< RandomT, ItemT, SIZE >::operator== (const ListSeedState< RandomT, ItemT, SIZE > & other) const inline noexcept
Returns true if both states are the same.
References ListSeedState().
seed()
template<typename RandomT, typename ItemT, const std::uint32_t SIZE> void ListSeedState< RandomT, ItemT, SIZE >::seed (const std::uint64_t seed_) inline noexcept
Initializes the internal state container items.
Initializes the container associated with the internal state of PRNGs. template argument ItemT must be an integral type. Notice: MELG algorithm states that at least one of its internal state items must be non zero. Since we now use an internal implementation of SplitMix that never uses its internal state when its value is 0, not more than one item in the list of internal state items of any PRNG will be zero.
The documentation for this struct was generated from the following file:
listseedstate.h