CppRandLib - c++20: algos: MRG - Multiple Recursive Generators
algos: MRG - Multiple Recursive Generators
Classes
struct BaseMRG31< SIZE >
The base support for 31-bits MRG Pseudo Random Number Generators.
struct BaseMRG32< SIZE >
The base support for 32-bits MRG Pseudo Random Number Generators.
class Mrg1457
A fast 31-bits Multiple Recursive Generator with a somewhat long period (3.98e+438)
class Mrg287
A fast 32-bits Multiple Recursive Generator with a long period (2.49e+86).
class Mrg49507
A fast 31-bits Multiple Recursive Generator with a very long period (1.2e+14,903)
Functions
virtual void BaseMRG31< SIZE >::_setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void BaseMRG31< SIZE >::_setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
virtual void BaseMRG32< SIZE >::_setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void BaseMRG32< SIZE >::_setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseMRG31< SIZE >::BaseMRG31 () noexcept
Default empty constructor.
BaseMRG31< SIZE >::BaseMRG31 (const double seed)
Valued constructor (double).
BaseMRG31< SIZE >::BaseMRG31 (const int seed) noexcept
Valued constructor (int).
BaseMRG31< SIZE >::BaseMRG31 (const long long seed) noexcept
Valued constructor (long long).
BaseMRG31< SIZE >::BaseMRG31 (const long seed) noexcept
Valued constructor (long)
BaseMRG31< SIZE >::BaseMRG31 (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseMRG31< SIZE >::BaseMRG31 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseMRG31< SIZE >::BaseMRG31 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseMRG31< SIZE >::BaseMRG31 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseMRG31< SIZE >::BaseMRG31 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
BaseMRG32< SIZE >::BaseMRG32 () noexcept
Default empty constructor.
BaseMRG32< SIZE >::BaseMRG32 (const double seed)
Valued constructor (double).
BaseMRG32< SIZE >::BaseMRG32 (const int seed) noexcept
Valued constructor (int).
BaseMRG32< SIZE >::BaseMRG32 (const long long seed) noexcept
Valued constructor (long long).
BaseMRG32< SIZE >::BaseMRG32 (const long seed) noexcept
Valued constructor (long)
BaseMRG32< SIZE >::BaseMRG32 (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseMRG32< SIZE >::BaseMRG32 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseMRG32< SIZE >::BaseMRG32 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseMRG32< SIZE >::BaseMRG32 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseMRG32< SIZE >::BaseMRG32 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void BaseMRG31< SIZE >::seed () noexcept
Initializes internal state (empty signature).
void BaseMRG31< SIZE >::seed (const double seed_)
Initializes internal state (double).
void BaseMRG31< SIZE >::seed (const int seed_) noexcept
Initializes internal state (int).
void BaseMRG31< SIZE >::seed (const long long seed_) noexcept
Initializes internal state (long long).
void BaseMRG31< SIZE >::seed (const long seed_) noexcept
Initializes internal state (long)
void BaseMRG31< SIZE >::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void BaseMRG31< SIZE >::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void BaseMRG31< SIZE >::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void BaseMRG31< SIZE >::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
void BaseMRG32< SIZE >::seed () noexcept
Initializes internal state (empty signature).
void BaseMRG32< SIZE >::seed (const double seed_)
Initializes internal state (double).
void BaseMRG32< SIZE >::seed (const int seed_) noexcept
Initializes internal state (int).
void BaseMRG32< SIZE >::seed (const long long seed_) noexcept
Initializes internal state (long long).
void BaseMRG32< SIZE >::seed (const long seed_) noexcept
Initializes internal state (long)
void BaseMRG32< SIZE >::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void BaseMRG32< SIZE >::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void BaseMRG32< SIZE >::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void BaseMRG32< SIZE >::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
This is the group for all the CppRandLib implementations of the Multiple Recursive pseudorandom Generators (MRG) algorithm.
Multiple Recursive Generators (MRGs) use recurrence to evaluate pseudo- random numbers suites. Recurrence is of the form:
x(i) = A * SUM[ x(i-k) ]  mod M
for 2 to more k different values.
MRGs offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007".
Function Documentation
_setstate() [1/4]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >.
Referenced by seed().
_setstate() [2/4]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >.
_setstate() [3/4]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
Referenced by seed().
_setstate() [4/4]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
BaseMRG31() [1/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 () inline noexcept
Default empty constructor.
Empty constructor.
References BaseMRG31(), and seed().
Referenced by BaseMRG31().
BaseMRG31() [2/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
BaseMRG31() [3/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
BaseMRG31() [4/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
BaseMRG31() [5/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
BaseMRG31() [6/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::setstate().
BaseMRG31() [7/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
BaseMRG31() [8/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
BaseMRG31() [9/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
BaseMRG31() [10/10]
template<const std::uint32_t SIZE> BaseMRG31< SIZE >::BaseMRG31 (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
BaseMRG32() [1/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 () inline noexcept
Default empty constructor.
Empty constructor.
References BaseMRG32(), and seed().
Referenced by BaseMRG32().
BaseMRG32() [2/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseMRG32() [3/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseMRG32() [4/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseMRG32() [5/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseMRG32() [6/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::setstate().
BaseMRG32() [7/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseMRG32() [8/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructo (unsigned long long)r.
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseMRG32() [9/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseMRG32() [10/10]
template<const std::uint32_t SIZE> BaseMRG32< SIZE >::BaseMRG32 (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [1/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >.
References _setstate(), and utils::set_random_seed31().
Referenced by BaseMRG31().
seed() [2/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed (const double seed_) inline
Initializes internal state (double).
Initializes internal state (double).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
seed() [3/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed (const int seed_) inline noexcept
Initializes internal state (int).
Initializes internal state (int).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
seed() [4/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed (const long long seed_) inline noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
seed() [5/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed (const long seed_) inline noexcept
Initializes internal state (long)
Initializes internal state (long).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
seed() [6/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed (const unsigned int seed_) inline noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
seed() [7/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed (const unsigned long long seed_) inline noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
seed() [8/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed (const unsigned long seed_) inline noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
seed() [9/18]
template<const std::uint32_t SIZE> void BaseMRG31< SIZE >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >.
References BaseRandom< ListSeedState< utils::SplitMix31, std::uint32_t, SIZE >, std::uint32_t, 31 >::seed().
seed() [10/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References _setstate(), and utils::set_random_seed32().
Referenced by BaseMRG32().
seed() [11/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed (const double seed_) inline
Initializes internal state (double).
Initializes internal state (double).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [12/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed (const int seed_) inline noexcept
Initializes internal state (int).
Initializes internal state (int).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [13/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed (const long long seed_) inline noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [14/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed (const long seed_) inline noexcept
Initializes internal state (long)
Initializes internal state (long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [15/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed (const unsigned int seed_) inline noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [16/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed (const unsigned long long seed_) inline noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [17/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed (const unsigned long seed_) inline noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [18/18]
template<const std::uint32_t SIZE> void BaseMRG32< SIZE >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().