CppRandLib - c++20: utils: Random seeds default generation
utils: Random seeds default generation
Functions
const std::uint32_t utils::set_random_seed31 ()
Generates a 31-bits random seed for PRNGs, based on the current system time.
const std::uint32_t utils::set_random_seed32 ()
Generates a 32-bits random seed for PRNGs, based on the current system time.
const std::uint64_t utils::set_random_seed63 ()
Generates a 63-bits random seed for PRNGs, based on the current system time.
const std::uint64_t utils::set_random_seed64 ()
Generates a 64-bits random seed for PRNGs, based on the current system time.
Detailed Description
These utilities return 64-, 63-, 32- and 31-bits integers set with the xored and shuffled value of current system time. They are used to seed PRNGs with a pseudo-randomized initialization value when no explicit seed value is provided at their instantiation time.
Function Documentation
set_random_seed31()
const std::uint32_t utils::set_random_seed31 () inline
Generates a 31-bits random seed for PRNGs, based on the current system time.
This method is used to generate an as much random seed as possible without using the STL method 'std::random_device' which is known to not always use hardwara features to generate random numbers and for which no ensured way exist to check if such features are available on all platforms and on all hardware.
References set_random_seed64().
Referenced by BaseMRG31< SIZE >::seed().
set_random_seed32()
const std::uint32_t utils::set_random_seed32 () inline
Generates a 32-bits random seed for PRNGs, based on the current system time.
This method is used to generate an as much random seed as possible without using the STL method 'std::random_device' which is known to not always use hardwara features to generate random numbers and for which no ensured way exist to check if such features are available on all platforms and on all hardware.
References set_random_seed64().
Referenced by BaseMRG32< SIZE >::seed().
set_random_seed63()
const std::uint64_t utils::set_random_seed63 () inline
Generates a 63-bits random seed for PRNGs, based on the current system time.
This method is used to generate an as much random seed as possible without using the STL method 'std::random_device' which is known to not always use hardwara features to generate random numbers and for which no ensured way exist to check if such features are available on all platforms and on all hardware.
References set_random_seed64().
set_random_seed64()
const std::uint64_t utils::set_random_seed64 () inline
Generates a 64-bits random seed for PRNGs, based on the current system time.
This method is used to generate an as much random seed as possible without using the STL method 'std::random_device' which is known to not always use hardwara features to generate random numbers and for which no ensured way exist to check if such features are available on all platforms and on all hardware.
References get_time_us().
Referenced by BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed(), BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed(), BaseSquares< OutputT >::seed(), set_random_seed31(), set_random_seed32(), and set_random_seed63().