CppRandLib - c++20: Melg44497 Class Reference
Melg44497 Class Reference
A 64-bits Maximally Equidistributed Long-period Linear Generator with a long period (8.55e+13,395).
#include <melg44497.h>
Public Types
using MyBaseClass = BaseMELG<696>
using output_type = MyBaseClass::output_type
using state_type = MyBaseClass::state_type
using value_type = typename state_type::value_type
Public Member Functions
Melg44497 () noexcept
Default empty constructor.
Melg44497 (const double seed)
Valued constructor (double).
Melg44497 (const int seed) noexcept
Valued constructor (int).
Melg44497 (const long long seed) noexcept
Valued constructor (long long).
Melg44497 (const long seed) noexcept
Valued constructor (long)
Melg44497 (const state_type &internal_state) noexcept
Valued constructor (full state).
Melg44497 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Melg44497 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Melg44497 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Melg44497 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual const output_type next () noexcept override
The internal PRNG algorithm.
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~Melg44497 () noexcept=default
default destructor.
Detailed Description
A 64-bits Maximally Equidistributed Long-period Linear Generator with a long period (8.55e+13,395).
Maximally Equidistributed Long-period Linear Generators (MELG) use linear recurrence based on state transitions with double feedbacks and linear output transformations with several memory references. See reference [11] in README.md.
MELGs offer large to very large periods with best known results in the evaluation of their randomness. They ensure a maximally equidistributed generation of pseudo random numbers. They pass all TestU01 tests and newer ones but are the slowest to compute ones in the base of PRNGs that have been implemented in CppRandLib.
See Melg607 for a large period MELG-Generator (2^607, i.e. 5.31e+182) with medium computation time and the equivalent of 21 32-bits integers memory little consumption. This is the shortest period version proposed in paper [11].
See Melg19937 for an even larger period MELG-Generator (2^19,937, i.e. 4.32e+6001), same computation time and equivalent of 625 integers memory consumption.
Furthermore this class is callable:
Melg44497 rand();
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
Melg44497 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the MELGs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Melg607 melg607-64 21 x 4-bytes 2^607 n.a. n.a. n.a. n.a. n.a.
Melg19937 melg19937-64 625 x 4-bytes 2^19937 n.a. 4.21 0 0 0
Melg44497 melg44497-64 1,393 x 4-bytes 2^44497 n.a. n.a. n.a. n.a. n.a.
+------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Melg44497() [1/10]
Melg44497::Melg44497 () noexcept
Default empty constructor.
Empty constructor.
References seed().
Melg44497() [2/10]
Melg44497::Melg44497 (const int seed_) noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
Melg44497() [3/10]
Melg44497::Melg44497 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
Melg44497() [4/10]
Melg44497::Melg44497 (const long seed_) noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
Melg44497() [5/10]
Melg44497::Melg44497 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
Melg44497() [6/10]
Melg44497::Melg44497 (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
Melg44497() [7/10]
Melg44497::Melg44497 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
Melg44497() [8/10]
Melg44497::Melg44497 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (utils::UInt128).
References seed().
Melg44497() [9/10]
Melg44497::Melg44497 (const double seed_)
Valued constructor (double).
Valued constructor (double).
References seed().
Melg44497() [10/10]
Melg44497::Melg44497 (const state_type & internal_state) noexcept
Valued constructor (full state).
Valued constructor (full state).
~Melg44497()
virtual Melg44497::~Melg44497 () inline virtual default noexcept
default destructor.
References next(), and seed().
Member Function Documentation
next()
const Melg44497::output_type Melg44497::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Referenced by ~Melg44497().
seed() [1/9]
void Melg44497::seed () noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Referenced by Melg44497(), Melg44497(), Melg44497(), Melg44497(), Melg44497(), Melg44497(), Melg44497(), Melg44497(), Melg44497(), seed(), seed(), seed(), seed(), seed(), and ~Melg44497().
seed() [2/9]
void Melg44497::seed (const double seed_)
Initializes internal state (double).
Initializes internal state (double).
seed() [3/9]
void Melg44497::seed (const int seed_) noexcept
Initializes internal state (int).
Initializes internal state (int).
References seed().
seed() [4/9]
void Melg44497::seed (const long long seed_) noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References seed().
seed() [5/9]
void Melg44497::seed (const long seed_) noexcept
Initializes internal state (long)
Initializes internal state (long).
References seed().
seed() [6/9]
void Melg44497::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References seed().
seed() [7/9]
void Melg44497::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
seed() [8/9]
void Melg44497::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References seed().
seed() [9/9]
void Melg44497::seed (const utils::UInt128 & seed_) noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
The documentation for this class was generated from the following files:
melg44497.h
melg44497.cpp