CppRandLib - c++20: Xoroshiro1024 Class Reference
Xoroshiro1024 Class Reference
Scrambled Linear Pseudorandom Number Generators (xoroshiro) algorithm
A very fast 64-bits Scrambled Linear Pseudorandom Number Generators with a very long period (1.80e+308)
#include <xoroshiro1024.h>
Public Types
using MyBaseClass = BaseXoroshiro<16>
Public Types inherited from BaseXoroshiro< 16 >
using MyBaseClass
using output_type
using state_type
using value_type
Public Types inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >
using output_type
using state_type
Public Member Functions
virtual const output_type next () noexcept override
The internal PRNG algorithm.
Xoroshiro1024 () noexcept
Default empty constructor.
Xoroshiro1024 (const double seed)
Valued constructor (double).
Xoroshiro1024 (const int seed) noexcept
Valued constructor (int).
Xoroshiro1024 (const long long seed) noexcept
Valued constructor (long long).
Xoroshiro1024 (const long seed) noexcept
Valued constructor (long)
Xoroshiro1024 (const state_type &internal_state) noexcept
Valued constructor (full state).
Xoroshiro1024 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Xoroshiro1024 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Xoroshiro1024 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Xoroshiro1024 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual ~Xoroshiro1024 () noexcept=default
default destructor.
Public Member Functions inherited from BaseXoroshiro< 16 >
virtual void _setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseXoroshiro () noexcept
Default empty constructor.
BaseXoroshiro (const double seed)
Valued constructor (double).
BaseXoroshiro (const int seed) noexcept
Valued constructor (int).
BaseXoroshiro (const long long seed) noexcept
Valued constructor (long long).
BaseXoroshiro (const long seed) noexcept
Valued constructor (long)
BaseXoroshiro (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseXoroshiro (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseXoroshiro (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseXoroshiro (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseXoroshiro (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~BaseXoroshiro () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >
BaseRandom () noexcept=default
default empty constructor
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (const CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
std::uint64_t getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be later passed to setstate().
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate () noexcept
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max) noexcept
Returns an array of min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of max.size() values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max) noexcept
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max) noexcept
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max) noexcept
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max) noexcept
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max) noexcept
Valued call operator (2 std::vector of scalars).
const T operator() (const T max) noexcept
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &seed) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b) noexcept
Returns a random integer in range [a, b], including both end points.
const T random () noexcept
The uniform distribution on [0.0, 1.0).
const long double random () noexcept
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void seed (const double seed_)
Initalizes internal state from a double seed.
void seed (const int seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
void seed (const long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned int seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const unsigned long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void setstate (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state, const double gauss_next) noexcept
Restores internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
In place Shuffles the specified sequence.
const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform () noexcept
Uniform distribution in [0.0, 1.0).
const double uniform (const double max) noexcept
const float uniform (const float max) noexcept
const long double uniform (const long double max) noexcept
const T uniform (const U max) noexcept
Uniform distribution [0.0, max).
const T uniform (const U min, const V max) noexcept
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static constexpr double BPF
static const double E
static constexpr double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static constexpr double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static constexpr double TWO_PI
Detailed Description
A very fast 64-bits Scrambled Linear Pseudorandom Number Generators with a very long period (1.80e+308)
This pseudorandom numbers generator implements the xoroshiro1024** pseudo-random generator, the 16 64-bits integers state array version of the Scrambled Linear Pseudorandom Number Generators. It provides 64-bits pseudo random values, a medium period 2^1024 (i.e. about 1.80e+308), jump ahead feature, short escape from zeroland (100 iterations only) and passes TestU01 tests.
The base xoroshiro linear transformation is obtained combining a rotation, a shift, and again a rotation. An additional scrambling method based on two multiplications is also computed for this version xoroshiro256** of the algorithm.
See Xoroshiro256 for a large 2^256 period (i.e. about 1.16e+77) scramble linear PRNG, with low computation time, 64-bits output values and good randomness characteristics.
See Xoroshiro512 for a large 2^256 period (i.e. about 1.16e+77) scramble linear PRNG, with low computation time, 64-bits output values and good randomness characteristics.
Furthermore this class is callable:
Xoroshiro1024 rand();
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
Xoroshiro1024 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the xoroshiros that have been implemented in CppRandLib, as described by the authors of xoroshiro - see reference [10] in file README.md.
+----------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class initial xoroshiro algo name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Xoroshiro256 xoroshiro256** 8 x 4-bytes 2^256 n.a. 0.84 0 0 0
Xoroshiro512 xoroshiro512** 16 x 4-bytes 2^512 n.a. 0.99 0 0 0
Xoroshiro1024 xoroshiro1024** 32 x 4-bytes 2^1024 n.a. 1.17 0 0 0
+----------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Xoroshiro1024() [1/10]
Xoroshiro1024::Xoroshiro1024 () noexcept
Default empty constructor.
Empty constructor.
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [2/10]
Xoroshiro1024::Xoroshiro1024 (const int seed_) noexcept
Valued constructor (int).
Valued constructor (int).
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [3/10]
Xoroshiro1024::Xoroshiro1024 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [4/10]
Xoroshiro1024::Xoroshiro1024 (const long seed_) noexcept
Valued constructor (long)
Valued constructor (long).
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [5/10]
Xoroshiro1024::Xoroshiro1024 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor(unsigned long).
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [6/10]
Xoroshiro1024::Xoroshiro1024 (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor (long long).
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [7/10]
Xoroshiro1024::Xoroshiro1024 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [8/10]
Xoroshiro1024::Xoroshiro1024 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [9/10]
Xoroshiro1024::Xoroshiro1024 (const double seed_)
Valued constructor (double).
Valued constructor (double).
References BaseXoroshiro< 16 >::seed().
Xoroshiro1024() [10/10]
Xoroshiro1024::Xoroshiro1024 (const state_type & internal_state) noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::setstate().
~Xoroshiro1024()
virtual Xoroshiro1024::~Xoroshiro1024 () inline virtual default noexcept
default destructor.
References next().
Member Function Documentation
next()
const Xoroshiro1024::output_type Xoroshiro1024::next () override virtual noexcept
The internal PRNG algorithm.
Returns
an integer value coded on 32 bits.
The internal PRNG algorithm.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
Referenced by ~Xoroshiro1024().
The documentation for this class was generated from the following files:
xoroshiro1024.h
xoroshiro1024.cpp