CppRandLib - c++20: Mrg287 Class Reference
Mrg287 Class Reference
algos: MRG - Multiple Recursive Generators
A fast 32-bits Multiple Recursive Generator with a long period (2.49e+86).
#include <mrg287.h>
Public Types
using MyBaseClass = BaseMRG32<256>
using output_type = MyBaseClass::output_type
using state_type = MyBaseClass::state_type
using value_type = typename state_type::value_type
Public Types inherited from BaseMRG32< 256 >
using MyBaseClass
using output_type
using state_type
using value_type
Public Types inherited from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >
using output_type
using state_type
Public Member Functions
Mrg287 () noexcept
Default empty constructor.
Mrg287 (const double seed)
Valued constructor (double).
Mrg287 (const int seed) noexcept
Valued constructor (int).
Mrg287 (const long long seed) noexcept
Valued constructor (long long).
Mrg287 (const long seed) noexcept
Valued constructor (long)
Mrg287 (const state_type &internal_state) noexcept
Valued constructor (full state).
Mrg287 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Mrg287 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Mrg287 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Mrg287 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual const output_type next () noexcept override
The internal PRNG algorithm.
virtual ~Mrg287 () noexcept=default
default destructor.
Public Member Functions inherited from BaseMRG32< 256 >
virtual void _setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseMRG32 () noexcept
Default empty constructor.
BaseMRG32 (const double seed)
Valued constructor (double).
BaseMRG32 (const int seed) noexcept
Valued constructor (int).
BaseMRG32 (const long long seed) noexcept
Valued constructor (long long).
BaseMRG32 (const long seed) noexcept
Valued constructor (long)
BaseMRG32 (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseMRG32 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseMRG32 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseMRG32 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseMRG32 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~BaseMRG32 () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >
BaseRandom () noexcept=default
default empty constructor
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (const CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
std::uint32_t getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be later passed to setstate().
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate () noexcept
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max) noexcept
Returns an array of min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of max.size() values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max) noexcept
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max) noexcept
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max) noexcept
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max) noexcept
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max) noexcept
Valued call operator (2 std::vector of scalars).
const T operator() (const T max) noexcept
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const ListSeedState< utils::SplitMix32, std::uint32_t, SIZE > &seed) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b) noexcept
Returns a random integer in range [a, b], including both end points.
const T random () noexcept
The uniform distribution on [0.0, 1.0).
const long double random () noexcept
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void seed (const double seed_)
Initalizes internal state from a double seed.
void seed (const int seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
void seed (const long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned int seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const unsigned long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void setstate (const ListSeedState< utils::SplitMix32, std::uint32_t, SIZE > &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const ListSeedState< utils::SplitMix32, std::uint32_t, SIZE > &new_internal_state, const double gauss_next) noexcept
Restores internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
In place Shuffles the specified sequence.
const ListSeedState< utils::SplitMix32, std::uint32_t, SIZE > state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform () noexcept
Uniform distribution in [0.0, 1.0).
const double uniform (const double max) noexcept
const float uniform (const float max) noexcept
const long double uniform (const long double max) noexcept
const T uniform (const U max) noexcept
Uniform distribution [0.0, max).
const T uniform (const U min, const V max) noexcept
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >
struct BaseRandom::_InternalState _internal_state
Static Public Attributes inherited from BaseMRG32< 256 >
static constexpr std::uint32_t SEED_SIZE
Static Protected Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static constexpr double BPF
static const double E
static constexpr double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static constexpr double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static constexpr double TWO_PI
Detailed Description
A fast 32-bits Multiple Recursive Generator with a long period (2.49e+86).
Multiple Recursive Generators (MRGs) use recurrence to evaluate pseudo-random numbers suites. Recurrence is of the form:
x(i) = A * SUM[ x(i-k) ] mod M
for 2 to more k different values.
MRGs offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007". It is recommended to use such pseudo-random numbers generators rather than LCG ones for serious simulation applications.
The implementation of this MRG 32-bits model is based on a Lagged Fibonacci generator (LFIB), the Marsa-LFIB4 one. Lagged Fibonacci generators LFib(m, r, k, op) use the recurrence
x(i) = (x(i-r) op (x(i-k)) mod m
where op is an operation that can be
(addition),
(substraction),
(multiplication), ^(bitwise exclusive-or).
With the + or - operation, such generators are in fact MRGs. They offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) paper.
The Marsa-LIBF4 version uses the recurrence
x(i) = (x(i-55) + x(i-119) + x(i-179) + x(i-256)) mod 2^32
and offers a period of about 2^287 - i.e. 2.49e+86 - with low computation time due to the use of a 2^32 modulo.
See Mrg1457 for a longer period MR-Generator (2^1457, i.e. 4.0e+438) and longer computation time (2^31-1 modulus calculations) but less memory space consumption (i.e. 47 integers).
See Mrg49507 for a far longer period (2^49,507, i.e. 1.2e+14,903) with low computation time too (31-bits modulus) but use of more memory space (1,597 integers).
Furthermore this class is callable:
Mrg287 rand();
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
Mrg287 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the MRGs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Mrg287 Marsa-LFIB4 256 x 4-bytes 2^287 3.40 0.8 0 0 0
Mrg1457 DX-47-3 47 x 4-bytes 2^1457 n.a. 1.4 0 0 0
Mrg49507 DX-1597-2-7 1,597 x 4-bytes 2^49507 n.a. 1.4 0 0 0
+------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Mrg287() [1/10]
Mrg287::Mrg287 () noexcept
Default empty constructor.
Empty constructor.
References BaseMRG32< 256 >::seed().
Mrg287() [2/10]
Mrg287::Mrg287 (const int seed_) noexcept
Valued constructor (int).
Valued constructor (int).
Mrg287() [3/10]
Mrg287::Mrg287 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
Mrg287() [4/10]
Mrg287::Mrg287 (const long seed_) noexcept
Valued constructor (long)
Valued constructor (long).
Mrg287() [5/10]
Mrg287::Mrg287 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
Mrg287() [6/10]
Mrg287::Mrg287 (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor (long long).
Mrg287() [7/10]
Mrg287::Mrg287 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
Mrg287() [8/10]
Mrg287::Mrg287 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (utils::UInt128).
Mrg287() [9/10]
Mrg287::Mrg287 (const double seed_)
Valued constructor (double).
Valued constructor (double).
Mrg287() [10/10]
Mrg287::Mrg287 (const state_type & internal_state) noexcept
Valued constructor (full state).
Valued constructor (full state).
~Mrg287()
virtual Mrg287::~Mrg287 () inline virtual default noexcept
default destructor.
References next().
Member Function Documentation
next()
const Mrg287::output_type Mrg287::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
Referenced by ~Mrg287().
The documentation for this class was generated from the following files:
mrg287.h
mrg287.cpp