CppRandLib - c++20: utils::UInt128 Class Reference
utils::UInt128 Class Reference
utils: UInt128 - A minimalist 128-bits integer type
128 bits integer minimalist arithmetic.
#include <uint128.h>
Public Member Functions
operator const double () const noexcept
< 64-bits float const casting operator
operator const long double () const noexcept
< 128-bits float const casting operator
template<typename IntT>
requires std::is_integral_v<IntT>
const bool operator!= (const IntT value) const noexcept
const bool operator!= (const UInt128 &other) const noexcept
const UInt128 operator* (const std::uint64_t value) const noexcept
const UInt128 operator* (const UInt128 &other) const noexcept
UInt128 & operator*= (const std::uint64_t other) noexcept
UInt128 & operator*= (const UInt128 &other) noexcept
const UInt128 operator+ (const std::uint64_t other) const noexcept
const UInt128 operator+ (const UInt128 &other) const noexcept
UInt128 & operator+= (const std::uint64_t other) noexcept
UInt128 & operator+= (const UInt128 &other) noexcept
UInt128 operator<< (const unsigned int shift) noexcept
UInt128 & operator<<= (const unsigned int shift) noexcept
template<typename IntT>
requires std::is_integral_v<IntT>
UInt128 & operator= (const IntT val) noexcept
UInt128 & operator= (const UInt128 &) noexcept=default
Default copy assignment.
UInt128 & operator= (UInt128 &&) noexcept=default
Default move assignment.
template<typename IntT>
requires std::is_integral_v<IntT>
const bool operator== (const IntT value) const noexcept
const bool operator== (const UInt128 &other) const noexcept
UInt128 operator>> (const unsigned int shift) noexcept
UInt128 & operator>>= (const unsigned int shift) noexcept
const UInt128 operator^ (const std::uint64_t value) const noexcept
const UInt128 operator^ (const UInt128 &other) const noexcept
UInt128 & operator^= (const std::uint64_t value) noexcept
UInt128 & operator^= (const UInt128 &other) noexcept
const UInt128 operator| (const std::uint64_t value) const noexcept
const UInt128 operator| (const UInt128 &other) const noexcept
UInt128 & operator|= (const std::uint64_t value) noexcept
UInt128 & operator|= (const UInt128 &other) noexcept
UInt128 () noexcept=default
Default empty constructor.
template<typename IntT>
requires std::is_integral_v<IntT>
UInt128 (const IntT val)
UInt128 (const std::uint64_t hi_, const std::uint64_t lo_)
UInt128 (const UInt128 &) noexcept=default
Default copy constructor.
UInt128 (UInt128 &&) noexcept=default
Default move constructor.
virtual ~UInt128 () noexcept=default
Default destructor.
Public Attributes
std::uint64_t hi { 0ull }
std::uint64_t lo { 0ull }
Friends
template<typename IntT>
requires std::is_integral_v<IntT>
const bool operator!= (const IntT lhs, const UInt128 &rhs) noexcept
const UInt128 operator* (const std::uint64_t lhs, const UInt128 &rhs)
const UInt128 operator+ (const std::uint64_t lhs, const UInt128 &rhs)
template<typename IntT>
requires std::is_integral_v<IntT>
const bool operator== (const IntT lhs, const UInt128 &rhs) noexcept
const UInt128 operator^ (const std::uint64_t lhs, const UInt128 &rhs)
const UInt128 operator| (const std::uint64_t lhs, const UInt128 &rhs)
Detailed Description
128 bits integer minimalist arithmetic.
Visual Studio provides no 128-bits integer arithmetic. Some of the implemented PRNGs in CppRandLib use this type of arithmetic. So, this class implements a minimalist version of 128-bits arithmetic: addition, multiplication and bit -shift, -or and -xor operators.
Constructor & Destructor Documentation
UInt128() [1/5]
utils::UInt128::UInt128 (const std::uint64_t hi_, const std::uint64_t lo_) inline
Parameters
lo_ Valued constructor (UInt128)
Referenced by operator=(), operator=(), UInt128(), UInt128(), and ~UInt128().
UInt128() [2/5]
template<typename IntT> requires std::is_integral_v<IntT> utils::UInt128::UInt128 (const IntT val) inline
Parameters
val Valued constructor (integer)
UInt128() [3/5]
utils::UInt128::UInt128 () inline default noexcept
Default empty constructor.
UInt128() [4/5]
utils::UInt128::UInt128 (const UInt128 &) inline default noexcept
Default copy constructor.
References UInt128().
UInt128() [5/5]
utils::UInt128::UInt128 (UInt128 &&) inline default noexcept
Default move constructor.
References UInt128().
~UInt128()
virtual utils::UInt128::~UInt128 () inline virtual default noexcept
Default destructor.
References UInt128().
Member Function Documentation
operator const double()
utils::UInt128::operator const double () const inline explicit noexcept
< 64-bits float const casting operator
operator const long double()
utils::UInt128::operator const long double () const inline explicit noexcept
< 128-bits float const casting operator
operator=() [1/2]
UInt128 & utils::UInt128::operator= (const UInt128 &) inline default noexcept
Default copy assignment.
References UInt128().
operator=() [2/2]
UInt128 & utils::UInt128::operator= (UInt128 &&) inline default noexcept
Default move assignment.
References UInt128().
The documentation for this class was generated from the following files:
uint128.h
uint128.cpp