CppRandLib - c++20: Cwg128_64 Class Reference
Cwg128_64 Class Reference
algos: CWG - Collatz-Weyl Generators
A 128-/64- bits Collatz-Weyl pseudorandom Generator with a short period (1.18e+21).
#include <cwg128_64.h>
Public Types
using MyBaseClass = BaseCWG<std::uint64_t, utils::UInt128, std::uint64_t, 64>
using output_type = typename MyBaseClass::output_type
using state_type = typename MyBaseClass::state_type
using value_type = typename state_type::value_type
Public Types inherited from BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >
using MyBaseClass
using output_type
using state_type
using value_type
Public Types inherited from BaseRandom< StateT, OutputT, OUTPUT_BITS >
using output_type = OutputT
using state_type = StateT
Public Member Functions
virtual void _setstate (const std::uint64_t seed_) noexcept override
Sets the internal state with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed_) noexcept override
Sets the internal state with a 128-bits integer seed.
Cwg128_64 () noexcept=default
Default empty constructor.
Cwg128_64 (const double seed)
Valued constructor (double).
Cwg128_64 (const int seed) noexcept
Valued constructor (int).
Cwg128_64 (const long long seed) noexcept
Valued constructor (long long).
Cwg128_64 (const long seed) noexcept
Valued constructor (long)
Cwg128_64 (const state_type &internal_state) noexcept
Valued constructor (full state).
Cwg128_64 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Cwg128_64 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Cwg128_64 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Cwg128_64 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual const output_type next () noexcept override
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~Cwg128_64 () noexcept=default
Default Destructor.
Public Member Functions inherited from BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >
BaseCWG () noexcept
Default empty constructor.
BaseCWG (const double seed)
Valued constructor (double).
BaseCWG (const int seed) noexcept
Valued constructor (int).
BaseCWG (const long long seed) noexcept
Valued constructor (long long).
BaseCWG (const long seed) noexcept
Valued constructor (long)
BaseCWG (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseCWG (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseCWG (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseCWG (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseCWG (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
virtual ~BaseCWG () noexcept=default
Default Destructor.
Public Member Functions inherited from BaseRandom< StateT, OutputT, OUTPUT_BITS >
BaseRandom () noexcept=default
default empty constructor
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
template<typename CountT, typename ProbaT>
requires std::is_integral_v<CountT>&& std::is_floating_point_v<ProbaT>
const CountT binomialvariate (const CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
template<typename T, const std::size_t n>
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
template<typename T>
requires std::is_integral_v<OutputT> || std::is_same_v<OutputT, utils::UInt128>
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
template<typename T>
requires std::is_integral_v<OutputT> || std::is_same_v<OutputT, utils::UInt128>
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
template<typename T, typename C>
requires std::is_arithmetic_v<C>
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
template<typename T, typename C>
requires std::is_arithmetic_v<C>
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
OutputT getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be later passed to setstate().
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
template<typename T, const std::size_t n>
requires std::is_floating_point_v<T> && (n != 0)
std::array< T, n > n_evaluate () noexcept
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
template<typename T, const std::size_t m, typename U = T, const std::size_t n = m>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && (m != 0) && (n != 0)
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
template<typename T, const std::size_t m, typename U = T, const std::size_t n = m, typename V = U, const std::size_t p = n>
requires std::is_arithmetic_v<T>&& std::is_arithmetic_v<U>&& std::is_arithmetic_v<V> && (n != 0) && (m != 0) && (p != 0)
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max) noexcept
Returns an array of min(m, n, p) values in range [min[i]; max[i]).
template<typename T>
requires std::is_floating_point_v<T>
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
template<typename T, typename U = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U>
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
template<typename T, typename U = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U>
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of max.size() values in range [0; max[i]).
template<typename T, typename U = T, typename V = U>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && std::is_arithmetic_v<V>
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
template<typename T, const std::size_t n, typename U = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && (n != 0)
std::array< T, n > n_evaluate (const U max) noexcept
Returns an array of n values that are uniformly contained within range [0, max).
template<typename T, const std::size_t n, typename U = T, typename V = U>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && std::is_arithmetic_v<V> && (n != 0)
std::array< T, n > n_evaluate (const U min, const V max) noexcept
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
template<typename T = long double>
const T operator() () noexcept
Empty Call operator.
template<typename T, const std::size_t n>
requires std::is_arithmetic_v<T> && (n != 0)
std::array< T, n > operator() (const std::array< T, n > &max) noexcept
Valued call operator (1 std::array of scalars).
template<typename T, const std::size_t n>
requires std::is_arithmetic_v<T> && (n != 0)
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max) noexcept
Valued call operator (2 std::array of scalars).
template<typename T>
requires std::is_arithmetic_v<T>
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
template<typename T>
requires std::is_arithmetic_v<T>
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max) noexcept
Valued call operator (2 std::vector of scalars).
template<typename T = OutputT>
requires std::is_arithmetic_v<T>
const T operator() (const T max) noexcept
Valued call operator (1 scalar).
template<typename T = OutputT>
requires std::is_arithmetic_v<T>
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
template<typename T>
requires std::is_arithmetic_v<T>
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const StateT &seed) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
template<typename T>
requires std::is_integral_v<T>
const T randint (const T a, const T b) noexcept
Returns a random integer in range [a, b], including both end points.
template<typename T = double>
requires std::is_floating_point_v<T>
const T random () noexcept
The uniform distribution on [0.0, 1.0).
template<>
const long double random () noexcept
template<typename T, typename S = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<S>
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
template<typename T, const std::size_t k, const std::size_t n>
requires (k != 0)
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
template<typename T, typename C, const std::size_t k, const std::size_t n>
requires std::is_integral_v<C> && (k != 0)
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
template<typename T>
requires std::is_integral_v<OutputT> || std::is_same_v<OutputT, utils::UInt128>
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
template<typename T, typename C>
requires std::is_integral_v<C>
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void seed (const double seed_)
Initalizes internal state from a double seed.
void seed (const int seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
void seed (const long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned int seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const unsigned long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void setstate (const StateT &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const StateT &new_internal_state, const double gauss_next) noexcept
Restores internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
template<typename ContainerType>
requires utils::is_indexable_v<ContainerType>
void shuffle (ContainerType &seq)
In place Shuffles the specified sequence.
const StateT state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
template<typename T = double>
requires std::is_floating_point_v<T>
const T uniform () noexcept
Uniform distribution in [0.0, 1.0).
template<>
const double uniform (const double max) noexcept
template<>
const float uniform (const float max) noexcept
template<>
const long double uniform (const long double max) noexcept
template<typename T = double, typename U = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U>
const T uniform (const U max) noexcept
Uniform distribution [0.0, max).
template<typename T, typename U = T, typename V = U>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && std::is_arithmetic_v<V>
const T uniform (const U min, const V max) noexcept
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< StateT, OutputT, OUTPUT_BITS >
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< StateT, OutputT, OUTPUT_BITS >
static constexpr std::uint64_t _MODULO { (((1ull << ((OUTPUT_BITS > 64 ? 64 : OUTPUT_BITS) - 1)) - 1) << 1) | 0x1 }
static constexpr double _NORMALIZE { double(_NORMALIZE_LD) }
static constexpr long double _NORMALIZE_LD
static constexpr double BPF { 53 }
static const double E
static constexpr double GAUSS_NULL { -1.0 }
static const double LOG4
static const double NV_MAGICCONST
static constexpr double PI { 3.141'592'653'589'793'238'46 }
static const double RECIP_BPF
static const double SG_MAGICCONST
static constexpr double TWO_PI { 2.0 * PI }
Detailed Description
A 128-/64- bits Collatz-Weyl pseudorandom Generator with a short period (1.18e+21).
Pseudo-random numbers generator - Collatz-Weyl pseudorandom Generator dedicated to 128-bits calculations and 64-bits output values with small period (min 2^71, i.e. 2.36e+21) but short computation time. All CWG algorithms offer multi streams features, by simply using different initial settings for control value 's' - see below.
This CWG model evaluates pseudo-random numbers suites x(i) as a simple mathematical function of
x(i+1) = (x(i) | 1) * ((a += x(i)) >> 1) ^ (weyl += s)
and returns as the output value the xored shifted: a >> 48 ^ x(i+1)
where a, weyl and s are the control values and x the internal state of the PRNG. 's' must be initally odd. 'a', 'weyl' and initial state 'x' may be initialized each with any 64-bits value.
See Cwg64 for a minimum 2^70 (i.e. about 1.18e+21) period CW-Generator with very low computation time, medium period, 64- bits output values and very good randomness characteristics.
See Cwg128_64 for a minimum 2^135 (i.e. about 4.36e+40) period CW-generator with very low computation time, medium period, 128-bits output values and very good randomness characteristics.
Furthermore this class is callable:
Cwg128_64 rand();
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
Cwg128_64 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the CWGs that have been implemented in CppRandLib, as presented in paper [8] - see file README.md.
+---------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class [8] generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Cwg64 CWG64 8 x 4-bytes >= 2^70 n.a. n.a. 0 0 0
Cwg128_64 CWG128_64 10 x 4-bytes >= 2^71 n.a. n.a. 0 0 0
Cwg128 CWG128 16 x 4-bytes >= 2^135 n.a. n.a. 0 0 0
+---------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Cwg128_64() [1/10]
Cwg128_64::Cwg128_64 () inline default noexcept
Default empty constructor.
References Cwg128_64(), and seed().
Referenced by Cwg128_64(), and ~Cwg128_64().
Cwg128_64() [2/10]
Cwg128_64::Cwg128_64 (const int seed) noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
Cwg128_64() [3/10]
Cwg128_64::Cwg128_64 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
Cwg128_64() [4/10]
Cwg128_64::Cwg128_64 (const long seed) noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
Cwg128_64() [5/10]
Cwg128_64::Cwg128_64 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
Cwg128_64() [6/10]
Cwg128_64::Cwg128_64 (const long long seed) noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
Cwg128_64() [7/10]
Cwg128_64::Cwg128_64 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
Cwg128_64() [8/10]
Cwg128_64::Cwg128_64 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References seed().
Cwg128_64() [9/10]
Cwg128_64::Cwg128_64 (const double seed)
Valued constructor (double).
Valued constructor (double).
References seed().
Cwg128_64() [10/10]
Cwg128_64::Cwg128_64 (const state_type & internal_state) noexcept
Valued constructor (full state).
Valued constructor (full state).
~Cwg128_64()
virtual Cwg128_64::~Cwg128_64 () virtual default noexcept
Default Destructor.
References _setstate(), Cwg128_64(), next(), and seed().
Member Function Documentation
_setstate() [1/2]
void Cwg128_64::_setstate (const std::uint64_t seed_) override virtual noexcept
Sets the internal state with a 64-bits integer seed.
Sets the internal state with a 64-bits integer seed.
Reimplemented from BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >.
References BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >::_setstate().
Referenced by ~Cwg128_64().
_setstate() [2/2]
void Cwg128_64::_setstate (const utils::UInt128 & seed_) override virtual noexcept
Sets the internal state with a 128-bits integer seed.
Sets the internal state with a 128-bits integer seed.
Reimplemented from BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >.
next()
const Cwg128_64::output_type Cwg128_64::next () override virtual noexcept
The internal PRNG algorithm.
Reimplemented from BaseRandom< StateT, OutputT, OUTPUT_BITS >.
Referenced by ~Cwg128_64().
seed() [1/9]
void Cwg128_64::seed () virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Reimplemented from BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >.
References BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >::seed().
Referenced by Cwg128_64(), Cwg128_64(), Cwg128_64(), Cwg128_64(), Cwg128_64(), Cwg128_64(), Cwg128_64(), Cwg128_64(), Cwg128_64(), seed(), seed(), seed(), seed(), seed(), and ~Cwg128_64().
seed() [2/9]
void Cwg128_64::seed (const double seed_)
Initializes internal state (double).
Initializes internal state (double).
References BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >::seed().
seed() [3/9]
void Cwg128_64::seed (const int seed_) noexcept
Initializes internal state (int).
Initializes internal state (int).
References seed().
seed() [4/9]
void Cwg128_64::seed (const long long seed_) noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References seed().
seed() [5/9]
void Cwg128_64::seed (const long seed_) noexcept
Initializes internal state (long)
Initializes internal state (long).
References seed().
seed() [6/9]
void Cwg128_64::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References seed().
seed() [7/9]
void Cwg128_64::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
References BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >::seed().
seed() [8/9]
void Cwg128_64::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References seed().
seed() [9/9]
void Cwg128_64::seed (const utils::UInt128 & seed_) virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >.
References BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >::seed().
The documentation for this class was generated from the following files:
cwg128_64.h
cwg128_64.cpp