CppRandLib - c++20: Squares64 Class Reference
Squares64 Class Reference
algos: Squares - Squares counter-based pseudorandom generators
Squares pseudo-random Generators dedicated to 64-bits calculations and 64-bits output values with small period (min 2^64, i.e. 1.84e+19).
#include <squares64.h>
Public Types
using MyBaseClass = BaseSquares<std::uint64_t>
Public Types inherited from BaseSquares< std::uint64_t >
using MyBaseClass
using output_type
using state_type
using value_type
Public Types inherited from BaseRandom< StateT, OutputT, OUTPUT_BITS >
using output_type = OutputT
using state_type = StateT
Public Member Functions
virtual const output_type next () noexcept override
The internal PRNG algorithm.
Squares64 () noexcept
Default empty constructor.
Squares64 (const double seed)
Valued constructor (double).
Squares64 (const int seed) noexcept
Valued constructor (int).
Squares64 (const long long seed) noexcept
Valued constructor (long long).
Squares64 (const long seed) noexcept
Valued constructor (long)
Squares64 (const state_type &internal_state) noexcept
Valued constructor (full state).
Squares64 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Squares64 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Squares64 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Squares64 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual ~Squares64 () noexcept=default
default destructor.
Public Member Functions inherited from BaseSquares< std::uint64_t >
virtual void _setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseSquares () noexcept
Default empty constructor.
BaseSquares (const double seed)
Valued constructor (double).
BaseSquares (const int seed) noexcept
Valued constructor (int).
BaseSquares (const long long seed) noexcept
Valued constructor (long long).
BaseSquares (const long seed) noexcept
Valued constructor (long)
BaseSquares (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseSquares (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseSquares (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseSquares (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseSquares (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~BaseSquares () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< StateT, OutputT, OUTPUT_BITS >
BaseRandom () noexcept=default
default empty constructor
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
template<typename CountT, typename ProbaT>
requires std::is_integral_v<CountT>&& std::is_floating_point_v<ProbaT>
const CountT binomialvariate (const CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
template<typename T, const std::size_t n>
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
template<typename T>
requires std::is_integral_v<OutputT> || std::is_same_v<OutputT, utils::UInt128>
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
template<typename T>
requires std::is_integral_v<OutputT> || std::is_same_v<OutputT, utils::UInt128>
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
template<typename T, typename C>
requires std::is_arithmetic_v<C>
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
template<typename T, typename C>
requires std::is_arithmetic_v<C>
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
OutputT getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be later passed to setstate().
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
template<typename T, const std::size_t n>
requires std::is_floating_point_v<T> && (n != 0)
std::array< T, n > n_evaluate () noexcept
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
template<typename T, const std::size_t m, typename U = T, const std::size_t n = m>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && (m != 0) && (n != 0)
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
template<typename T, const std::size_t m, typename U = T, const std::size_t n = m, typename V = U, const std::size_t p = n>
requires std::is_arithmetic_v<T>&& std::is_arithmetic_v<U>&& std::is_arithmetic_v<V> && (n != 0) && (m != 0) && (p != 0)
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max) noexcept
Returns an array of min(m, n, p) values in range [min[i]; max[i]).
template<typename T>
requires std::is_floating_point_v<T>
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
template<typename T, typename U = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U>
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
template<typename T, typename U = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U>
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of max.size() values in range [0; max[i]).
template<typename T, typename U = T, typename V = U>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && std::is_arithmetic_v<V>
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
template<typename T, const std::size_t n, typename U = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && (n != 0)
std::array< T, n > n_evaluate (const U max) noexcept
Returns an array of n values that are uniformly contained within range [0, max).
template<typename T, const std::size_t n, typename U = T, typename V = U>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && std::is_arithmetic_v<V> && (n != 0)
std::array< T, n > n_evaluate (const U min, const V max) noexcept
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
template<typename T = long double>
const T operator() () noexcept
Empty Call operator.
template<typename T, const std::size_t n>
requires std::is_arithmetic_v<T> && (n != 0)
std::array< T, n > operator() (const std::array< T, n > &max) noexcept
Valued call operator (1 std::array of scalars).
template<typename T, const std::size_t n>
requires std::is_arithmetic_v<T> && (n != 0)
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max) noexcept
Valued call operator (2 std::array of scalars).
template<typename T>
requires std::is_arithmetic_v<T>
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
template<typename T>
requires std::is_arithmetic_v<T>
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max) noexcept
Valued call operator (2 std::vector of scalars).
template<typename T = OutputT>
requires std::is_arithmetic_v<T>
const T operator() (const T max) noexcept
Valued call operator (1 scalar).
template<typename T = OutputT>
requires std::is_arithmetic_v<T>
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
template<typename T>
requires std::is_arithmetic_v<T>
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const StateT &seed) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
template<typename T>
requires std::is_integral_v<T>
const T randint (const T a, const T b) noexcept
Returns a random integer in range [a, b], including both end points.
template<typename T = double>
requires std::is_floating_point_v<T>
const T random () noexcept
The uniform distribution on [0.0, 1.0).
template<>
const long double random () noexcept
template<typename T, typename S = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<S>
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
template<typename T, const std::size_t k, const std::size_t n>
requires (k != 0)
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
template<typename T, typename C, const std::size_t k, const std::size_t n>
requires std::is_integral_v<C> && (k != 0)
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
template<typename T>
requires std::is_integral_v<OutputT> || std::is_same_v<OutputT, utils::UInt128>
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
template<typename T, typename C>
requires std::is_integral_v<C>
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void seed (const double seed_)
Initalizes internal state from a double seed.
void seed (const int seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
void seed (const long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned int seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const unsigned long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void setstate (const StateT &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const StateT &new_internal_state, const double gauss_next) noexcept
Restores internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
template<typename ContainerType>
requires utils::is_indexable_v<ContainerType>
void shuffle (ContainerType &seq)
In place Shuffles the specified sequence.
const StateT state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
template<typename T = double>
requires std::is_floating_point_v<T>
const T uniform () noexcept
Uniform distribution in [0.0, 1.0).
template<>
const double uniform (const double max) noexcept
template<>
const float uniform (const float max) noexcept
template<>
const long double uniform (const long double max) noexcept
template<typename T = double, typename U = T>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U>
const T uniform (const U max) noexcept
Uniform distribution [0.0, max).
template<typename T, typename U = T, typename V = U>
requires std::is_arithmetic_v<T> && std::is_arithmetic_v<U> && std::is_arithmetic_v<V>
const T uniform (const U min, const V max) noexcept
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< StateT, OutputT, OUTPUT_BITS >
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< StateT, OutputT, OUTPUT_BITS >
static constexpr std::uint64_t _MODULO { (((1ull << ((OUTPUT_BITS > 64 ? 64 : OUTPUT_BITS) - 1)) - 1) << 1) | 0x1 }
static constexpr double _NORMALIZE { double(_NORMALIZE_LD) }
static constexpr long double _NORMALIZE_LD
static constexpr double BPF { 53 }
static const double E
static constexpr double GAUSS_NULL { -1.0 }
static const double LOG4
static const double NV_MAGICCONST
static constexpr double PI { 3.141'592'653'589'793'238'46 }
static const double RECIP_BPF
static const double SG_MAGICCONST
static constexpr double TWO_PI { 2.0 * PI }
Detailed Description
Squares pseudo-random Generators dedicated to 64-bits calculations and 64-bits output values with small period (min 2^64, i.e. 1.84e+19).
This Squares models is based on a five rounds of squaring and exchanging of upper and lower bits of the successive combinations. Output values are provided on 32-bits. Caution: this 64-bits output values version should not pass the birthday test, which is a randmoness issue, while this is not mentionned in the original paper (see [9] in file README.md).
See Squares32 for a 2^64 (i.e. about 1.84e+19) period PRNG with low computation time, medium period, 32-bits output values and very good randomness characteristics.
Please notice that this class and all its inheriting sub-classes are callable. Example:
Squares64 rand{};
std::cout << rand() << std::endl;     // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;    // prints a uniform pseudo-random value within [0.0, b)
Please notice that for simulating the roll of a dice you may use any of:
Squares64 diceRoll{};
std::cout << int(diceRoll(1, 7))    << std::endl; // prints a uniform roll within range {1, ..., 6}
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the WELL algorithms that have been implemented in CppRandLib, as provided in paper "TestU01, ..." and when available.
+-----------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class [9] generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Squares32 squares32 4 x 4-bytes 2^64 n.a. n.a. 0 0 0
Squares64 squares64 4 x 4-bytes 2^64 n.a. n.a. 0 0 0
+-----------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Squares64() [1/10]
Squares64::Squares64 () noexcept
Default empty constructor.
Empty constructor.
References BaseSquares< std::uint64_t >::seed().
Squares64() [2/10]
Squares64::Squares64 (const int seed_) noexcept
Valued constructor (int).
Valued constructor.
References BaseSquares< std::uint64_t >::seed().
Squares64() [3/10]
Squares64::Squares64 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor.
References BaseSquares< std::uint64_t >::seed().
Squares64() [4/10]
Squares64::Squares64 (const long seed_) noexcept
Valued constructor (long)
Valued constructor.
References BaseSquares< std::uint64_t >::seed().
Squares64() [5/10]
Squares64::Squares64 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor.
References BaseSquares< std::uint64_t >::seed().
Squares64() [6/10]
Squares64::Squares64 (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor.
References BaseSquares< std::uint64_t >::seed().
Squares64() [7/10]
Squares64::Squares64 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor.
References BaseSquares< std::uint64_t >::seed().
Squares64() [8/10]
Squares64::Squares64 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References BaseSquares< std::uint64_t >::seed().
Squares64() [9/10]
Squares64::Squares64 (const double seed_)
Valued constructor (double).
Valued constructor.
References BaseSquares< std::uint64_t >::seed().
Squares64() [10/10]
Squares64::Squares64 (const state_type & internal_state) noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate().
~Squares64()
virtual Squares64::~Squares64 () inline virtual default noexcept
default destructor.
References next().
Member Function Documentation
next()
const Squares64::output_type Squares64::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< StateT, OutputT, OUTPUT_BITS >.
Referenced by ~Squares64().
The documentation for this class was generated from the following files:
squares64.h
squares64.cpp