CppRandLib - c++20: Melg19937 Class Reference
Melg19937 Class Reference
Maximally Equidistributed Long-period Linear Generators (MELG) algorithm
A 64-bits Maximally Equidistributed Long-period Linear Generator with a long period (4.32e+6,001).
#include <melg19937.h>
Public Types
using MyBaseClass = BaseMELG<312>
using output_type = MyBaseClass::output_type
using state_type = MyBaseClass::state_type
using value_type = typename state_type::value_type
Public Types inherited from BaseMELG< 312 >
using MyBaseClass
using output_type
using state_type
using value_type
Public Types inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >
using output_type
using state_type
Public Member Functions
Melg19937 () noexcept
Default empty constructor.
Melg19937 (const double seed)
Valued constructor (double).
Melg19937 (const int seed) noexcept
Valued constructor (int).
Melg19937 (const long long seed) noexcept
Valued constructor (long long).
Melg19937 (const long seed) noexcept
Valued constructor (long)
Melg19937 (const state_type &internal_state) noexcept
Valued constructor (full state).
Melg19937 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Melg19937 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Melg19937 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Melg19937 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual const output_type next () noexcept override
The internal PRNG algorithm.
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~Melg19937 () noexcept=default
default destructor.
Public Member Functions inherited from BaseMELG< 312 >
virtual void _setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseMELG () noexcept
Default empty constructor.
BaseMELG (const double seed)
Valued constructor (double).
BaseMELG (const int seed) noexcept
Valued constructor (int).
BaseMELG (const long long seed) noexcept
Valued constructor (long long).
BaseMELG (const long seed) noexcept
Valued constructor (long)
BaseMELG (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseMELG (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseMELG (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseMELG (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseMELG (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
virtual ~BaseMELG () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >
BaseRandom () noexcept=default
default empty constructor
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (const CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
std::uint64_t getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be later passed to setstate().
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate () noexcept
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max) noexcept
Returns an array of min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of max.size() values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max) noexcept
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max) noexcept
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max) noexcept
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max) noexcept
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max) noexcept
Valued call operator (2 std::vector of scalars).
const T operator() (const T max) noexcept
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &seed) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b) noexcept
Returns a random integer in range [a, b], including both end points.
const T random () noexcept
The uniform distribution on [0.0, 1.0).
const long double random () noexcept
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void seed (const double seed_)
Initalizes internal state from a double seed.
void seed (const int seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
void seed (const long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned int seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const unsigned long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void setstate (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > &new_internal_state, const double gauss_next) noexcept
Restores internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
In place Shuffles the specified sequence.
const ListSeedState< utils::SplitMix64, std::uint64_t, SIZE > state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform () noexcept
Uniform distribution in [0.0, 1.0).
const double uniform (const double max) noexcept
const float uniform (const float max) noexcept
const long double uniform (const long double max) noexcept
const T uniform (const U max) noexcept
Uniform distribution [0.0, max).
const T uniform (const U min, const V max) noexcept
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static constexpr double BPF
static const double E
static constexpr double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static constexpr double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static constexpr double TWO_PI
Detailed Description
A 64-bits Maximally Equidistributed Long-period Linear Generator with a long period (4.32e+6,001).
Maximally Equidistributed Long-period Linear Generators (MELG) use linear recurrence based on state transitions with double feedbacks and linear output transformations with several memory references. See reference [11] in README.md.
MELGs offer large to very large periods with best known results in the evaluation of their randomness. They ensure a maximally equidistributed generation of pseudo random numbers. They pass all TestU01 tests and newer ones but are the slowest to compute ones in the base of PRNGs that have been implemented in CppRandLib.
See Melg607 for a large period MELG-Generator (2^607, i.e. 5.31e+182) with medium computation time and the equivalent of 21 32-bits integers memory little consumption. This is the shortest period version proposed in paper [11].
See Melg44497 for a very large period (2^44,497, i.e. 8.55e+13,395) with similar computation time but use of even more memory space (equivalent of 1,393 32-bits integers). This is the longest period version proposed in paper [11].
Furthermore this class is callable:
Melg19937 rand();
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
Melg19937 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the MELGs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Melg607 melg607-64 21 x 4-bytes 2^607 n.a. n.a. n.a. n.a. n.a.
Melg19937 melg19937-64 625 x 4-bytes 2^19937 n.a. 4.21 0 0 0
Melg44497 melg44497-64 1,393 x 4-bytes 2^44497 n.a. n.a. n.a. n.a. n.a.
+------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Melg19937() [1/10]
Melg19937::Melg19937 () noexcept
Default empty constructor.
Empty constructor.
References seed().
Melg19937() [2/10]
Melg19937::Melg19937 (const int seed_) noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
Melg19937() [3/10]
Melg19937::Melg19937 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
Melg19937() [4/10]
Melg19937::Melg19937 (const long seed_) noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
Melg19937() [5/10]
Melg19937::Melg19937 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
Melg19937() [6/10]
Melg19937::Melg19937 (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
Melg19937() [7/10]
Melg19937::Melg19937 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
Melg19937() [8/10]
Melg19937::Melg19937 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (utils::UInt128).
References seed().
Melg19937() [9/10]
Melg19937::Melg19937 (const double seed_)
Valued constructor (double).
Valued constructor (double).
References seed().
Melg19937() [10/10]
Melg19937::Melg19937 (const state_type & internal_state) noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::setstate().
~Melg19937()
virtual Melg19937::~Melg19937 () inline virtual default noexcept
default destructor.
References next(), and seed().
Member Function Documentation
next()
const Melg19937::output_type Melg19937::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Referenced by ~Melg19937().
seed() [1/9]
void Melg19937::seed () virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Reimplemented from BaseMELG< 312 >.
References BaseMELG< 312 >::seed().
Referenced by Melg19937(), Melg19937(), Melg19937(), Melg19937(), Melg19937(), Melg19937(), Melg19937(), Melg19937(), Melg19937(), seed(), seed(), seed(), seed(), seed(), and ~Melg19937().
seed() [2/9]
void Melg19937::seed (const double seed_)
Initializes internal state (double).
Initializes internal state (double).
References BaseMELG< 312 >::seed().
seed() [3/9]
void Melg19937::seed (const int seed_) noexcept
Initializes internal state (int).
Initializes internal state (int).
References seed().
seed() [4/9]
void Melg19937::seed (const long long seed_) noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References seed().
seed() [5/9]
void Melg19937::seed (const long seed_) noexcept
Initializes internal state (long)
Initializes internal state (long).
References seed().
seed() [6/9]
void Melg19937::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References seed().
seed() [7/9]
void Melg19937::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
References BaseMELG< 312 >::seed().
seed() [8/9]
void Melg19937::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References seed().
seed() [9/9]
void Melg19937::seed (const utils::UInt128 & seed_) virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseMELG< 312 >.
References BaseMELG< 312 >::seed().
The documentation for this class was generated from the following files:
melg19937.h
melg19937.cpp