CppRandLib - c++20: utils::SplitMix63 Class Reference
utils::SplitMix63 Class Reference
utils: Splittable numbers generators
The splitting and mixing algorithm used to initialize 63-bits internal states of PRNGs.
#include <splitmix.h>
Public Member Functions
const std::uint64_t operator() () noexcept
Evaluates next pseudorandom value.
SplitMix63 () noexcept
Empty constructor, uses the shuffled current time to initialize the internal state.
SplitMix63 (const double seed)
Valued constructor - double.
SplitMix63 (const int seed) noexcept
Valued constructor - 32-bits integer.
SplitMix63 (const long long seed) noexcept
Valued constructor - 64-bits integer.
SplitMix63 (const long seed) noexcept
Valued constructor - 32-bits integer.
SplitMix63 (const unsigned int seed) noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix63 (const unsigned long long seed) noexcept
Valued constructor - 64-bits unsigned integer.
SplitMix63 (const unsigned long seed) noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix63 (const utils::UInt128 &seed) noexcept
Valued constructor - 128-bits unsigned integer.
Public Member Functions inherited from utils::SplitMix64
const std::uint64_t operator() () noexcept
Evaluates next pseudorandom value.
SplitMix64 () noexcept
Empty constructor, uses current time to initialize the internal state.
SplitMix64 (const int seed) noexcept
Valued constructor - 32-bits integer.
SplitMix64 (const long long seed) noexcept
Valued constructor - 64-bits integer.
SplitMix64 (const long seed) noexcept
Valued constructor - 32-bits integer.
SplitMix64 (const unsigned int seed) noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix64 (const unsigned long long seed) noexcept
Valued constructor - 64-bits unsigned integer.
SplitMix64 (const unsigned long seed) noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix64 (const utils::UInt128 &seed) noexcept
Valued constructor - 128-bits unsigned integer.
SplitMix64 (double seed)
Valued constructor - double in range [0.0, 1.0).
Detailed Description
The splitting and mixing algorithm used to initialize 63-bits internal states of PRNGs.
This method is used to split and mix bits of 64-bits integers. It is internally used in CppRandLib to initialize internal state of PRNGs. It implements the 64-bits version of the Fast Splittable Pseudorandom Number Generators proposed by Steele Jr, Guy L., Doug Lea, and Christine H. Flood in "Fast splittable pseudorandom number generators.", in ACM SIGPLAN Notices 49.10 (2014): pp. 453-472.
It uses the Gamma method inited by Sebastiano Vigna (vigna.nosp@m.@acm.nosp@m..org) in 2015, provided under the Creative Commons license and modified under the same license by D. Lemire by Aug. 2017. (see https://github.com/lemire/testingRNG/blob/master/source/splitmix64.h).
It SHOULD NOT BE USED as a generic PRNG due to is randomness big limitations.
Constructor & Destructor Documentation
SplitMix63() [1/9]
utils::SplitMix63::SplitMix63 () inline noexcept
Empty constructor, uses the shuffled current time to initialize the internal state.
References utils::SplitMix64::SplitMix64().
SplitMix63() [2/9]
utils::SplitMix63::SplitMix63 (const int seed) inline noexcept
Valued constructor - 32-bits integer.
SplitMix63() [3/9]
utils::SplitMix63::SplitMix63 (const unsigned int seed) inline noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix63() [4/9]
utils::SplitMix63::SplitMix63 (const long seed) inline noexcept
Valued constructor - 32-bits integer.
SplitMix63() [5/9]
utils::SplitMix63::SplitMix63 (const unsigned long seed) inline noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix63() [6/9]
utils::SplitMix63::SplitMix63 (const long long seed) inline noexcept
Valued constructor - 64-bits integer.
SplitMix63() [7/9]
utils::SplitMix63::SplitMix63 (const unsigned long long seed) inline noexcept
Valued constructor - 64-bits unsigned integer.
SplitMix63() [8/9]
utils::SplitMix63::SplitMix63 (const utils::UInt128 & seed) inline noexcept
Valued constructor - 128-bits unsigned integer.
SplitMix63() [9/9]
utils::SplitMix63::SplitMix63 (const double seed) inline
Valued constructor - double.
References utils::SplitMix64::SplitMix64().
Member Function Documentation
operator()()
const std::uint64_t utils::SplitMix63::operator() () inline noexcept
Evaluates next pseudorandom value.
References utils::SplitMix64::operator()().
The documentation for this class was generated from the following file:
splitmix.h