CppRandLib - c++20: Well512a Class Reference
Well512a Class Reference
algos: WELL - Well-Equidistributed Long-period Linear generators
A fast 32-bits Well-Equidistributed Long-period Linear generator with a large period (2^512, i.e. 1.34e+154).
#include <well512a.h>
Public Types
using MyBaseClass = BaseWell<16>
Public Types inherited from BaseWell< 16 >
using MyBaseClass
using output_type
using state_type
using value_type
Public Types inherited from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >
using output_type
using state_type
Public Member Functions
virtual const output_type next () noexcept override
The internal PRNG algorithm.
Well512a () noexcept
Default empty constructor.
Well512a (const double seed)
Valued constructor (double).
Well512a (const int seed) noexcept
Valued constructor (int).
Well512a (const long long seed) noexcept
Valued constructor (long long).
Well512a (const long seed) noexcept
Valued constructor (long)
Well512a (const state_type &internal_state) noexcept
Valued constructor (full state).
Well512a (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Well512a (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Well512a (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Well512a (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual ~Well512a () noexcept=default
default destructor.
Public Member Functions inherited from BaseWell< 16 >
virtual void _setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseWell () noexcept
Default empty constructor.
BaseWell (const double seed)
Valued constructor (double).
BaseWell (const int seed) noexcept
Valued constructor (int).
BaseWell (const long long seed) noexcept
Valued constructor (long long).
BaseWell (const long seed) noexcept
Valued constructor (long)
BaseWell (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseWell (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseWell (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseWell (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseWell (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void seed () noexcept
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual ~BaseWell () noexcept=default
default destructor.
Public Member Functions inherited from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >
BaseRandom () noexcept=default
default empty constructor
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (const CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
std::uint32_t getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be later passed to setstate().
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate () noexcept
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max) noexcept
Returns an array of min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of max.size() values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max) noexcept
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max) noexcept
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max) noexcept
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max) noexcept
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max) noexcept
Valued call operator (2 std::vector of scalars).
const T operator() (const T max) noexcept
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const ListSeedState< utils::SplitMix32, std::uint32_t, SIZE > &seed) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b) noexcept
Returns a random integer in range [a, b], including both end points.
const T random () noexcept
The uniform distribution on [0.0, 1.0).
const long double random () noexcept
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void seed (const double seed_)
Initalizes internal state from a double seed.
void seed (const int seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
void seed (const long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned int seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void seed (const unsigned long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
void seed (const unsigned long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
void setstate (const ListSeedState< utils::SplitMix32, std::uint32_t, SIZE > &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const ListSeedState< utils::SplitMix32, std::uint32_t, SIZE > &new_internal_state, const double gauss_next) noexcept
Restores internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
In place Shuffles the specified sequence.
const ListSeedState< utils::SplitMix32, std::uint32_t, SIZE > state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform () noexcept
Uniform distribution in [0.0, 1.0).
const double uniform (const double max) noexcept
const float uniform (const float max) noexcept
const long double uniform (const long double max) noexcept
const T uniform (const U max) noexcept
Uniform distribution [0.0, max).
const T uniform (const U min, const V max) noexcept
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Additional Inherited Members
Public Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >
struct BaseRandom::_InternalState _internal_state
Static Public Attributes inherited from BaseWell< 16 >
static constexpr std::uint32_t STATE_SIZE
Static Protected Member Functions inherited from BaseWell< 16 >
static value_type _d (const value_type s) noexcept
static value_type _M0 (const value_type x=0) noexcept
static value_type _M1 (const value_type x) noexcept
static value_type _M2_neg (const value_type x, const value_type t) noexcept
static value_type _M2_pos (const value_type x, const value_type t) noexcept
static value_type _M3_neg (const value_type x, const value_type t) noexcept
static value_type _M3_pos (const value_type x, const value_type t) noexcept
static value_type _M4 (const value_type x, const value_type a) noexcept
static value_type _M5_neg (const value_type x, const value_type t, const value_type a) noexcept
static value_type _M5_pos (const value_type x, const value_type t, const value_type a) noexcept
static value_type _M6 (const value_type x, const value_type q, const value_type t, const value_type s, const value_type a) noexcept
static value_type _tempering (const value_type x, const value_type b, const value_type c) noexcept
Static Protected Attributes inherited from BaseWell< 16 >
static constexpr value_type _a1
static constexpr value_type _a2
static constexpr value_type _a3
static constexpr value_type _a4
static constexpr value_type _a5
static constexpr value_type _a6
static constexpr value_type _a7
Static Protected Attributes inherited from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static constexpr double BPF
static const double E
static constexpr double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static constexpr double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static constexpr double TWO_PI
Detailed Description
A fast 32-bits Well-Equidistributed Long-period Linear generator with a large period (2^512, i.e. 1.34e+154).
Well-Equidistributed Long-period Linear Generators (WELL) use linear recurrence based on primitive characteristic polynomials associated with left- and right- shifts and xor operations to fastly evaluate pseudo-random numbers suites.
WELLs offer large to very large periods with best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007". It is recommended to use such pseudo-random numbers generators rather than LCG ones for serious simulation applications. Furthermore, WELLs have proven their great ability to very fastly escape from zeroland.
Notice: the algorithm in its Well512a version has been coded here as a direct implementation of its description in the initial paper: "Improved Long-Period Generators Based on Linear Recurrences Modulo 2", Franois PANNETON and Pierre L'ECUYER (Universit de Montral) and Makoto MATSUMOTO (Hiroshima University), in ACM Transactions on Mathematical Software, Vol. 32, No. 1, March 2006, Pages 1-16. (see https://www.iro.umontreal.ca/~lecuyer/myftp/papers/wellrng.pdf). As such, only minimalist optimization has been coded, with the aim at easing the verification of its proper implementation.
See Well1024a for a longer period WELL-Generator (2^1,024, i.e. 1.80e+308), same computation time and 32 integers memory consumption.
See Well199937c for a far longer period (2^19,937, i.e. 4.32e+6,001) with similar computation time but use of more memory space (624 integers).
See Well44497b for a very large period (2^44,497, i.e. 15.1e+13,466) with similar computation time but use of even more memory space (1,391 integers).
Furthermore this class is callable:
Well512a rand();
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
Well512a diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the WELL algorithms that have been implemented in CppRandLib, as provided in paper "TestU01, ..." and when available.
+------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
Well512a not available 16 x 4-bytes 2^512 n.a. n.a. n.a. n.a. n.a.
Well1024a WELL1024a 32 x 4-bytes 2^1024 4.0 1.1 0 4 4
Well19937c (1) WELL19937a 624 x 4-bytes 2^19937 4.3 1.3 0 2 2
Well44497b not available 1,391 x 4-bytes 2^44497 n.a. n.a. n.a. n.a. n.a.
+------------------------------------------------------------------------------------------------------------------------------------------------—+
(1) The Well19937c generator provided with library CppRandLib implements the Well19937a algorithm augmented with an associated tempering algorithm. This should very slightly slow down its CPU performance while enhancing its pseudo-randomness quality, as measured by TestU01.
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Well512a() [1/10]
Well512a::Well512a () noexcept
Default empty constructor.
Empty constructor.
References BaseWell< 16 >::seed().
Well512a() [2/10]
Well512a::Well512a (const int seed_) noexcept
Valued constructor (int).
Valued constructor (int).
References BaseWell< 16 >::seed().
Well512a() [3/10]
Well512a::Well512a (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References BaseWell< 16 >::seed().
Well512a() [4/10]
Well512a::Well512a (const long seed_) noexcept
Valued constructor (long)
Valued constructor (long).
References BaseWell< 16 >::seed().
Well512a() [5/10]
Well512a::Well512a (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor(unsigned long).
References BaseWell< 16 >::seed().
Well512a() [6/10]
Well512a::Well512a (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor (long long).
References BaseWell< 16 >::seed().
Well512a() [7/10]
Well512a::Well512a (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References BaseWell< 16 >::seed().
Well512a() [8/10]
Well512a::Well512a (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References BaseWell< 16 >::seed().
Well512a() [9/10]
Well512a::Well512a (const double seed_)
Valued constructor (double).
Valued constructor (double).
References BaseWell< 16 >::seed().
Well512a() [10/10]
Well512a::Well512a (const state_type & internal_state) noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::setstate().
~Well512a()
virtual Well512a::~Well512a () inline virtual default noexcept
default destructor.
References next().
Member Function Documentation
next()
const Well512a::output_type Well512a::next () override virtual noexcept
The internal PRNG algorithm.
Returns
an integer value coded on 32 bits.
The internal PRNG algorithm.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
Referenced by ~Well512a().
The documentation for this class was generated from the following files:
well512a.h
well512a.cpp