CppRandLib - c++20: algos: CWG - Collatz-Weyl Generators
algos: CWG - Collatz-Weyl Generators
Classes
class BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >
The base class for all Collatz-Weyl pseudorandom Generators (CWG).
class Cwg128
A 128-bits Collatz-Weyl pseudorandom Generator with a short period (4.36e+40).
class Cwg128_64
A 128-/64- bits Collatz-Weyl pseudorandom Generator with a short period (1.18e+21).
class Cwg64
A 64-bits Collatz-Weyl pseudorandom Generator with a long period (1.18e+21).
Functions
virtual void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::_setstate (const std::uint64_t seed_) noexcept override
Sets the internal state with a 64-bits integer seed.
virtual void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::_setstate (const utils::UInt128 &seed_) noexcept override
Sets the internal state with a 128-bits integer seed.
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG () noexcept
Default empty constructor.
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const double seed)
Valued constructor (double).
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const int seed) noexcept
Valued constructor (int).
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const long long seed) noexcept
Valued constructor (long long).
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const long seed) noexcept
Valued constructor (long)
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed () noexcept
Initializes internal state (empty signature).
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const double seed_)
Initializes internal state (double).
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const int seed_) noexcept
Initializes internal state (int).
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const long long seed_) noexcept
Initializes internal state (long long).
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const long seed_) noexcept
Initializes internal state (long)
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
This is the group for all the CppRandLib implementations of the Collatz-Weyl pseudorandom Generators (CWG) algorithm.
CWG models are chaotic generators that are combined with Weyl sequences to eliminate the risk of short cycles. They have a large period, a uniform distribution, and the ability to generate multiple independent streams by changing their internal parameters (Weyl increment). CWGs owe their exceptional quality to the arithmetical dynamics of noninvertible, generalized, Collatz mappings based on the wellknown Collatz conjecture. There is no jump function, but each odd number of the Weyl increment initiates a new unique period, which enables quick initialization of independent streams (this text is extracted from [8], see README.md).
The internal implementation of the CWG algorithm varies according to its implemented version. See implementation classes to get their formal description.
Function Documentation
_setstate() [1/2]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< StateT, OutputT, OUTPUT_BITS >.
Reimplemented in Cwg128, and Cwg128_64.
Referenced by seed().
_setstate() [2/2]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< StateT, OutputT, OUTPUT_BITS >.
Reimplemented in Cwg128, and Cwg128_64.
BaseCWG() [1/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG () inline noexcept
Default empty constructor.
Empty constructor.
References BaseCWG(), and BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
Referenced by BaseCWG().
BaseCWG() [2/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const double seed_) inline
Valued constructor (double).
Valued construtor (double).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
BaseCWG() [3/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const int seed_) inline noexcept
Valued constructor (int).
Valued construtor (int).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
BaseCWG() [4/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const long long seed_) inline noexcept
Valued constructor (long long).
Valued construtor (long long).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
BaseCWG() [5/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const long seed_) inline noexcept
Valued constructor (long)
Valued construtor (long).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
BaseCWG() [6/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::setstate().
BaseCWG() [7/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued construtor (unsigned int).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
BaseCWG() [8/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued construtor (unsigned long long).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
BaseCWG() [9/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued construtor (unsigned long).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
BaseCWG() [10/10]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::BaseCWG (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued construtor (128-bits integer).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
seed() [1/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< StateT, OutputT, OUTPUT_BITS >.
Reimplemented in Cwg128, Cwg128_64, and Cwg64.
References _setstate(), and utils::set_random_seed64().
seed() [2/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const double seed_) inline
Initializes internal state (double).
Initializes internal state (double).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
seed() [3/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const int seed_) inline noexcept
Initializes internal state (int).
Initializes internal state (int).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
seed() [4/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const long long seed_) inline noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
seed() [5/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const long seed_) inline noexcept
Initializes internal state (long)
Initializes internal state (long).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
seed() [6/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const unsigned int seed_) inline noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
seed() [7/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const unsigned long long seed_) inline noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
seed() [8/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const unsigned long seed_) inline noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().
seed() [9/9]
template<typename ValueType, typename StateValueType, typename OutputType, const std::uint32_t OUTPUT_BITS> void BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< StateT, OutputT, OUTPUT_BITS >.
Reimplemented in Cwg128, Cwg128_64, and Cwg64.
References BaseRandom< CollatzWeylState< ValueType, StateValueType >, OutputType, OUTPUT_BITS >::seed().