CppRandLib - c++20: Lagged Fibonacci (LFib) algorithm
Lagged Fibonacci (LFib) algorithm
Classes
class BaseLFib64< SIZE, K >
The base class for all LFib PRNG based on 64-bits numbers.
Typedefs
using LFib116 = BaseLFib64<55, 24>
A fast 64-bits Lagged Fibonacci Generator with a short period (8.3e+34).
using LFib1340 = BaseLFib64<1279, 861>
A fast 64-bits Lagged Fibonacci Generator with a very long period (2.4e+403).
using LFib668 = BaseLFib64<607, 273>
A fast 64-bits Lagged Fibonacci Generator with a long period (1.2e+201).
using LFib78 = BaseLFib64<17, 5>
A fast 64-bits Lagged Fibonacci Generator with a short period (3.0e+23).
Functions
void BaseLFib64< SIZE, K >::_initIndex (const size_t _index) noexcept
Inits the internal index pointing to the internal list.
virtual void BaseLFib64< SIZE, K >::_setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void BaseLFib64< SIZE, K >::_setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseLFib64< SIZE, K >::BaseLFib64 () noexcept
Default empty constructor.
BaseLFib64< SIZE, K >::BaseLFib64 (const double seed)
Valued constructor (double).
BaseLFib64< SIZE, K >::BaseLFib64 (const int seed) noexcept
Valued constructor (int).
BaseLFib64< SIZE, K >::BaseLFib64 (const long long seed) noexcept
Valued constructor (long long).
BaseLFib64< SIZE, K >::BaseLFib64 (const long seed) noexcept
Valued constructor (long)
BaseLFib64< SIZE, K >::BaseLFib64 (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseLFib64< SIZE, K >::BaseLFib64 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual const output_type BaseLFib64< SIZE, K >::next () noexcept override
The internal PRNG algorithm.
void BaseLFib64< SIZE, K >::seed () noexcept
Initializes internal state (empty signature).
void BaseLFib64< SIZE, K >::seed (const double seed_)
Initializes internal state (double).
void BaseLFib64< SIZE, K >::seed (const int seed_) noexcept
Initializes internal state (int).
void BaseLFib64< SIZE, K >::seed (const long long seed_) noexcept
Initializes internal state (long long).
void BaseLFib64< SIZE, K >::seed (const long seed_) noexcept
Initializes internal state (long)
void BaseLFib64< SIZE, K >::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void BaseLFib64< SIZE, K >::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void BaseLFib64< SIZE, K >::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void BaseLFib64< SIZE, K >::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
This is the group for all the CppRandLib implementations of the Lagged Fibonacci pseudorandom generators (LFib) algorithm.
Lagged Fibonacci generators LFib(m, r, k, op) use the recurrence
x(i) = (x(i-r) op (x(i-k)) mod m
where op is an operation that can be:
+ (addition),
- (substraction),
* (multiplication),
^ (bitwise exclusive-or).
With the + or - operation, such generators are in fact MRGs. They offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007".
Typedef Documentation
LFib116
using LFib116 = BaseLFib64<55, 24>
A fast 64-bits Lagged Fibonacci Generator with a short period (8.3e+34).
Lagged Fibonacci generators LFib(m, r, k, op) use the recurrence
x(i) = (x(i-r) op (x(i-k)) mod m
where op is an operation that can be:
(addition),
(substraction),
(multiplication), ^ (bitwise exclusive-or).
With the + or - operation, such generators are in fact MRGs. They offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007". It is recommended to use such pseudo-random numbers generators rather than LCG ones for serious simulation applications.
The implementation of this LFib 64-bits model is based on a Lagged Fibonacci generator (LFIB) that uses the recurrence
x(i) = (x(i-24) + x(i-55)) mod 2^64
and offers a period of about 2^116 - i.e. 8.3e+34 - with low computation time due to the use of a 2^64 modulo and little memory space consumption (55 long integ- ers).
Please notice that the TestUO1 article states that the operator should be '*' while Mascagni & Srinivasan in their original article stated that the operator is '+'. We've implemented here the original operator: '+'.
See LFib78, LFib668 and LFib1340 for long period LFib generators (resp. 2^78, 2^668 and 2^1340 periods, i.e. resp. 3.0e+23, 1.2e+201 and 2.4e+403 periods) while same computation time and far higher precision (64-bits calculations) than MRGs, but memory consumption (resp. 17, 607 and 1279 integers).* Please notice that this class and all its inheriting sub-classes are callable. Example:
LFib116 rand{};
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
LFib116 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the LFibs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +-----------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
LFib78 LFib(2^64, 17, 5, +) 34 x 4-bytes 2^78 n.a. 1.1 0 0 0
LFib116 LFib(2^64, 55, 24, +) 110 x 4-bytes 2^116 n.a. 1.0 0 0 0
LFib668 LFib(2^64, 607, 273, +) 1,214 x 4-bytes 2^668 n.a. 0.9 0 0 0
LFib1340 LFib(2^64, 1279, 861, +) 2,558 x 4-bytes 2^1340 n.a. 0.9 0 0 0
+-----------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRG should definitively pass.
LFib1340
using LFib1340 = BaseLFib64<1279, 861>
A fast 64-bits Lagged Fibonacci Generator with a very long period (2.4e+403).
Lagged Fibonacci generators LFib(m, r, k, op) use the recurrence
x(i) = (x(i-r) op (x(i-k)) mod m
where op is an operation that can be:
(addition),
(substraction),
(multiplication), ^ (bitwise exclusive-or).
With the + or - operation, such generators are in fact MRGs. They offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007". It is recommended to use such pseudo-random numbers generators rather than LCG ones for serious simulation applications.
The implementation of this LFib 64-bits model is based on a Lagged Fibonacci generator (LFIB) that uses the recurrence
x(i) = (x(i-861) + x(i-1279)) mod 2^64
and offers a period of about 2^1340 - i.e. 2.4e+403 - with low computation time due to the use of a 2^64 modulo but memory space consumption (1379 long integ- ers).
Please notice that the TestUO1 article states that the operator should be '*' while Mascagni & Srinivasan in their original article stated that the operator is '+'. We've implemented here the original operator: '+'.
See LFib78, LFib116 and LFib668 for long period LFib generators (resp. 2^78, 2^116 and 2^668 periods, i.e. resp. 3.0e+23, 8.3e+34 and 1.2e+201 periods) while same computation time and far higher precision (64-bits calculations) than MRGs, but memory consumption (resp. 17, 55 and 607 integers).
Please notice that this class and all its inheriting sub-classes are callable. Example:
LFib1340 rand{};
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
LFib1340 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the LFibs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +-----------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
LFib78 LFib(2^64, 17, 5, +) 34 x 4-bytes 2^78 n.a. 1.1 0 0 0
LFib116 LFib(2^64, 55, 24, +) 110 x 4-bytes 2^116 n.a. 1.0 0 0 0
LFib668 LFib(2^64, 607, 273, +) 1,214 x 4-bytes 2^668 n.a. 0.9 0 0 0
LFib1340 LFib(2^64, 1279, 861, +) 2,558 x 4-bytes 2^1340 n.a. 0.9 0 0 0
+-----------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRG should definitively pass.
LFib668
using LFib668 = BaseLFib64<607, 273>
A fast 64-bits Lagged Fibonacci Generator with a long period (1.2e+201).
Lagged Fibonacci generators LFib(m, r, k, op) use the recurrence
x(i) = (x(i-r) op (x(i-k)) mod m
where op is an operation that can be:
(addition),
(substraction),
(multiplication), ^ (bitwise exclusive-or).
With the + or - operation, such generators are in fact MRGs. They offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007". It is recommended to use such pseudo-random numbers generators rather than LCG ones for serious simulation applications.
The implementation of this LFib 64-bits model is based on a Lagged Fibonacci generator (LFIB) that uses the recurrence
x(i) = (x(i-273) + x(i-607)) mod 2^64
and offers a period of about 2^668 - i.e. 1.2e+201 - with low computation time due to the use of a 2^64 modulo and little memory space consumption (607 long integ- ers).
Please notice that the TestUO1 article states that the operator should be '*' while Mascagni & Srinivasan in their original article stated that the operator is '+'. We've implemented here the original operator: '+'.
See LFib78, LFib116 and LFib1340 for long period LFib generators (resp. 2^78, 2^116 and 2^1340 periods, i.e. resp. 3.0e+23, 8.3e+34 and 2.4e+403 periods) while same computation time and far higher precision (64-bits calculations) than MRGs, but memory consumption (resp. 17, 55 and 1279 integers).
Please notice that this class and all its inheriting sub-classes are callable. Example:
LFib607 rand{};
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
LFib607 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the LFibs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +-----------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
LFib78 LFib(2^64, 17, 5, +) 34 x 4-bytes 2^78 n.a. 1.1 0 0 0
LFib116 LFib(2^64, 55, 24, +) 110 x 4-bytes 2^116 n.a. 1.0 0 0 0
LFib668 LFib(2^64, 607, 273, +) 1,214 x 4-bytes 2^668 n.a. 0.9 0 0 0
LFib1340 LFib(2^64, 1279, 861, +) 2,558 x 4-bytes 2^1340 n.a. 0.9 0 0 0
+-----------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRG should definitively pass.
LFib78
using LFib78 = BaseLFib64<17, 5>
A fast 64-bits Lagged Fibonacci Generator with a short period (3.0e+23).
Lagged Fibonacci generators LFib(m, r, k, op) use the recurrence
x(i) = (x(i-r) op (x(i-k)) mod m
where op is an operation that can be:
(addition),
(substraction),
(multiplication), ^ (bitwise exclusive-or).
With the + or - operation, such generators are in fact MRGs. They offer very large periods with the best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007". It is recommended to use such pseudo-random numbers generators rather than LCG ones for serious simulation applications.
The implementation of this LFib 64-bits model is based on a Lagged Fibonacci generator (LFIB) that uses the recurrence
x(i) = (x(i-5) + x(i-17)) mod 2^64
and offers a period of about 2^78 - i.e. 3.0e+23 - with low computation time due to the use of a 2^64 modulo and few memory space consumption (17 long integers).
Please notice that the TestUO1 article states that the operator should be '*' while Mascagni & Srinivasan in their original article stated that the operator is '+'. We've implemented here the original operator: '+'.
See LFib116, LFib668 and LFib1340 for long period LFib generators (resp. 2^116, 2^668 and 2^1340 periods, i.e. resp. 8.3e+34, 1.2e+201 and 2.4e+403 periods) while same computation time and far higher precision (64-bits calculations) than MRGs, but memory consumption (resp. 55, 607 and 1279 integers).
Please notice that this class and all its inheriting sub-classes are callable. Example:
LFib78 rand{};
std::cout << rand() << std::endl;    // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;   // prints a uniform pseudo-random value within [0.0, b)
Notice that for simulating the roll of a dice you should program:
LFib78 diceRoll();
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the LFibs that have been implemented in CppRandLib, as provided in paper "TestU01, ..." - see file README.md. +-----------------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class TU01 generator name Memory Usage Period time-32bits time-64 bits SmallCrush fails Crush fails BigCrush fails
LFib78 LFib(2^64, 17, 5, +) 34 x 4-bytes 2^78 n.a. 1.1 0 0 0
LFib116 LFib(2^64, 55, 24, +) 110 x 4-bytes 2^116 n.a. 1.0 0 0 0
LFib668 LFib(2^64, 607, 273, +) 1,214 x 4-bytes 2^668 n.a. 0.9 0 0 0
LFib1340 LFib(2^64, 1279, 861, +) 2,558 x 4-bytes 2^1340 n.a. 0.9 0 0 0
+-----------------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRG should definitively pass.
Function Documentation
_initIndex()
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::_initIndex (const size_t _index) inline noexcept
Inits the internal index pointing to the internal list.
Inits the internal index pointing to the internal list.
_setstate() [1/2]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::_setstate (const std::uint64_t seed) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
_setstate() [2/2]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::_setstate (const utils::UInt128 & seed) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::_setstate(), and seed().
BaseLFib64() [1/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 () inline noexcept
Default empty constructor.
Empty constructor.
References BaseLFib64(), and seed().
Referenced by BaseLFib64().
BaseLFib64() [2/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References seed().
BaseLFib64() [3/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
BaseLFib64() [4/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
BaseLFib64() [5/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
BaseLFib64() [6/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::setstate().
BaseLFib64() [7/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
BaseLFib64() [8/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
BaseLFib64() [9/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
BaseLFib64() [10/10]
template<const std::uint32_t SIZE, std::uint32_t K> BaseLFib64< SIZE, K >::BaseLFib64 (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (utils::UInt128).
References seed().
next()
template<const std::uint32_t SIZE, std::uint32_t K> const BaseLFib64< SIZE, K >::output_type BaseLFib64< SIZE, K >::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
seed() [1/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
Referenced by _setstate(), _setstate(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), BaseLFib64(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const double seed_) inline
Initializes internal state (double).
Initializes internal state (double).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
seed() [3/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const int seed_) inline noexcept
Initializes internal state (int).
Initializes internal state (int).
References seed().
seed() [4/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const long long seed_) inline noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References seed().
seed() [5/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const long seed_) inline noexcept
Initializes internal state (long)
Initializes internal state (long).
References seed().
seed() [6/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const unsigned int seed_) inline noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References seed().
seed() [7/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const unsigned long long seed_) inline noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
seed() [8/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const unsigned long seed_) inline noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References seed().
seed() [9/9]
template<const std::uint32_t SIZE, std::uint32_t K> void BaseLFib64< SIZE, K >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().