CppRandLib - c++20: Linear Congruential Generator (LCG) algorithms
Linear Congruential Generator (LCG) algorithms
Classes
class FastRand32
Fast Linear Congruential Generator - 32 bits.
class FastRand63
Fast Linear Congruential Generator - 63 bits.
Functions
virtual void FastRand32::_setstate (const std::uint64_t seed_) noexcept override
Sets the internal state with a 64-bits integer seed.
virtual void FastRand32::_setstate (const utils::UInt128 &seed_) noexcept override
Sets the internal state with a 128-bits integer seed.
virtual void FastRand63::_setstate (const std::uint64_t seed_) noexcept override
Sets the internal state with a 64-bits integer seed.
virtual void FastRand63::_setstate (const utils::UInt128 &seed_) noexcept override
Sets the internal state with a 128-bits integer seed.
FastRand32::FastRand32 () noexcept
Empty constructor.
FastRand32::FastRand32 (const double seed_)
Valued constructor (double).
FastRand32::FastRand32 (const int seed_) noexcept
Valued constructor (int).
FastRand32::FastRand32 (const long long seed_) noexcept
Valued constructor (long long).
FastRand32::FastRand32 (const long seed_) noexcept
Valued constructor (long)
FastRand32::FastRand32 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
FastRand32::FastRand32 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
FastRand32::FastRand32 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
FastRand32::FastRand32 (const utils::UInt128 &seed_) noexcept
Valued constructor (unsigned 128-bits).
FastRand63::FastRand63 () noexcept
Empty constructor.
FastRand63::FastRand63 (const double seed_)
Valued constructor (double).
FastRand63::FastRand63 (const int seed_) noexcept
Valued constructor (int).
FastRand63::FastRand63 (const long long seed_) noexcept
Valued constructor (long long).
FastRand63::FastRand63 (const long seed_) noexcept
Valued constructor (long)
FastRand63::FastRand63 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
FastRand63::FastRand63 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
FastRand63::FastRand63 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
FastRand63::FastRand63 (const utils::UInt128 &seed_) noexcept
Valued constructor (unsigned 128-bits).
virtual const output_type FastRand32::next () noexcept override
The internal PRNG algorithm.
virtual const output_type FastRand63::next () noexcept override
The internal PRNG algorithm.
virtual void FastRand32::seed () noexcept override
Initializes internal state (empty signature).
void FastRand32::seed (const double seed_)
Initializes internal state (double).
void FastRand32::seed (const int seed_) noexcept
Initializes internal state (int).
void FastRand32::seed (const long long seed_) noexcept
Initializes internal state (long long).
void FastRand32::seed (const long seed_) noexcept
Initializes internal state (long)
void FastRand32::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void FastRand32::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void FastRand32::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void FastRand32::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
virtual void FastRand63::seed () noexcept override
Initializes internal state (empty signature).
void FastRand63::seed (const double seed_)
Initializes internal state (double).
void FastRand63::seed (const int seed_) noexcept
Initializes internal state (int).
void FastRand63::seed (const long long seed_) noexcept
Initializes internal state (long long).
void FastRand63::seed (const long seed_) noexcept
Initializes internal state (long)
void FastRand63::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void FastRand63::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void FastRand63::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void FastRand63::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
This is the group for all the CppRandLib implementations of the Linear Congruential Generator (LCG) algorithm.
LCG models evaluate pseudo-random numbers suites x(i) as a simple mathematical function of
x(i) = (a * x(i-1) + c) mod m
Results are nevertheless considered to be poor as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in 'TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007'. It is not recommended to use such pseudo-random numbers generators for serious simulation applications.
Function Documentation
_setstate() [1/4]
void FastRand32::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state with a 64-bits integer seed.
Sets the internal state with an integer seed.
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
Referenced by _setstate(), and ~FastRand32().
_setstate() [2/4]
void FastRand32::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state with a 128-bits integer seed.
Sets the internal state with a 128-bits integer seed.
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References _setstate().
_setstate() [3/4]
void FastRand63::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state with a 64-bits integer seed.
Sets the internal state with an integer seed.
Reimplemented from BaseRandom< std::uint64_t, std::uint64_t, 63 >.
Referenced by _setstate(), and ~FastRand63().
_setstate() [4/4]
void FastRand63::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state with a 128-bits integer seed.
Sets the internal state with a 128-bits integer seed.
Reimplemented from BaseRandom< std::uint64_t, std::uint64_t, 63 >.
References _setstate().
FastRand32() [1/9]
FastRand32::FastRand32 () inline noexcept
Empty constructor.
Empty constructor.
References FastRand32(), and seed().
Referenced by FastRand32().
FastRand32() [2/9]
FastRand32::FastRand32 (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References seed().
FastRand32() [3/9]
FastRand32::FastRand32 (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
FastRand32() [4/9]
FastRand32::FastRand32 (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
FastRand32() [5/9]
FastRand32::FastRand32 (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
FastRand32() [6/9]
FastRand32::FastRand32 (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
FastRand32() [7/9]
FastRand32::FastRand32 (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
FastRand32() [8/9]
FastRand32::FastRand32 (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
FastRand32() [9/9]
FastRand32::FastRand32 (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References seed().
FastRand63() [1/9]
FastRand63::FastRand63 () inline noexcept
Empty constructor.
Empty constructor.
References FastRand63(), and seed().
Referenced by FastRand63().
FastRand63() [2/9]
FastRand63::FastRand63 (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References seed().
FastRand63() [3/9]
FastRand63::FastRand63 (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
FastRand63() [4/9]
FastRand63::FastRand63 (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
FastRand63() [5/9]
FastRand63::FastRand63 (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
FastRand63() [6/9]
FastRand63::FastRand63 (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
FastRand63() [7/9]
FastRand63::FastRand63 (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
FastRand63() [8/9]
FastRand63::FastRand63 (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
FastRand63() [9/9]
FastRand63::FastRand63 (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References seed().
next() [1/2]
const FastRand32::output_type FastRand32::next () inline override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
Referenced by ~FastRand32().
next() [2/2]
const FastRand63::output_type FastRand63::next () inline override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< std::uint64_t, std::uint64_t, 63 >.
Referenced by ~FastRand63().
seed() [1/18]
void FastRand32::seed () inline override virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References BaseRandom< std::uint32_t, std::uint32_t, 32 >::seed().
Referenced by FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), FastRand32(), seed(), seed(), seed(), seed(), seed(), and ~FastRand32().
seed() [2/18]
void FastRand32::seed (const double seed_) inline
Initializes internal state (double).
Initializes internal state (double).
References BaseRandom< std::uint32_t, std::uint32_t, 32 >::seed().
seed() [3/18]
void FastRand32::seed (const int seed_) inline noexcept
Initializes internal state (int).
Initializes internal state (int).
References seed().
seed() [4/18]
void FastRand32::seed (const long long seed_) inline noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References seed().
seed() [5/18]
void FastRand32::seed (const long seed_) inline noexcept
Initializes internal state (long)
Initializes internal state (long).
References seed().
seed() [6/18]
void FastRand32::seed (const unsigned int seed_) inline noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References seed().
seed() [7/18]
void FastRand32::seed (const unsigned long long seed_) inline noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
References BaseRandom< std::uint32_t, std::uint32_t, 32 >::seed().
seed() [8/18]
void FastRand32::seed (const unsigned long seed_) inline noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References seed().
seed() [9/18]
void FastRand32::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< std::uint32_t, std::uint32_t, 32 >.
References BaseRandom< std::uint32_t, std::uint32_t, 32 >::seed().
seed() [10/18]
void FastRand63::seed () inline override virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Reimplemented from BaseRandom< std::uint64_t, std::uint64_t, 63 >.
References BaseRandom< std::uint64_t, std::uint64_t, 63 >::seed().
Referenced by FastRand63(), FastRand63(), FastRand63(), FastRand63(), FastRand63(), FastRand63(), FastRand63(), FastRand63(), FastRand63(), seed(), seed(), seed(), seed(), seed(), and ~FastRand63().
seed() [11/18]
void FastRand63::seed (const double seed_) inline
Initializes internal state (double).
Initializes internal state (double).
References BaseRandom< std::uint64_t, std::uint64_t, 63 >::seed().
seed() [12/18]
void FastRand63::seed (const int seed_) inline noexcept
Initializes internal state (int).
Initializes internal state (int).
References seed().
seed() [13/18]
void FastRand63::seed (const long long seed_) inline noexcept
Initializes internal state (long long).
Initializes internal state (long long).
References seed().
seed() [14/18]
void FastRand63::seed (const long seed_) inline noexcept
Initializes internal state (long)
Initializes internal state (long).
References seed().
seed() [15/18]
void FastRand63::seed (const unsigned int seed_) inline noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
References seed().
seed() [16/18]
void FastRand63::seed (const unsigned long long seed_) inline noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
References BaseRandom< std::uint64_t, std::uint64_t, 63 >::seed().
seed() [17/18]
void FastRand63::seed (const unsigned long seed_) inline noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
References seed().
seed() [18/18]
void FastRand63::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< std::uint64_t, std::uint64_t, 63 >.
References BaseRandom< std::uint64_t, std::uint64_t, 63 >::seed().