CppRandLib - c++20: CollatzWeylState< ValueType, StateValueType > Struct Template Reference
CollatzWeylState< ValueType, StateValueType > Struct Template Reference
Algorithms Internal States Definitions
The internal state of counter-based Pseudo Random Numbers Generators.
#include <collatzweylstate.h>
Public Types
using state_value_type = StateValueType
using value_type = ValueType
Public Member Functions
CollatzWeylState () noexcept=default
Default empty constructor.
CollatzWeylState (CollatzWeylState &&other) noexcept=default
Move constructor.
CollatzWeylState (const CollatzWeylState &other) noexcept=default
Copy constructor.
CollatzWeylState & operator= (CollatzWeylState &&other) noexcept=default
Assignment move operator.
CollatzWeylState & operator= (const CollatzWeylState &other) noexcept=default
Assignment copy operator.
bool const operator== (const CollatzWeylState &other) const noexcept
equality operator.
void seed (const std::uint64_t seed_) noexcept
Initalizes the internal state according to a 64-bits integer seed.
void seed (const std::uint64_t seed_) noexcept
void seed (const std::uint64_t seed_) noexcept
void seed (const std::uint64_t seed_) noexcept
void seed (const utils::UInt128 &seed_) noexcept
Initalizes the internal state according to a 128-bits integer seed.
void seed (const utils::UInt128 &seed_) noexcept
void seed (const utils::UInt128 &seed_) noexcept
void seed (const utils::UInt128 &seed_) noexcept
virtual ~CollatzWeylState () noexcept=default
Default destructor.
Public Attributes
value_type a { value_type(0) }
value_type s { value_type(1) }
state_value_type state { state_value_type(0) }
value_type weyl { value_type(0) }
Detailed Description
template<typename ValueType, typename StateValueType>
struct CollatzWeylState< ValueType, StateValueType >
The internal state of counter-based Pseudo Random Numbers Generators.
Constructor & Destructor Documentation
CollatzWeylState() [1/3]
template<typename ValueType, typename StateValueType> CollatzWeylState< ValueType, StateValueType >::CollatzWeylState () inline default noexcept
Default empty constructor.
Referenced by CollatzWeylState(), CollatzWeylState(), operator=(), operator=(), operator==(), and ~CollatzWeylState().
CollatzWeylState() [2/3]
template<typename ValueType, typename StateValueType> CollatzWeylState< ValueType, StateValueType >::CollatzWeylState (const CollatzWeylState< ValueType, StateValueType > & other) inline default noexcept
Copy constructor.
References CollatzWeylState().
CollatzWeylState() [3/3]
template<typename ValueType, typename StateValueType> CollatzWeylState< ValueType, StateValueType >::CollatzWeylState (CollatzWeylState< ValueType, StateValueType > && other) inline default noexcept
Move constructor.
References CollatzWeylState().
~CollatzWeylState()
template<typename ValueType, typename StateValueType> virtual CollatzWeylState< ValueType, StateValueType >::~CollatzWeylState () inline virtual default noexcept
Default destructor.
References CollatzWeylState().
Member Function Documentation
operator=() [1/2]
template<typename ValueType, typename StateValueType> CollatzWeylState & CollatzWeylState< ValueType, StateValueType >::operator= (CollatzWeylState< ValueType, StateValueType > && other) inline default noexcept
Assignment move operator.
References CollatzWeylState(), and seed().
operator=() [2/2]
template<typename ValueType, typename StateValueType> CollatzWeylState & CollatzWeylState< ValueType, StateValueType >::operator= (const CollatzWeylState< ValueType, StateValueType > & other) inline default noexcept
Assignment copy operator.
References CollatzWeylState().
seed() [1/6]
void CollatzWeylState< std::uint64_t, std::uint64_t >::seed (const std::uint64_t seed_) inline noexcept
Specialization for <64-, 64-> bits internal state.
seed() [2/6]
void CollatzWeylState< std::uint64_t, utils::UInt128 >::seed (const std::uint64_t seed_) inline noexcept
Specialization for <64-, 128-> bits internal state.
seed() [3/6]
void CollatzWeylState< utils::UInt128, utils::UInt128 >::seed (const std::uint64_t seed_) inline noexcept
Specialization for <128-, 128-> bits internal state.
seed() [4/6]
void CollatzWeylState< std::uint64_t, std::uint64_t >::seed (const utils::UInt128 & seed_) inline noexcept
Specialization for <64-, 64-> bits internal state.
seed() [5/6]
void CollatzWeylState< std::uint64_t, utils::UInt128 >::seed (const utils::UInt128 & seed_) inline noexcept
Specialization for <64-, 128-> bits internal state.
seed() [6/6]
void CollatzWeylState< utils::UInt128, utils::UInt128 >::seed (const utils::UInt128 & seed_) inline noexcept
Specialization for <128-, 128-> bits internal state.
The documentation for this struct was generated from the following file:
collatzweylstate.h