CppRandLib - c++11: Pcg1024_32 Class Reference
Pcg1024_32 Class Reference
Permuted Congruential Generator (PCG) algorithm
Permutated Congruential Generator dedicated to 64-bits calculations and 32-bits output with medium period (about 1.84e+19).
#include <pcg1024_32.h>
Public Types
using extended_value_type = MyBaseClass::state_type::extended_value_type
using MyBaseClass = BasePCG<ExtendedState<Pcg64_32, std::uint32_t, 1024>, std::uint32_t>
using state_type = MyBaseClass::state_type
using value_type = MyBaseClass::state_type::value_type
Public Types inherited from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>
using output_type
using state_type
Public Member Functions
virtual void _setstate (const std::uint64_t seed_) noexcept override
Sets the internal state with a 64-bits integer seed.
virtual void _setstate (const utils::UInt128 &seed_) noexcept override
Sets the internal state with a 128-bits integer seed.
virtual const output_type next () noexcept override
The internal PRNG algorithm.
Pcg1024_32 () noexcept
Default empty constructor.
Pcg1024_32 (const double seed)
Valued constructor (double).
Pcg1024_32 (const int seed) noexcept
Valued constructor (int).
Pcg1024_32 (const long long seed) noexcept
Valued constructor (long long).
Pcg1024_32 (const long seed) noexcept
Valued constructor (long)
Pcg1024_32 (const unsigned int seed) noexcept
Valued constructor (unsigned int).
Pcg1024_32 (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
Pcg1024_32 (const unsigned long seed) noexcept
Valued constructor (unsigned long).
Pcg1024_32 (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
virtual void seed () noexcept override
Initializes internal state (empty signature).
void seed (const double seed_)
Initializes internal state (double).
void seed (const int seed_) noexcept
Initializes internal state (int).
void seed (const long long seed_) noexcept
Initializes internal state (long long).
void seed (const long seed_) noexcept
Initializes internal state (long)
void seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Public Member Functions inherited from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>
BaseRandom () noexcept=default
default empty constructor.
BaseRandom (BaseRandom &&) noexcept=default
default move constructor.
BaseRandom (const BaseRandom &) noexcept=default
default copy constructor.
const double betavariate (const double alpha, const double beta)
Beta distribution.
const CountT binomialvariate (CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
const T & choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
const T & choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
std::vector< T > choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
std::vector< T > choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
std::vector< T > choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double expovariate (const double lambda=1.0)
Exponential distribution.
const double gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
OutputT getrandbits (const unsigned int k)
Returns a non-negative integer with k random bits.
struct _InternalState getstate () const noexcept
Returns the internal state of this PRNG; can be passed to setstate() later.
const double lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
std::array< T, n > n_evaluate ()
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
std::array< T, m > n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
std::array< T, m > n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
std::vector< T > n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
std::vector< T > n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
std::vector< T > n_evaluate (const std::vector< U > &max)
Returns a vector of n values in range [0; max[i]).
std::vector< T > n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
std::array< T, n > n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
std::array< T, n > n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
const double normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
const T operator() () noexcept
Empty Call operator.
std::array< T, n > operator() (const std::array< T, n > &max)
Valued call operator (1 std::array of scalars).
std::array< T, n > operator() (const std::array< T, n > &min, const std::array< T, n > &max)
Valued call operator (2 std::array of scalars).
std::vector< T > operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
std::vector< T > operator() (const std::vector< T > &min, const std::vector< T > &max)
Valued call operator (2 std::vector of scalars).
const T operator() (const T max)
Valued call operator (1 scalar).
std::vector< T > operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
std::vector< T > operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
BaseRandom & operator= (BaseRandom &&) noexcept=default
default move assignment.
BaseRandom & operator= (const BaseRandom &) noexcept=default
default copy assignment.
BaseRandom & operator= (const StateT &new_internal_state) noexcept
< valued assignment.
const double paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > randbytes (const std::size_t n)
Generates n random bytes.
const T randint (const T a, const T b)
Returns random integer in range [a, b], including both end points.
const T random ()
The uniform distribution on [0.0, 1.0).
const long double random ()
const T randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
void sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
void sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
void sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
void setstate (const StateT &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void setstate (const StateT &new_internal_state, const double gauss_next) noexcept
Sets the internal state from a new internal state content and with gauss_next.
void setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
void shuffle (ContainerType &seq)
Shuffles specified sequence in place.
const state_type state () const noexcept
Returns the current internal state value.
const double triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
const T uniform ()
Uniform distribution in [0.0, 1.0).
const double uniform (const double max)
const float uniform (const float max)
const long double uniform (const long double max)
const T uniform (const U max)
Uniform distribution in [0.0, max).
const T uniform (const U min, const V max)
Uniform distribution in [min, max).
const double vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double weibullvariate (const double alpha, const double beta)
Weibull distribution.
virtual ~BaseRandom () noexcept=default
default destructor.
Static Public Attributes
static const unsigned int _INDEX_MODULO { _STATE_SIZE - 1 }
static const std::uint64_t _MODULO_32 { (1ull << 32) - 1ull }
static const unsigned int _STATE_SIZE { 1024 }
Additional Inherited Members
Public Attributes inherited from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>
struct BaseRandom::_InternalState _internal_state
Static Protected Attributes inherited from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>
static constexpr std::uint64_t _MODULO
static constexpr double _NORMALIZE
static constexpr long double _NORMALIZE_LD
static const double BPF
static const double E
static const double GAUSS_NULL
static const double LOG4
static const double NV_MAGICCONST
static const double PI
static const double RECIP_BPF
static const double SG_MAGICCONST
static const double TWO_PI
Detailed Description
Permutated Congruential Generator dedicated to 64-bits calculations and 32-bits output with medium period (about 1.84e+19).
This Pcg1024_32 class implements the "PCG XSH RS 64/32 (EXT 1024)" version of the PCG algorithm, as specified in the related paper (see reference [7] in document README.md). Output values are returned on 32 bits. State value is coded on 64-bits. Each value in extended state is coded on 32-bits.
PCGs are very fast generators, with low memory usage except for a very few of them and medium to very large periods. They offer jump ahead and multi streams features for most of them. They are difficult to very difficult to invert and to predict.
See Pcg64_32 for a 2^64 (i.e. 1.84e+19) period PC-Generator with very low computation time and medium period, with 2 32-bits word integers memory consumption. Output values are returned on 32 bits.
See Pcg128_64 for a 2^128 (i.e. about 3.40e+38) period PC-Generator with low computation time also and a longer period than for Pcg64_32, with 4 32-bits word integers memory consumption. Output values are returned on 64 bits.
Furthermore this class is callable:
Pcg1024_32 rand{};
std::cout << rand() << std::endl;     // prints a uniform pseudo-random value within [0.0, 1.0)
std::cout << rand(b) << std::endl;    // prints a uniform pseudo-random value within [0.0, b)
Please notice that for simulating the roll of a dice you may use any of:
Pcg1024_32 diceRoll{};
std::cout << 1 + int(diceRoll(6)) << std::endl;   // prints a uniform roll within range {1, ..., 6}
std::cout << diceRoll.randint(1, 6) << std::endl; // prints also a uniform roll within range {1, ..., 6}
Reminder: We give you here below a copy of the table of tests for the PCG algorithms that have been implemented in CppRandLib, as provided in paper "TestU01, ..." and when available.
+------------------------------------------------------------------------------------------------------------------------------------------—+
CppRandLib class initial PCG algo name ([7]) Memory Usage Period time-64 bits SmallCrush fails Crush fails BigCrush fails
Pcg64_32 PCG XSH RS 64/32 (LCG) 2 x 4-bytes 2^64 0.79 0 0 0
Pcg128_64 PCG XSL RR 128/64 (LCG) 4 x 4-bytes 2^128 1.70 0 0 0
Pcg1024_32 PCG XSH RS 64/32 (EXT 1024) 1026 x 4-bytes 2^32,830 0.78 0 0 0
+------------------------------------------------------------------------------------------------------------------------------------------—+
small crush is a small set of simple tests that quickly tests some of the expected characteristics for a pretty good PRNG;
crush is a bigger set of tests that test more deeply expected random characteristics;
big crush is the ultimate set of difficult tests that any GOOD PRNG should definitively pass.
Constructor & Destructor Documentation
Pcg1024_32() [1/9]
Pcg1024_32::Pcg1024_32 () noexcept
Default empty constructor.
Empty constructor.
References seed().
Pcg1024_32() [2/9]
Pcg1024_32::Pcg1024_32 (const int seed_) noexcept
Valued constructor (int).
Valued constructor (int).
References seed().
Pcg1024_32() [3/9]
Pcg1024_32::Pcg1024_32 (const unsigned int seed_) noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References seed().
Pcg1024_32() [4/9]
Pcg1024_32::Pcg1024_32 (const long seed_) noexcept
Valued constructor (long)
Valued constructor (long).
References seed().
Pcg1024_32() [5/9]
Pcg1024_32::Pcg1024_32 (const unsigned long seed_) noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References seed().
Pcg1024_32() [6/9]
Pcg1024_32::Pcg1024_32 (const long long seed_) noexcept
Valued constructor (long long).
Valued constructor (long long).
References seed().
Pcg1024_32() [7/9]
Pcg1024_32::Pcg1024_32 (const unsigned long long seed_) noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References seed().
Pcg1024_32() [8/9]
Pcg1024_32::Pcg1024_32 (const utils::UInt128 & seed_) noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References seed().
Pcg1024_32() [9/9]
Pcg1024_32::Pcg1024_32 (const double seed_)
Valued constructor (double).
Valued constructor (double).
References seed().
Member Function Documentation
_setstate() [1/2]
void Pcg1024_32::_setstate (const std::uint64_t seed_) override virtual noexcept
Sets the internal state with a 64-bits integer seed.
Sets the internal state with an integer seed.
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
_setstate() [2/2]
void Pcg1024_32::_setstate (const utils::UInt128 & seed_) override virtual noexcept
Sets the internal state with a 128-bits integer seed.
Sets the internal state with an UInt128 seed.
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
next()
const Pcg1024_32::output_type Pcg1024_32::next () override virtual noexcept
The internal PRNG algorithm.
The internal PRNG algorithm.
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
seed() [1/9]
void Pcg1024_32::seed () inline override virtual noexcept
Initializes internal state (empty signature).
Initializes internal state (empty signature).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>::seed().
Referenced by Pcg1024_32(), Pcg1024_32(), Pcg1024_32(), Pcg1024_32(), Pcg1024_32(), Pcg1024_32(), Pcg1024_32(), Pcg1024_32(), Pcg1024_32(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
void Pcg1024_32::seed (const double seed_) virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [3/9]
void Pcg1024_32::seed (const int seed_) virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References seed().
seed() [4/9]
void Pcg1024_32::seed (const long long seed_) virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References seed().
seed() [5/9]
void Pcg1024_32::seed (const long seed_) virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References seed().
seed() [6/9]
void Pcg1024_32::seed (const unsigned int seed_) virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References seed().
seed() [7/9]
void Pcg1024_32::seed (const unsigned long long seed_) virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [8/9]
void Pcg1024_32::seed (const unsigned long seed_) virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References seed().
seed() [9/9]
void Pcg1024_32::seed (const utils::UInt128 & seed_) virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< StateT, OutputT, 8 *sizeof(OutputT)>::seed().
The documentation for this class was generated from the following files:
pcg1024_32.h
pcg1024_32.cpp