CppRandLib - c++11: utils::SplitMix64 Class Reference
utils::SplitMix64 Class Reference
Splittable pseudorandom number generators
The splitting and mixing algorithm used to initialize 64-bits internal states of PRNGs.
#include <splitmix.h>
Public Member Functions
const std::uint64_t operator() () noexcept
Evaluates next pseudorandom value.
SplitMix64 () noexcept
Empty constructor, uses current time to initialize the internal state.
SplitMix64 (const int seed) noexcept
Valued constructor - 32-bits integer.
SplitMix64 (const long long seed) noexcept
Valued constructor - 64-bits integer.
SplitMix64 (const long seed) noexcept
Valued constructor - 32-bits integer.
SplitMix64 (const unsigned int seed) noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix64 (const unsigned long long seed) noexcept
Valued constructor - 64-bits unsigned integer.
SplitMix64 (const unsigned long seed) noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix64 (const utils::UInt128 &seed) noexcept
Valued constructor - 128-bits unsigned integer.
SplitMix64 (double seed)
Valued constructor - double in range [0.0, 1.0).
Detailed Description
The splitting and mixing algorithm used to initialize 64-bits internal states of PRNGs.
This method is used to split and mix bits of 64-bits integers. It is internally used in CppRandLib to initialize internal state of PRNGs. It implements the 64-bits version of the Fast Splittable Pseudorandom Number Generators proposed by Steele Jr, Guy L., Doug Lea, and Christine H. Flood in "Fast splittable pseudorandom number generators.", in ACM SIGPLAN Notices 49.10 (2014): pp. 453-472.
It uses the Gamma method inited by Sebastiano Vigna (vigna.nosp@m.@acm.nosp@m..org) in 2015, provided under the Creative Commons license and modified under the same license by D. Lemire by Aug. 2017. (see https://github.com/lemire/testingRNG/blob/master/source/splitmix64.h).
It SHOULD NOT BE USED as a generic PRNG due to is randomness big limitations.
Constructor & Destructor Documentation
SplitMix64() [1/9]
utils::SplitMix64::SplitMix64 () inline noexcept
Empty constructor, uses current time to initialize the internal state.
References utils::get_time_us().
Referenced by utils::SplitMix31::SplitMix31(), utils::SplitMix31::SplitMix31(), utils::SplitMix32::SplitMix32(), utils::SplitMix32::SplitMix32(), utils::SplitMix63::SplitMix63(), and utils::SplitMix63::SplitMix63().
SplitMix64() [2/9]
utils::SplitMix64::SplitMix64 (const int seed) inline noexcept
Valued constructor - 32-bits integer.
SplitMix64() [3/9]
utils::SplitMix64::SplitMix64 (const unsigned int seed) inline noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix64() [4/9]
utils::SplitMix64::SplitMix64 (const long seed) inline noexcept
Valued constructor - 32-bits integer.
SplitMix64() [5/9]
utils::SplitMix64::SplitMix64 (const unsigned long seed) inline noexcept
Valued constructor - 32-bits unsigned integer.
SplitMix64() [6/9]
utils::SplitMix64::SplitMix64 (const long long seed) inline noexcept
Valued constructor - 64-bits integer.
SplitMix64() [7/9]
utils::SplitMix64::SplitMix64 (const unsigned long long seed) inline noexcept
Valued constructor - 64-bits unsigned integer.
SplitMix64() [8/9]
utils::SplitMix64::SplitMix64 (const utils::UInt128 & seed) inline noexcept
Valued constructor - 128-bits unsigned integer.
SplitMix64() [9/9]
utils::SplitMix64::SplitMix64 (double seed) inline
Valued constructor - double in range [0.0, 1.0).
Member Function Documentation
operator()()
const std::uint64_t utils::SplitMix64::operator() () noexcept
Evaluates next pseudorandom value.
Referenced by utils::SplitMix63::operator()().
The documentation for this class was generated from the following files:
splitmix.h
splitmix.cpp