CppRandLib - c++11: Squares counter-based pseudorandom Generators algorithm
Squares counter-based pseudorandom Generators algorithm
Classes
class BaseSquares< OutputT >
The base class for all Squares counter-based pseudorandom Generators.
class Squares32
Squares pseudo-random Generators dedicated to 64-bits calculations and 32-bits output values with small period (min 2^64, i.e. 1.84e+19).
class Squares64
Squares pseudo-random Generators dedicated to 64-bits calculations and 64-bits output values with small period (min 2^64, i.e. 1.84e+19).
Functions
virtual void BaseSquares< OutputT >::_setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void BaseSquares< OutputT >::_setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseSquares< OutputT >::BaseSquares () noexcept
Default empty constructor.
BaseSquares< OutputT >::BaseSquares (const double seed)
Valued constructor (double).
BaseSquares< OutputT >::BaseSquares (const int seed) noexcept
Valued constructor (int).
BaseSquares< OutputT >::BaseSquares (const long long seed) noexcept
Valued constructor (long long).
BaseSquares< OutputT >::BaseSquares (const long seed) noexcept
Valued constructor (long)
BaseSquares< OutputT >::BaseSquares (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseSquares< OutputT >::BaseSquares (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseSquares< OutputT >::BaseSquares (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseSquares< OutputT >::BaseSquares (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseSquares< OutputT >::BaseSquares (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void BaseSquares< OutputT >::seed () noexcept
Initializes internal state (empty signature).
void BaseSquares< OutputT >::seed (const double seed_)
Initializes internal state (double).
void BaseSquares< OutputT >::seed (const int seed_) noexcept
Initializes internal state (int).
void BaseSquares< OutputT >::seed (const long long seed_) noexcept
Initializes internal state (long long).
void BaseSquares< OutputT >::seed (const long seed_) noexcept
Initializes internal state (long)
void BaseSquares< OutputT >::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void BaseSquares< OutputT >::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void BaseSquares< OutputT >::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void BaseSquares< OutputT >::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
This is the group for all the CppRandLib implementations of the
Squares counter-based pseudorandom Generators (Squares) algorithm.
Squares models are based on an incremented counter and a key. The algorithm squares a combination of the counter and the key values, and exchanges the upper and lower bits of the combination, the whole repeated a number of times (4 to 5 rounds). Output values are provided on 32-bits or on 64-bits according to the model.
Function Documentation
_setstate() [1/2]
template<typename OutputT> void BaseSquares< OutputT >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
Referenced by seed().
_setstate() [2/2]
template<typename OutputT> void BaseSquares< OutputT >::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
BaseSquares() [1/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares () inline noexcept
Default empty constructor.
Empty constructor.
References BaseSquares(), and BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
Referenced by BaseSquares().
BaseSquares() [2/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const double seed_) inline
Valued constructor (double).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [3/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [4/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [5/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [6/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::setstate().
BaseSquares() [7/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [8/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [9/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
BaseSquares() [10/10]
template<typename OutputT> BaseSquares< OutputT >::BaseSquares (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (unsigned 128-bits).
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [1/9]
template<typename OutputT> void BaseSquares< OutputT >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References _setstate(), and utils::set_random_seed64().
seed() [2/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const double seed_) inline virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [3/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const int seed_) inline virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [4/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const long long seed_) inline virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [5/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const long seed_) inline virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [6/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [7/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [8/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().
seed() [9/9]
template<typename OutputT> void BaseSquares< OutputT >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>.
References BaseRandom< CounterKeyState, OutputT, 8 *sizeof(OutputT)>::seed().