CppRandLib - c++11: Bits rotation utility on unsigned integers
Bits rotation utility on unsigned integers
Functions
template<typename IntT>
const IntT utils::rot_left (const IntT value, const int rot_count, const int BITS_COUNT=8 *sizeof(IntT))
Left bits rotation on unsigned integers.
Detailed Description
Function Documentation
rot_left()
template<typename IntT> const IntT utils::rot_left (const IntT value, const int rot_count, const int BITS_COUNT = 8 * sizeof(IntT)) inline
Left bits rotation on unsigned integers.
Referenced by Xoroshiro1024::next(), Xoroshiro256::next(), and Xoroshiro512::next().