CppRandLib - c++11: algos: BaseRandom - Base class for all PRNGs (Pseudo Random Numbers Generators)
algos: BaseRandom - Base class for all PRNGs (Pseudo Random Numbers Generators)
Classes
class BaseRandom< StateT, OutputT, OUTPUT_BITS >
This is the base class for all pseudo-random numbers generators.
Functions
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::betavariate (const double alpha, const double beta)
Beta distribution.
template<typename CountT, typename ProbaT>
const CountT BaseRandom< StateT, OutputT, OUTPUT_BITS >::binomialvariate (CountT n=1, const ProbaT p=ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
template<typename T, const std::size_t n>
const T & BaseRandom< StateT, OutputT, OUTPUT_BITS >::choice (const std::array< T, n > &seq)
Chooses a random element from a non-empty sequence (std::array).
template<typename T>
const T & BaseRandom< StateT, OutputT, OUTPUT_BITS >::choice (const std::vector< T > &seq)
Chooses a random element from a non-empty sequence (std::vector).
template<typename T>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices (const std::vector< T > &population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
template<typename T, typename C>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices (const std::vector< T > &population, std::vector< C > &weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
template<typename T, typename C>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices_cum (const std::vector< T > &population, const std::vector< C > &cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::expovariate (const double lambda=1.0)
Exponential distribution.
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gauss () noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::lognormvariate ()
Default Log normal distribution (mean=0.0, stdev=1.0).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::lognormvariate (const double mu, const double sigma)
Log normal distribution (mean=mu, stdev=sigma).
template<typename T, const std::size_t n>
std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate ()
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
template<typename T, const std::size_t m, typename U = T, const std::size_t n = m>
std::array< T, m > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::array< U, n > &max)
Returns an array of min(m, n) values in range [0; max[i]).
template<typename T, const std::size_t m, typename U = T, const std::size_t n = m, typename V = U, const std::size_t p = n>
std::array< T, m > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::array< U, n > &min, const std::array< V, p > &max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
template<typename T>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::size_t n)
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
template<typename T, typename U = T>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
template<typename T, typename U = T>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::vector< U > &max)
Returns a vector of n values in range [0; max[i]).
template<typename T, typename U = T, typename V = U>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::vector< U > &min, const std::vector< V > &max)
Returns a vector of n values in range [min[i]; max[i]).
template<typename T, const std::size_t n, typename U = T>
std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
template<typename T, const std::size_t n, typename U = T, typename V = U>
std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::normalvariate ()
Normal distribution (mean=0.0, stdev=1.0).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::normalvariate (const double mu, const double sigma)
Normal distribution (mean=mu, stdev=sigma).
template<typename T, const std::size_t n>
std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::array< T, n > &max)
Valued call operator (1 std::array of scalars).
template<typename T, const std::size_t n>
std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::array< T, n > &min, const std::array< T, n > &max)
Valued call operator (2 std::array of scalars).
template<typename T>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::vector< T > &max)
Valued call operator (1 std::vector of scalars).
template<typename T>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::vector< T > &min, const std::vector< T > &max)
Valued call operator (2 std::vector of scalars).
template<typename T = OutputT>
const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T max)
Valued call operator (1 scalar).
template<typename T = OutputT>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
template<typename T = OutputT>
std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::paretovariate (const double alpha)
Pareto distribution.
std::vector< std::uint8_t > BaseRandom< StateT, OutputT, OUTPUT_BITS >::randbytes (const std::size_t n)
Generates n random bytes.
template<typename T>
const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::randint (const T a, const T b)
Returns random integer in range [a, b], including both end points.
template<typename T, typename S = T>
const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::randrange (const T start, const T stop, const S step=S(1))
Returns a random value in range [start, stop) with specified step.
template<typename T, const std::size_t k, const std::size_t n>
void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::array< T, k > &out, const std::array< T, n > &population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
template<typename T, typename C, const std::size_t k, const std::size_t n>
void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::array< T, k > &out, const std::array< T, n > &population, const std::array< C, n > &counts)
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
template<typename T>
void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::vector< T > &out, const std::vector< T > &population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
template<typename T, typename C>
void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::vector< T > &out, const std::vector< T > &population, const std::vector< C > &counts, const std::size_t k)
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed () noexcept
Initializes internal state (empty signature).
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const double seed_)
Initalizes internal state from a double seed.
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const int seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const long long seed_) noexcept
Initializes internal state from a 64-bits signed integer seed.
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const long seed_) noexcept
Initializes internal state from a 32-bits signed integer seed.
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned int seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned long long seed_) noexcept
Initializes internal state from a 64-bits unsigned integer seed.
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned long seed_) noexcept
Initializes internal state from a 32-bits unsigned integer seed.
virtual void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const utils::UInt128 &seed_) noexcept
Initializes the internal state of this PRNG with a 128-bits integer seed.
void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const StateT &new_internal_state) noexcept
Sets the internal state from a new internal state content.
void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const StateT &new_internal_state, const double gauss_next) noexcept
Sets the internal state from a new internal state content and with gauss_next.
void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const struct _InternalState &new_internal_state) noexcept
Restores internal state from object returned by getstate().
template<typename ContainerType>
void BaseRandom< StateT, OutputT, OUTPUT_BITS >::shuffle (ContainerType &seq)
Shuffles specified sequence in place.
const state_type BaseRandom< StateT, OutputT, OUTPUT_BITS >::state () const noexcept
Returns the current internal state value.
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular () noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
template<typename T = double>
const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform ()
Uniform distribution in [0.0, 1.0).
template<typename T = double, typename U = T>
const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform (const U max)
Uniform distribution in [0.0, max).
template<typename T, typename U = T, typename V = U>
const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform (const U min, const V max)
Uniform distribution in [min, max).
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::weibullvariate (const double alpha, const double beta)
Weibull distribution.
Variables
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::BPF { 53 }
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::E { std::exp(1.0) }
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::GAUSS_NULL = -1.0
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::LOG4 { std::log(4.0) }
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::NV_MAGICCONST { 4 * std::exp(-0.5) / std::sqrt(2.0) }
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::PI { 3.14159265358979323846 }
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::RECIP_BPF { std::exp2(-BPF) }
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::SG_MAGICCONST { 1.0 + std::log(4.5) }
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS>
const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::TWO_PI { 2.0 * BaseRandom<StateT, OutputT, OUTPUT_BITS>::PI }
Detailed Description
This is the definition of the base class for all pseudo-random numbers generators that are implemented in CppRandLib.
Function Documentation
betavariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::betavariate (const double alpha, const double beta)
Beta distribution.
Parameters
alpha double, must be greater than 0
beta double, must be greater than 0
Returns
a value in interval [0.0, 1.0].
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++. The original code is due to Janne Sinkkonen and matches all the std texts (e.g., Knuth Vol 2 Ed 3 pg 134 "the beta distribution").
Beta distribution.
References gammavariate().
binomialvariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename CountT, typename ProbaT> const CountT BaseRandom< StateT, OutputT, OUTPUT_BITS >::binomialvariate (CountT n = 1, const ProbaT p = ProbaT(0.5))
Returns the number of successes for n>=0 independent trials.
Returns the number of successes for n>=0 independent trials.
References uniform().
choice() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n> const T & BaseRandom< StateT, OutputT, OUTPUT_BITS >::choice (const std::array< T, n > & seq)
Chooses a random element from a non-empty sequence (std::array).
Chooses a random element from a non-empty sequence (std::array).
References uniform().
choice() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> const T & BaseRandom< StateT, OutputT, OUTPUT_BITS >::choice (const std::vector< T > & seq)
Chooses a random element from a non-empty sequence (std::vector).
Chooses a random element from a non-empty sequence (std::vector).
References uniform().
choices() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices (const std::vector< T > & population, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (same weights).
Returns a k sized vector of elements chosen from the population with replacement (same weights).
References choices_cum().
choices() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename C> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices (const std::vector< T > & population, std::vector< C > & weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
Returns a k sized vector of elements chosen from the population with replacement (individual weights).
References choices_cum().
choices_cum()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename C> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::choices_cum (const std::vector< T > & population, const std::vector< C > & cum_weights, const std::size_t k)
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
Returns a k sized vector of elements chosen from the population with replacement (cumulative weights).
Referenced by choices(), and choices().
expovariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::expovariate (const double lambda = 1.0)
Exponential distribution.
Parameters
lambda double, this should get the value (1.0 / desired_mean). It cannot be 0.0.
Returns
a value in range [0.0, Infinity) if lambda is positive, or a value in range (-Infinity, 0.0] if lambda is negative.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Exponential distribution.
References uniform().
gammavariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gammavariate (const double alpha, const double beta)
Gamma distribution. This is NOT the gamma function!
The probability distribution function is : x^(alpha - 1) * std::exp(-x / beta) pdf(x) = --------------------------------— std::tgamma(alpha) * beta^alpha where: pdf is the probability density function a^b is std::pow(a, b) std::tgamma() is the Gamma funtion as implemented in the c++ math library.
The Gamma function is the below integral summation from 0 to Infinity: (x) = 0 t^(x1) * std::exp(t) dt
Parameters
alpha : double, the shape parameter - must be greater than 0.0.
beta : double, the scale parameter - must be greater than 0.0. With these two arguments: mean is alpha * beta and variance is alpha * beta * beta
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++. As such, some comments present in the Python original code have been copied as is in this c++ implementation, naming then the authors of the related parts of code.
Gamma distribution. This is NOT the gamma function!
References uniform().
Referenced by betavariate().
gauss() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gauss () inline noexcept
Default Gaussian distribution (mean=0.0, stdev=1.0).
This is slightly faster than the normalvariate() function. Notice: not thread-safe without a lock around calls.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Default Gaussian distribution (mean=0.0, stdev=1.0).
References gauss().
Referenced by gauss().
gauss() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::gauss (const double mu, const double sigma)
Gaussian distribution (mean=mu, stdev=sigma).
mu is the mean, and sigma is the standard deviation. mu can be any value, sigma must be greater than 0.0. This is slightly faster than the normalvariate() function.
Notice: not thread-safe without a mutex around calls.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Gaussian distribution (mean=mu, stdev=sigma).
References uniform().
lognormvariate() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::lognormvariate () inline
Default Log normal distribution (mean=0.0, stdev=1.0).
If you take the natural logarithm of this distribution, you'll get a normal distribution with mean 0.0 and standard deviation 1.0.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Default Log normal distribution (mean=0.0, stdev=1.0).
References lognormvariate().
Referenced by lognormvariate().
lognormvariate() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::lognormvariate (const double mu, const double sigma) inline
Log normal distribution (mean=mu, stdev=sigma).
If you take the natural logarithm of this distribution, you'll get a normal distribution with mean mu and standard deviation sigma. mu can have any value, and sigma must be greater than zero.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Log normal distribution (mean=mu, stdev=sigma).
References normalvariate().
n_evaluate() [1/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate () inline
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
Returns an array of n values that are uniformly contained within range [0.0, 1.0).
References uniform().
n_evaluate() [2/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t m, typename U, const std::size_t n> std::array< T, m > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::array< U, n > & max)
Returns an array of min(m, n) values in range [0; max[i]).
Returns an array of min(m, n) values in range [0; max[i]).
References uniform().
n_evaluate() [3/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t m, typename U, const std::size_t n, typename V, const std::size_t p> std::array< T, m > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::array< U, n > & min, const std::array< V, p > & max)
Returns an array min(m, n, p) values in range [min[i]; max[i]).
Returns an array min(m, n, p) values in range [min[i]; max[i]).
References uniform().
n_evaluate() [4/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::size_t n) inline
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
Returns a vector of n values that are uniformly contained within range [0.0, 1.0).
n_evaluate() [5/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::size_t n, const U max)
Returns a vector of n values that are uniformly contained within range [0, max).
Returns a vector of n values that are uniformly contained within range [0, max).
References uniform().
n_evaluate() [6/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::vector< U > & max)
Returns a vector of n values in range [0; max[i]).
Returns a vector of n values in range [0; max[i]).
References uniform().
n_evaluate() [7/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U, typename V> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const std::vector< U > & min, const std::vector< V > & max)
Returns a vector of n values in range [min[i]; max[i]).
Returns a vector of n values in range [min[i]; max[i]).
References uniform().
n_evaluate() [8/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n, typename U> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const U max)
Returns an array of n values that are uniformly contained within range [0, max).
Returns an array of n values that are uniformly contained within range [0, max).
References uniform().
n_evaluate() [9/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n, typename U, typename V> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::n_evaluate (const U min, const V max)
Returns an array of n values that are uniformly contained within range [min, max).
Returns an array of n values that are uniformly contained within range [min, max).
References uniform().
normalvariate() [1/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::normalvariate () inline
Normal distribution (mean=0.0, stdev=1.0).
The Python version of this method uses Kindermanand Monahan method. Reference: Kinderman, A.J.and Monahan, J.F., "Computer generation of random variables using the ratio of uniform deviates", ACM Trans Math Software, 3, (1977), pp257 - 260. This method is slightlly slower than the gauss method. Furthermore, we've s lightly modified the original algorithm here to fulfill very special cases that might happen in very specific conditions. This slows down also the running of normalvariate() in these very specific conditions. You should prefer then to use method gauss() instead of this one.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Normal distribution (mean=0.0, stdev=1.0).
References normalvariate().
Referenced by lognormvariate(), and normalvariate().
normalvariate() [2/2]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::normalvariate (const double mu, const double sigma) inline
Normal distribution (mean=mu, stdev=sigma).
mu is the mean, and sigma is the standard deviation. mu can be any value, sigma must be greater than 0.0.
The Python version of this method uses Kindermanand Monahan method. Reference: Kinderman, A.J.and Monahan, J.F., "Computer generation of random variables using the ratio of uniform deviates", ACM Trans Math Software, 3, (1977), pp257 - 260. This method is slightlly slower than the gauss method. Furthermore, we've s lightly modified the original algorithm here to fulfill very special cases that might happen in very specific conditions. This slows down also the running of normalvariate() in these very specific conditions. You should prefer then to use method gauss() instead of this one.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Normal distribution (mean=mu, stdev=sigma).
References uniform().
operator()() [1/7]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::array< T, n > & max)
Valued call operator (1 std::array of scalars).
Returns
an array of values that are uniformly contained within the interval [0; max[i]) – i being the index of the value in the returned array.
Valued call operator (1 std::array of scalars).
References uniform().
operator()() [2/7]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t n> std::array< T, n > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::array< T, n > & min, const std::array< T, n > & max)
Valued call operator (2 std::array of scalars).
Returns
an array of values that are uniformly contained within the interval [min[i]; max[i]) - i being the index of the value in the returned array.
Valued call operator (2 std::array of scalars).
References uniform().
operator()() [3/7]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::vector< T > & max)
Valued call operator (1 std::vector of scalars).
Returns
a vector of values that are uniformly contained within the interval [0; max[i]) – i being the index of the value in the returned vector.
Valued call operator (1 std::vector of scalars).
References uniform().
operator()() [4/7]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const std::vector< T > & min, const std::vector< T > & max)
Valued call operator (2 std::vector of scalars).
Returns
a vector of values that are uniformly contained within the interval [min[i]; max[i]) - i being the index of the value in the returned vector.
Valued call operator (2 std::vector of scalars).
References uniform().
operator()() [5/7]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T max)
Valued call operator (1 scalar).
Returns
a value that is uniformly contained within range [0; max).
Valued call operator (1 scalar).
References uniform().
operator()() [6/7]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T max, const std::size_t n)
Valued call operator (max and n scalars).
Returns
a vector of n values that are uniformly contained within range [0; max).
Valued call operator (max and n scalars).
References uniform().
operator()() [7/7]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> std::vector< T > BaseRandom< StateT, OutputT, OUTPUT_BITS >::operator() (const T min, const T max, const std::size_t n)
Valued call operator (min, max and n scalars).
Returns
a vector of n values that are uniformly contained within range [min; max).
Valued call operator (min, max and n scalars).
References uniform().
paretovariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::paretovariate (const double alpha)
Pareto distribution.
Parameters
alpha double, the shape parameter. Cannot be 0.0.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Pareto distribution.
References uniform().
randbytes()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> std::vector< std::uint8_t > BaseRandom< StateT, OutputT, OUTPUT_BITS >::randbytes (const std::size_t n) inline
Generates n random bytes.
This method should not be used for generating security tokens.
Generates n random bytes.
References uniform().
randint()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::randint (const T a, const T b) inline
Returns random integer in range [a, b], including both end points.
Template argument T must be an integral type.
Returns a random integer in range [a, b], including both end points.
References uniform().
randrange()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename S> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::randrange (const T start, const T stop, const S step = S(1))
Returns a random value in range [start, stop) with specified step.
Template arguments T and S must be arithmetic types.
Returns a random value in range [start, stop) with specified step.
References uniform().
sample() [1/4]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, const std::size_t k, const std::size_t n> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::array< T, k > & out, const std::array< T, n > & population)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
Evaluates a vector containing elements from the population while leaving the original population unchanged. The resulting list is in selection order so that all sub-slices will also be valid random samples. This allows raffle winners (the sample) to be partitioned into grand prize and second place winners (the subslices).
Members of the population need not be unique. If the population contains repeats, then each occurrence is a possible selection in the sample. Notice: k must be greater than n.
Chooses k unique random elements from a population sequence (out std::array<>, in std::array<>, default count per element = 1).
References uniform().
sample() [2/4]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename C, const std::size_t k, const std::size_t n> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::array< T, k > & out, const std::array< T, n > & population, const std::array< C, n > & counts) inline
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
Evaluates an array containing k elements from the population while leaving the original population unchanged. The resulting list is in selection order so that all sub-slices will also be valid random samples. This allows raffle winners (the sample) to be partitioned into grand prize and second place winners (the subslices).
Members of the population need not be unique. If the population contains repeats, then each occurrence is a possible selection in the sample.
Repeated elements are specified by the counts parameter. For example: std::array<char*, 5> out; sample(out, std::array<char*, 2>{"red", "blue"}, std::array<int,2>{4, 2}); is equivalent to: sample(out, std::array<char*, 6>{"red", "red", "red", "red", "blue", "blue"});
Chooses k unique random elements from a population sequence (std::array<>, with counts array).
References uniform().
sample() [3/4]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::vector< T > & out, const std::vector< T > & population, const std::size_t k)
Chooses k unique random elements from a population sequence. All population elements have same weight for the sampling and are each chosen only once.
Evaluates a vector containing elements from the population while leaving the original population unchanged. The resulting list is in selection order so that all sub-slices will also be valid random samples. This allows raffle winners (the sample) to be partitioned into grand prize and second place winners (the subslices).
Members of the population need not be unique. If the population contains repeats, then each occurrence is a possible selection in the sample.
Chooses k unique random elements from a population sequence (out std::vector, in container, default count per element = 1).
References uniform().
sample() [4/4]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename C> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::sample (std::vector< T > & out, const std::vector< T > & population, const std::vector< C > & counts, const std::size_t k) inline
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
Evaluates a vector containing elements from the population while leaving the original population unchanged. The resulting list is in selection order so that all sub-slices will also be valid random samples. This allows raffle winners (the sample) to be partitioned into grand prize and second place winners (the subslices).
Members of the population need not be unique. If the population contains repeats, then each occurrence is a possible selection in the selection in the sample.
Repeated elements are specified by the counts parameter. For example: sample({"red", "blue"}, {4, 2}, 5); is equivalent to: sample({"red", "red", "red", "red", "blue", "blue"}, 5);
Chooses k unique random elements from a population sequence (std::vector<>, with counts vector).
References uniform().
seed() [1/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Uses an integer value evaluated from shuffled and xored current time as seed.
Initializes internal state (empty signature).
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed(), and utils::set_random_seed64().
Referenced by seed(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const double seed_) inline virtual
Initalizes internal state from a double seed.
Initalizes internal state from a double seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [3/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const int seed_) inline virtual noexcept
Initializes internal state from a 32-bits signed integer seed.
Initializes internal state from a 32-bits signed integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [4/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const long long seed_) inline virtual noexcept
Initializes internal state from a 64-bits signed integer seed.
Initializes internal state from a 64-bits signed integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [5/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const long seed_) inline virtual noexcept
Initializes internal state from a 32-bits signed integer seed.
Initializes internal state from a 32-bits signed integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [6/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state from a 32-bits unsigned integer seed.
Initializes internal state from a 32-bits unsigned integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References seed().
seed() [7/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state from a 64-bits unsigned integer seed.
Initializes internal state from a 64-bits unsigned integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References _setstate().
seed() [8/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state from a 32-bits unsigned integer seed.
Initializes internal state from a 32-bits unsigned integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References _setstate().
seed() [9/9]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes the internal state of this PRNG with a 128-bits integer seed.
Initializes the internal state of this PRNG with a 128-bits integer seed.
Reimplemented in BaseCWG< ValueType, StateValueType, OutputType, OUTPUT_BITS >, BaseCWG< std::uint64_t, std::uint64_t, std::uint64_t, 64 >, BaseCWG< std::uint64_t, utils::UInt128, std::uint64_t, 64 >, BaseCWG< utils::UInt128, utils::UInt128, utils::UInt128, 128 >, BaseLFib64< SIZE, K >, BaseLFib64< 1279, 861 >, BaseLFib64< 17, 5 >, BaseLFib64< 55, 24 >, BaseLFib64< 607, 273 >, BaseMELG< SIZE >, BaseMELG< 10 >, BaseMELG< 312 >, BaseMELG< 696 >, BaseMRG31< SIZE >, BaseMRG31< 1597 >, BaseMRG31< 47 >, BaseMRG32< SIZE >, BaseMRG32< 256 >, BaseSquares< OutputT >, BaseSquares< std::uint32_t >, BaseSquares< std::uint64_t >, BaseWell< SIZE >, BaseWell< 1391 >, BaseWell< 16 >, BaseWell< 32 >, BaseWell< 624 >, BaseXoroshiro< SIZE >, BaseXoroshiro< 16 >, BaseXoroshiro< 4 >, BaseXoroshiro< 8 >, Cwg128, Cwg128_64, Cwg64, FastRand32, FastRand63, Melg19937, Melg44497, Melg607, Pcg1024_32, Pcg128_64, and Pcg64_32.
References _setstate().
setstate() [1/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const StateT & new_internal_state) inline noexcept
Sets the internal state from a new internal state content.
Sets the internal state from a new internal state content.
setstate() [2/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const StateT & new_internal_state, const double gauss_next) inline noexcept
Sets the internal state from a new internal state content and with gauss_next.
Sets the internal state from a new internal state content and with gauss_next.
setstate() [3/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::setstate (const struct _InternalState & new_internal_state) inline noexcept
Restores internal state from object returned by getstate().
Restores internal state from object returned by getstate().
Referenced by Squares32::Squares32(), and Squares64::Squares64().
shuffle()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename ContainerType> void BaseRandom< StateT, OutputT, OUTPUT_BITS >::shuffle (ContainerType & seq)
Shuffles specified sequence in place.
The Container type must be either std::vector or std::array.
Shuffles specified sequence in place.
References uniform().
state()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const StateT BaseRandom< StateT, OutputT, OUTPUT_BITS >::state () const inline noexcept
Returns the current internal state value.
Returns the current internal state value.
triangular() [1/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular () inline noexcept
Triangular distribution (low=0.0, high=1.0, mode=0.5).
Triangular distribution (low=0.0, high=1.0, mode=0.5).
References triangular().
Referenced by triangular(), and triangular().
triangular() [2/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular (const double low, const double high) noexcept
Triangular distribution (low, high, default mode).
Triangular distribution (low, high, default mode).
References triangular().
triangular() [3/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::triangular (const double low, const double high, const double mode) noexcept
Triangular distribution (low, high, mode).
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++.
Triangular distribution (low, high, mode).
References uniform().
uniform() [1/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform () inline
Uniform distribution in [0.0, 1.0).
Uniform distribution in [0.0, 1.0).
References random().
Referenced by binomialvariate(), choice(), choice(), expovariate(), gammavariate(), gauss(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), n_evaluate(), normalvariate(), operator()(), operator()(), operator()(), operator()(), operator()(), operator()(), operator()(), paretovariate(), randbytes(), randint(), randrange(), sample(), sample(), sample(), sample(), shuffle(), triangular(), vonmisesvariate(), and weibullvariate().
uniform() [2/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform (const U max) inline
Uniform distribution in [0.0, max).
Uniform distribution in [0.0, max).
References random().
uniform() [3/3]
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> template<typename T, typename U, typename V> const T BaseRandom< StateT, OutputT, OUTPUT_BITS >::uniform (const U min, const V max) inline
Uniform distribution in [min, max).
Uniform distribution in [min, max).
References random().
vonmisesvariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::vonmisesvariate (const double mu, const double kappa)
Circular data distribution.
Parameters
mu is the mean angle, expressed in radians between 0 and 2*pi
kappa is the concentration parameter, which must be greater than or equal to zero. If kappa is equal to zero, this distribution reduces to a uniform random angle over the range 0 to 2*pi.
Important notice: the implemented code is a translation from Python https://github.com/python/cpython/blob/3.11/Lib/random.py into c++. As such, some comments present in the Python original code have been copied as is in this c++ implementation, naming then the authors of the related parts of code.
Circular data distribution.
References uniform().
weibullvariate()
template<typename StateT, typename OutputT, const std::uint8_t OUTPUT_BITS> const double BaseRandom< StateT, OutputT, OUTPUT_BITS >::weibullvariate (const double alpha, const double beta)
Weibull distribution.
Parameters
alpha double, the scale parameter.
beta double, the shape parameter. Must be non null.
Weibull distribution.
References uniform().