CppRandLib - c++11: algos: Xoroshiro - Scrambled Linear Pseudorandom Number generators
algos: Xoroshiro - Scrambled Linear Pseudorandom Number generators
Classes
class BaseXoroshiro< SIZE >
The base class for all Scrambled Linear Pseudorandom Number Generators based on 64-bits numbers.
class Xoroshiro1024
A very fast 64-bits Scrambled Linear Pseudorandom Number Generators with a very long period (1.80e+308)
class Xoroshiro256
A very fast 64-bits Scrambled Linear Pseudorandom Number Generators with a medium period (1.16e+77)
class Xoroshiro512
A fast 64-bits Scrambled Linear Pseudorandom Number Generators with a long period (1.34e+154)
Functions
virtual void BaseXoroshiro< SIZE >::_setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void BaseXoroshiro< SIZE >::_setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseXoroshiro< SIZE >::BaseXoroshiro () noexcept
Default empty constructor.
BaseXoroshiro< SIZE >::BaseXoroshiro (const double seed)
Valued constructor (double).
BaseXoroshiro< SIZE >::BaseXoroshiro (const int seed) noexcept
Valued constructor (int).
BaseXoroshiro< SIZE >::BaseXoroshiro (const long long seed) noexcept
Valued constructor (long long).
BaseXoroshiro< SIZE >::BaseXoroshiro (const long seed) noexcept
Valued constructor (long)
BaseXoroshiro< SIZE >::BaseXoroshiro (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseXoroshiro< SIZE >::BaseXoroshiro (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseXoroshiro< SIZE >::BaseXoroshiro (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseXoroshiro< SIZE >::BaseXoroshiro (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseXoroshiro< SIZE >::BaseXoroshiro (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void BaseXoroshiro< SIZE >::seed () noexcept
Initializes internal state (empty signature).
void BaseXoroshiro< SIZE >::seed (const double seed_)
Initializes internal state (double).
void BaseXoroshiro< SIZE >::seed (const int seed_) noexcept
Initializes internal state (int).
void BaseXoroshiro< SIZE >::seed (const long long seed_) noexcept
Initializes internal state (long long).
void BaseXoroshiro< SIZE >::seed (const long seed_) noexcept
Initializes internal state (long)
void BaseXoroshiro< SIZE >::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void BaseXoroshiro< SIZE >::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void BaseXoroshiro< SIZE >::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void BaseXoroshiro< SIZE >::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
This is the group for all the CppRandLib implementations of the Scrambled Linear Pseudorandom Number Generators (xoroshiro) algorithm.
The xoroshiro algorithm is a version of the Scrambled Linear Pseudorandom Number Generators. The xoroshiro linear transformation updates cyclically two words of a larger state array. The base xoroshiro linear transformation is obtained combining a rotation, a shift, and again a rotation. (extracted from the original paper, see reference [10] in file README.md)
An addition or a multiplication operation is internally applied also to the state of the PRNGs. Doubling the same operation has proven to enhance the randomness quality of the PRNG. This is the model of the algorithms that is implemeted in CppRandLib.
The implemented algorithms shortly escape from the zeroland (10 to 100 calls are enough to get equiprobability of bits 0 and 1 on 4 successive calls). The 256 version of the algorithm has nevertheless shown close repeats flaws, with a bad Hamming weight near zero. Xoroshiro512 seems to best fit this property. (see https://www.pcg-random.org/posts/xoshiro-repeat-flaws.html).
Function Documentation
_setstate() [1/2]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
_setstate() [2/2]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
BaseXoroshiro() [1/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro () inline noexcept
Default empty constructor.
Empty constructor.
References BaseXoroshiro(), and BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
Referenced by BaseXoroshiro().
BaseXoroshiro() [2/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const double seed_) inline
Valued constructor (double).
Valued constructor.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
BaseXoroshiro() [3/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
BaseXoroshiro() [4/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
BaseXoroshiro() [5/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
BaseXoroshiro() [6/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::setstate().
BaseXoroshiro() [7/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
BaseXoroshiro() [8/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
BaseXoroshiro() [9/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
BaseXoroshiro() [10/10]
template<const std::uint32_t SIZE> BaseXoroshiro< SIZE >::BaseXoroshiro (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
seed() [1/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
Referenced by seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed (const double seed_) inline virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
seed() [3/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed (const int seed_) inline virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [4/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed (const long long seed_) inline virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [5/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed (const long seed_) inline virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [6/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [7/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().
seed() [8/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References seed().
seed() [9/9]
template<const std::uint32_t SIZE> void BaseXoroshiro< SIZE >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t, 64 >::seed().