CppRandLib - c++11: Well-Equidistributed Long-period Linear Generators (WELL) algorithm
Well-Equidistributed Long-period Linear Generators (WELL) algorithm
Classes
class BaseWell< SIZE >
The base class for all WELL pseudo-random generators.
class Well1024a
A fast 32-bits Well-Equidistributed Long-period Linear generator with a large period (2^1,024, i.e. 1.80e+308).
class Well19937c
A fast 32-bits Well-Equidistributed Long-period Linear generator with a very large period (2^19,937, i.e. 4.32e+6,001).
class Well44497b
A fast 32-bits Well-Equidistributed Long-period Linear generator with a very large period (2^44,497, i.e. 15.1e+13,466).
class Well512a
A fast 32-bits Well-Equidistributed Long-period Linear generator with a large period (2^512, i.e. 1.34e+154).
Functions
static value_type BaseWell< SIZE >::_d (const value_type s) noexcept
static value_type BaseWell< SIZE >::_M0 (const value_type x=0) noexcept
static value_type BaseWell< SIZE >::_M1 (const value_type x) noexcept
static value_type BaseWell< SIZE >::_M2_neg (const value_type x, const value_type t) noexcept
static value_type BaseWell< SIZE >::_M2_pos (const value_type x, const value_type t) noexcept
static value_type BaseWell< SIZE >::_M3_neg (const value_type x, const value_type t) noexcept
static value_type BaseWell< SIZE >::_M3_pos (const value_type x, const value_type t) noexcept
static value_type BaseWell< SIZE >::_M4 (const value_type x, const value_type a) noexcept
static value_type BaseWell< SIZE >::_M5_neg (const value_type x, const value_type t, const value_type a) noexcept
static value_type BaseWell< SIZE >::_M5_pos (const value_type x, const value_type t, const value_type a) noexcept
static value_type BaseWell< SIZE >::_M6 (const value_type x, const value_type q, const value_type t, const value_type s, const value_type a) noexcept
virtual void BaseWell< SIZE >::_setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void BaseWell< SIZE >::_setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
static value_type BaseWell< SIZE >::_tempering (const value_type x, const value_type b, const value_type c) noexcept
BaseWell< SIZE >::BaseWell () noexcept
Default empty constructor.
BaseWell< SIZE >::BaseWell (const double seed)
Valued constructor (double).
BaseWell< SIZE >::BaseWell (const int seed) noexcept
Valued constructor (int).
BaseWell< SIZE >::BaseWell (const long long seed) noexcept
Valued constructor (long long).
BaseWell< SIZE >::BaseWell (const long seed) noexcept
Valued constructor (long)
BaseWell< SIZE >::BaseWell (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseWell< SIZE >::BaseWell (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseWell< SIZE >::BaseWell (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseWell< SIZE >::BaseWell (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseWell< SIZE >::BaseWell (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void BaseWell< SIZE >::seed () noexcept
Initializes internal state (empty signature).
void BaseWell< SIZE >::seed (const double seed_)
Initializes internal state (double).
void BaseWell< SIZE >::seed (const int seed_) noexcept
Initializes internal state (int).
void BaseWell< SIZE >::seed (const long long seed_) noexcept
Initializes internal state (long long).
void BaseWell< SIZE >::seed (const long seed_) noexcept
Initializes internal state (long)
void BaseWell< SIZE >::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void BaseWell< SIZE >::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void BaseWell< SIZE >::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void BaseWell< SIZE >::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
This is the group for all the CppRandLib implementations of the Well- Equidistributed Long-period Linear Generators pseudo-random generators (WELL) algorithm.
Well-Equidistributed Long-period Linear Generators (WELL) use linear recurrence based on primitive characteristic polynomials associated with left- and right- shifts and xor operations to fastly evaluate pseudo-random numbers suites.
WELLs offer large to very large periods with best known results in the evaluation of their randomness, as stated in the evaluation done by Pierre L'Ecuyer and Richard Simard (Universite de Montreal) in "TestU01: A C Library for Empirical Testing of Random Number Generators - ACM Transactions on Mathematical Software, vol.33 n.4, pp.22-40, August 2007". It is recommended to use such pseudo-random numbers generators rather than LCG ones for serious simulation applications. Furthermore, WELLs have proven their great ability to very fastly escape from zeroland.
Notice: the algorithm in the 4 different versions implemented here has been coded as a direct implementation of their descriptions in the initial paper "Improved Long-Period Generators Based on Linear Recurrences Modulo 2", Francois PANNETON and Pierre L'ECUYER (Universite de Montreal) and Makoto MATSUMOTO (Hiroshima University), in ACM Transactions on Mathematical Software, Vol. 32, No. 1, March 2006, Pages 1-16. (see https://www.iro.umontreal.ca/~lecuyer/myftp/papers/wellrng.pdf). So, only minimalist optimization has been coded, with the aim at easing the verification of its proper implementation.
Function Documentation
_setstate() [1/2]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
_setstate() [2/2]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::_setstate (const utils::UInt128 & seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
BaseWell() [1/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell () inline noexcept
Default empty constructor.
Empty constructor.
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseWell() [2/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseWell() [3/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseWell() [4/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseWell() [5/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseWell() [6/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::setstate().
BaseWell() [7/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor unsigned int).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseWell() [8/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseWell() [9/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
BaseWell() [10/10]
template<const std::uint32_t SIZE> BaseWell< SIZE >::BaseWell (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (128-bits integer).
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [1/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
Referenced by seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed (const double seed_) inline virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [3/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed (const int seed_) inline virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References seed().
seed() [4/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed (const long long seed_) inline virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References seed().
seed() [5/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed (const long seed_) inline virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References seed().
seed() [6/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References seed().
seed() [7/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().
seed() [8/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References seed().
seed() [9/9]
template<const std::uint32_t SIZE> void BaseWell< SIZE >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >.
References BaseRandom< ListSeedState< utils::SplitMix32, std::uint32_t, SIZE >, std::uint32_t, 32 >::seed().