CppRandLib - c++11: Maximally Equidistributed Long-period Linear Generators (MELG) algorithm
Maximally Equidistributed Long-period Linear Generators (MELG) algorithm
Classes
class BaseMELG< SIZE >
The base class for all Maximally Equidistributed Long-period Linear Generators (MELG).
class Melg19937
A 64-bits Maximally Equidistributed Long-period Linear Generator with a long period (4.32e+6,001).
class Melg44497
A 64-bits Maximally Equidistributed Long-period Linear Generator with a long period (8.55e+13,395).
class Melg607
A 64-bits Maximally Equidistributed Long-period Linear Generator with a long period (5.31e+182).
Functions
virtual void BaseMELG< SIZE >::_setstate (const std::uint64_t seed) noexcept override
Sets the internal state of this PRNG with a 64-bits integer seed.
virtual void BaseMELG< SIZE >::_setstate (const utils::UInt128 &seed) noexcept override
Sets the internal state of this PRNG with a 128-bits integer seed.
BaseMELG< SIZE >::BaseMELG () noexcept
Default empty constructor.
BaseMELG< SIZE >::BaseMELG (const double seed)
Valued constructor (double).
BaseMELG< SIZE >::BaseMELG (const int seed) noexcept
Valued constructor (int).
BaseMELG< SIZE >::BaseMELG (const long long seed) noexcept
Valued constructor (long long).
BaseMELG< SIZE >::BaseMELG (const long seed) noexcept
Valued constructor (long)
BaseMELG< SIZE >::BaseMELG (const state_type &internal_state) noexcept
Valued constructor (full state).
BaseMELG< SIZE >::BaseMELG (const unsigned int seed) noexcept
Valued constructor (unsigned int).
BaseMELG< SIZE >::BaseMELG (const unsigned long long seed) noexcept
Valued constructor (unsigned long long).
BaseMELG< SIZE >::BaseMELG (const unsigned long seed) noexcept
Valued constructor (unsigned long).
BaseMELG< SIZE >::BaseMELG (const utils::UInt128 &seed) noexcept
Valued constructor (unsigned 128-bits).
void BaseMELG< SIZE >::seed () noexcept
Initializes internal state (empty signature).
void BaseMELG< SIZE >::seed (const double seed_)
Initializes internal state (double).
void BaseMELG< SIZE >::seed (const int seed_) noexcept
Initializes internal state (int).
void BaseMELG< SIZE >::seed (const long long seed_) noexcept
Initializes internal state (long long).
void BaseMELG< SIZE >::seed (const long seed_) noexcept
Initializes internal state (long)
void BaseMELG< SIZE >::seed (const unsigned int seed_) noexcept
Initializes internal state (unsigned int).
void BaseMELG< SIZE >::seed (const unsigned long long seed_) noexcept
Initializes internal state (unsigned long long).
void BaseMELG< SIZE >::seed (const unsigned long seed_) noexcept
Initializes internal state (unsigned long).
void BaseMELG< SIZE >::seed (const utils::UInt128 &seed_) noexcept
Initializes internal state (unsigned 128-bits).
Detailed Description
This is the group for all the CppRandLib implementations of Maximally Equidistributed Long-period Linear Generators (MELG) algorithm.
Maximally Equidistributed Long-period Linear Generators (MELG) use linear recurrence based on state transitions with double feedbacks and linear output transformations with several memory references.
MELGs offer large to very large periods with best known results in the evaluation of their randomness. They ensure a maximally equidistributed generation of pseudo random numbers. They pass all TestU01 tests and newer ones but are the slowest to compute ones in the base of PRNGs that have been implemented in CppRandLib.
Function Documentation
_setstate() [1/2]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::_setstate (const std::uint64_t seed_) inline override virtual noexcept
Sets the internal state of this PRNG with a 64-bits integer seed.
Sets the internal state of this PRNG with a 64-*bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
_setstate() [2/2]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::_setstate (const utils::UInt128 & seed) inline override virtual noexcept
Sets the internal state of this PRNG with a 128-bits integer seed.
Sets the internal state of this PRNG with a 128-bits integer seed.
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::_setstate(), and seed().
BaseMELG() [1/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG () inline noexcept
Default empty constructor.
Empty constructor.
References BaseMELG(), and seed().
Referenced by BaseMELG().
BaseMELG() [2/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const double seed_) inline
Valued constructor (double).
Valued constructor (double).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [3/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const int seed_) inline noexcept
Valued constructor (int).
Valued constructor (int).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [4/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const long long seed_) inline noexcept
Valued constructor (long long).
Valued constructor (long long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [5/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const long seed_) inline noexcept
Valued constructor (long)
Valued constructor (long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [6/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const state_type & internal_state) inline noexcept
Valued constructor (full state).
Valued constructor (full state).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::setstate().
BaseMELG() [7/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const unsigned int seed_) inline noexcept
Valued constructor (unsigned int).
Valued constructor (unsigned int).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [8/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const unsigned long long seed_) inline noexcept
Valued constructor (unsigned long long).
Valued constructor (unsigned long long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [9/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const unsigned long seed_) inline noexcept
Valued constructor (unsigned long).
Valued constructor (unsigned long).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
BaseMELG() [10/10]
template<const std::uint32_t SIZE> BaseMELG< SIZE >::BaseMELG (const utils::UInt128 & seed_) inline noexcept
Valued constructor (unsigned 128-bits).
Valued constructor (utils::UInt128).
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
seed() [1/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed () inline virtual noexcept
Initializes internal state (empty signature).
Sets the internal state of this PRNG from current time (empty signature).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
Referenced by _setstate(), BaseMELG(), seed(), seed(), seed(), seed(), and seed().
seed() [2/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const double seed_) inline virtual
Initializes internal state (double).
Initializes internal state (double).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
seed() [3/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const int seed_) inline virtual noexcept
Initializes internal state (int).
Initializes internal state (int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [4/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const long long seed_) inline virtual noexcept
Initializes internal state (long long).
Initializes internal state (long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [5/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const long seed_) inline virtual noexcept
Initializes internal state (long)
Initializes internal state (long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [6/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const unsigned int seed_) inline virtual noexcept
Initializes internal state (unsigned int).
Initializes internal state (unsigned int).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [7/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const unsigned long long seed_) inline virtual noexcept
Initializes internal state (unsigned long long).
Initializes internal state (unsigned long long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().
seed() [8/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const unsigned long seed_) inline virtual noexcept
Initializes internal state (unsigned long).
Initializes internal state (unsigned long).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References seed().
seed() [9/9]
template<const std::uint32_t SIZE> void BaseMELG< SIZE >::seed (const utils::UInt128 & seed_) inline virtual noexcept
Initializes internal state (unsigned 128-bits).
Initializes internal state (unsigned 128-bits).
Reimplemented from BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >.
Reimplemented in Melg19937, Melg44497, and Melg607.
References BaseRandom< ListSeedState< utils::SplitMix64, std::uint64_t, SIZE >, std::uint64_t >::seed().