CppRandLib - c++11: CounterKeyState Struct Reference
CounterKeyState Struct Reference
Algorithms Internal States Definitions
The internal state of counter-based Pseudo Random Numbers Generators.
#include <counterkeystate.h>
Public Types
using value_type = std::uint64_t
Public Member Functions
void seed () noexcept
Initalizes the attribute key according to the original recommendations in document [9] - see file README.md.
void seed (const value_type seed_) noexcept
Initalizes the attribute key according to the original recommendations in document [9] - see file README.md.
Public Attributes
value_type counter { 0 }
value_type key { 1 }
Detailed Description
The internal state of counter-based Pseudo Random Numbers Generators.
Member Function Documentation
seed() [1/2]
void CounterKeyState::seed () inline noexcept
Initalizes the attribute key according to the original recommendations in document [9] - see file README.md.
References utils::balanced_bits_generation(), and utils::set_random_seed64().
seed() [2/2]
void CounterKeyState::seed (const value_type seed_) inline noexcept
Initalizes the attribute key according to the original recommendations in document [9] - see file README.md.
References utils::balanced_bits_generation().
The documentation for this struct was generated from the following file:
counterkeystate.h